/****************************************************************************
****************************************************************************/
USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='01', ARQATU='Rev01.sql';
/****************************************************************************
****************************************************************************/

ALTER TABLE OCLIENTE ADD IDTPCONHEC INT;
ALTER TABLE OCLIENTE ALTER COLUMN ENDERECO VARCHAR(100);
ALTER TABLE OCLIENTE ALTER COLUMN BAIRRO VARCHAR(50);
GO

CREATE TABLE OTPCONHEC
(	IDTPCONHEC  integer  NOT NULL ,
	NMCONHEC  varchar(25)  NULL ,
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NULL 
)
go

ALTER TABLE OTPCONHEC
	ADD CONSTRAINT  XPK_OTPCONHEC PRIMARY KEY   NONCLUSTERED (IDTPCONHEC  ASC)
go
exec sp_bindefault DF_1, 'OTPCONHEC.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OTPCONHEC.TIMESTAMP'
go
ALTER TABLE OCLIENTE
	ADD CONSTRAINT  FK_TPCONHEC FOREIGN KEY (IDTPCONHEC) REFERENCES OTPCONHEC(IDTPCONHEC)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

INSERT OTPCONHEC (IDTPCONHEC, NMCONHEC) VALUES(1,'Panfletagem');
INSERT OTPCONHEC (IDTPCONHEC, NMCONHEC) VALUES(2,'Passante');
INSERT OTPCONHEC (IDTPCONHEC, NMCONHEC) VALUES(3,'Indicação');
INSERT OTPCONHEC (IDTPCONHEC, NMCONHEC) VALUES(4,'Carro de Som');
INSERT OTPCONHEC (IDTPCONHEC, NMCONHEC) VALUES(5,'Televisão');
INSERT OTPCONHEC (IDTPCONHEC, NMCONHEC) VALUES(6,'Jornal');
INSERT OTPCONHEC (IDTPCONHEC, NMCONHEC) VALUES(7,'Revista');
INSERT OTPCONHEC (IDTPCONHEC, NMCONHEC) VALUES(8,'Outros');
go 

CREATE TABLE OTAREFAEVT
(	IDTAREFA  integer  IDENTITY (1,1) ,
	IDLOJA  int  NOT NULL ,
	IDEVENTO  int  NULL ,
	IDATENDIMENTO  int  NULL ,
	DSCTAREFA  ntext  NULL ,
	TITULO  varchar(50)  NULL ,
	DTTAREFA  datetime  NULL ,
	SITTAREFA  char(2)  NULL ,
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NULL 
)
go

ALTER TABLE OTAREFAEVT 
   ADD CONSTRAINT PK_OTAREFAEVT PRIMARY KEY
   NONCLUSTERED (IDTAREFA  ASC,IDLOJA  ASC)
go

exec sp_bindefault DF_1, 'OTAREFAEVT.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OTAREFAEVT.TIMESTAMP'
go
ALTER TABLE OTAREFAEVT
	ADD CONSTRAINT  FK_LOJA FOREIGN KEY (IDLOJA) REFERENCES OLOJA(IDLOJA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE OTAREFAEVT
	ADD CONSTRAINT  FK_EVENTO FOREIGN KEY (IDLOJA,IDEVENTO) REFERENCES OEVENTOAGENDA(IDLOJA,IDEVENTO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go


ALTER TABLE OTAREFAEVT
	ADD CONSTRAINT  FK_ATENDIMENTO FOREIGN KEY (IDLOJA,IDATENDIMENTO) REFERENCES OATENDIMENTO(IDLOJA,IDATENDIMENTO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [dbo].[OMAQDISPAROS] NOCHECK CONSTRAINT [R_226]
GO
ALTER TABLE [dbo].[OMAQDISPAROS] NOCHECK CONSTRAINT [R_230]
GO
/****** Object:  Table [dbo].[GPESQUISA]    Script Date: 09/03/2010 16:46:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[GPESQUISA](
	[IDPESQUISA] [int] IDENTITY(1,1) NOT NULL,
	[CODSIS] [varchar](20) NOT NULL,
	[IDMODU] [varchar](20) NOT NULL,
	[NOMEPESQUISA] [varchar](40) NULL,
	[TIPOPESQUISA] [varchar](20) NULL,
	[DSCPESQUISA] [varchar](200) NULL,
	[ESCOPO] [int] NULL CONSTRAINT [DF_GPESQUISA_ESCOPO]  DEFAULT ((0)),
	[PESQDEFAULT] [int] NULL,
	[PESQSQL] [text] NULL,
	[IDUSU] [varchar](10) NOT NULL,
	[IDCONEXAO] [int] NULL,
	[TAGCAMPOS] [text] NULL,
 CONSTRAINT [PK_GPESQUISA] PRIMARY KEY CLUSTERED 
(
	[IDPESQUISA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[GPESQUISA]  WITH CHECK ADD  CONSTRAINT [FK_GPESQUISA_CODSIS] FOREIGN KEY([CODSIS])
REFERENCES [dbo].[SISTEMA] ([CODSIS])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[GPESQUISA] CHECK CONSTRAINT [FK_GPESQUISA_CODSIS]
GO
ALTER TABLE [dbo].[GPESQUISA]  WITH NOCHECK ADD  CONSTRAINT [FK_GPESQUISA_GCONEXOES] FOREIGN KEY([IDCONEXAO])
REFERENCES [dbo].[GCONEXOES] ([IDCONEXAO])
GO
ALTER TABLE [dbo].[GPESQUISA] NOCHECK CONSTRAINT [FK_GPESQUISA_GCONEXOES]
GO
ALTER TABLE [dbo].[GPESQUISA]  WITH CHECK ADD  CONSTRAINT [FK_GPESQUISA_IDUSU] FOREIGN KEY([IDUSU])
REFERENCES [dbo].[USUARIO] ([IDUSU])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[GPESQUISA] CHECK CONSTRAINT [FK_GPESQUISA_IDUSU]

ALTER TABLE [dbo].[GPESQUISA]  WITH CHECK ADD  CONSTRAINT [FK_GPESQUISA_IDMODU] FOREIGN KEY([IDMODU])
REFERENCES [dbo].[MODULO] ([IDMODU])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[GPESQUISA] CHECK CONSTRAINT [FK_GPESQUISA_IDMODU]
GO
