/****************************************************************************
****************************************************************************/
USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='13', ARQATU='Rev13.sql';
/****************************************************************************
****************************************************************************/
DELETE FROM OCONTATO WHERE IDCONTATO>=3
SET IDENTITY_INSERT OCONTATO on;
INSERT INTO OCONTATO (IDLOJA, IDCONTATO, DTCADASTRO, PJ, NOME) VALUES (1,  3, GetDate(), 0, 'Caixa');
INSERT INTO OCONTATO (IDLOJA, IDCONTATO, DTCADASTRO, PJ, NOME) VALUES (1,  4, GetDate(), 0, 'CCorrente');
INSERT INTO OCONTATO (IDLOJA, IDCONTATO, DTCADASTRO, PJ, NOME) VALUES (1,  5, GetDate(), 0, 'Agua Mineral');
INSERT INTO OCONTATO (IDLOJA, IDCONTATO, DTCADASTRO, PJ, NOME) VALUES (1,  6, GetDate(), 0, 'Xerox');
INSERT INTO OCONTATO (IDLOJA, IDCONTATO, DTCADASTRO, PJ, NOME) VALUES (1,  7, GetDate(), 0, 'Adesivos');
INSERT INTO OCONTATO (IDLOJA, IDCONTATO, DTCADASTRO, PJ, NOME) VALUES (1,  8, GetDate(), 0, 'Chaveiro');
INSERT INTO OCONTATO (IDLOJA, IDCONTATO, DTCADASTRO, PJ, NOME) VALUES (1,  9, GetDate(), 0, 'Formedics');
INSERT INTO OCONTATO (IDLOJA, IDCONTATO, DTCADASTRO, PJ, NOME) VALUES (1, 10, GetDate(), 0, 'Marcos - Pedreiro');
SET IDENTITY_INSERT OCONTATO off;

ALTER TABLE FLAN ALTER COLUMN IDVENDA INT NULL;
ALTER TABLE FLAN ALTER COLUMN IDPGTO INT NULL;

ALTER TABLE OATENDIMENTO_VENDA DROP FK_AV_CVENDA
GO
ALTER TABLE OATENDIMENTO_VENDA DROP FK_AV_OATENDIMENTO
GO

ALTER TABLE OATENDIMENTO_VENDA
	ADD CONSTRAINT  FK_AV_CVENDA FOREIGN KEY (IDLOJA,IDVENDA) REFERENCES CVENDA(IDLOJA,IDVENDA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go


ALTER TABLE OATENDIMENTO_VENDA
	ADD CONSTRAINT  FK_AV_OATENDIMENTO FOREIGN KEY (IDLOJA,IDATENDIMENTO) REFERENCES OATENDIMENTO(IDLOJA,IDATENDIMENTO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go
