/****************************************************************************
****************************************************************************/
USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='15', ARQATU='Rev15.sql';
/****************************************************************************
****************************************************************************/
Alter Table FCCORRENTE ADD DTFECHAMENTO DateTime;
Alter Table FCCORRENTE ADD SLDFECHAMENTO Decimal(9,2);
Alter Table FLAN ADD TPDOC Char(2);
Alter Table FLAN ADD SALDO Decimal(9,2);
Alter Table SMOVEST ADD SALDO Decimal(9,2);
Alter Table SMOVEST ADD TPLAN CHAR(2);
Alter Table SMOVEST ADD TPTRANSA CHAR(1);
Alter Table SMOVEST ADD IDTRANSF INTEGER;
Alter Table SMOVEST ADD IDVENDA INTEGER;
Alter Table SMOVEST ADD OBS Varchar(80);
Alter Table SMOVEST ADD DTCADASTRO DateTime;
Alter Table SMOVEST ADD CODSIT Char(1);
Alter Table SMOVEST ADD FAVORECIDO VarChar(50);
go
--SELECT * FROM FLAN WHERE  (NDOC<>'' OR NOT NDOC IS NULL) and TPTRANSA='C';
UPDATE FLAN SET TPTRANSA='C' WHERE  TPTRANSA IS NULL AND IDCONTA =2;
UPDATE FLAN SET CODSIT='' WHERE  CODSIT IS NULL;
UPDATE FLAN SET TPDOC='CV' WHERE TPTRANSA='C' AND (NDOC<>'' OR NOT NDOC IS NULL);
UPDATE FLAN SET IDDESP=1 WHERE IDDESP<>1 AND TPDOC='CV';

UPDATE SMOVEST SET TPLAN='D' WHERE QTDITEM<0;
UPDATE SMOVEST SET TPTRANSA='D' WHERE QTDITEM<0;
UPDATE SMOVEST SET TPLAN='C' WHERE QTDITEM>0;
UPDATE SMOVEST SET TPTRANSA='C' WHERE QTDITEM>0;
UPDATE SMOVEST SET IDFOR=1 WHERE TPDOC='CV';
UPDATE SMOVEST SET IDVENDA=NUMDOC Where NUMDOC<>'' and Not NUMDOC is Null And  TPDOC='CV';
UPDATE SMOVEST SET DTCADASTRO=DTMOV ;
UPDATE SMOVEST SET CODSIT='';
UPDATE SMOVEST SET FAVORECIDO=(Select NOME From OCONTATO Where IDCONTATO=SMOVEST.IDFOR);


