/****************************************************************************
****************************************************************************/
USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='19', ARQATU='Rev19.sql';
/****************************************************************************
****************************************************************************/
Alter Table OMAQUINA     ADD [IDTPMAQ] [int] NULL
GO
Alter Table OMAQDISPAROS ADD [IDMANIPULO] [int] NULL
GO
Alter Table OMAQDISPAROS ADD [IDLAMP] [int] NULL
GO
Alter Table OMAQDISPAROS ADD [IDTPTRATAMENTO] [int] NULL
GO
Alter Table OCLIENTE     ADD [ISENTO] [int] NULL
GO
Alter Table OATENDIMENTO ADD [IDMANIPULO] [int] NULL
GO
Alter Table OSESSAO ADD [IDMANIPULO] [int] NULL
GO
exec sp_bindefault DF_1, 'OATENDIMENTO.IDMANIPULO'
go
exec sp_bindefault DF_1, 'OSESSAO.IDMANIPULO'
go
exec sp_bindefault DF_0, 'OCLIENTE.ISENTO'
GO

CREATE TABLE [dbo].[OTPMAQ](
	[IDTPMAQ] [int] IDENTITY(1,1) NOT NULL,
	[DSCMAQ] [varchar](20) NULL,
	[TPNUM] [int] NOT NULL,
	[ALTERSTAMP] [int] NULL,
	[TIMESTAMP] [datetime] NULL,
 CONSTRAINT [PK_IDTPMAQ] PRIMARY KEY CLUSTERED 
(
	[IDTPMAQ] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

exec sp_bindefault DF_1, 'OTPMAQ.ALTERSTAMP';
exec sp_bindefault DF_Now, 'OTPMAQ.TIMESTAMP';
exec sp_bindefault DF_0, 'OTPMAQ.TPNUM';

INSERT INTO OTPMAQ (DSCMAQ, TPNUM) VALUES ('FORMED', 2)
GO
INSERT INTO OTPMAQ (DSCMAQ, TPNUM) VALUES ('M80', 1)
GO
INSERT INTO OTPMAQ (DSCMAQ, TPNUM) VALUES ('A4', 1)
GO

CREATE TABLE OTPMANUT
(	IDTPMANUT  int  IDENTITY (1,1),
	DSCMANUT  varchar(20)  NULL,
	OBJMANUT  int  NOT NULL,
	ALTERSTAMP  int  NULL,
	TIMESTAMP  datetime  NULL
)
go
ALTER TABLE OTPMANUT ADD CONSTRAINT  PK_IDTPMANUT PRIMARY KEY   NONCLUSTERED (IDTPMANUT  ASC)
go
exec sp_bindefault DF_1, 'OTPMANUT.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OTPMANUT.TIMESTAMP'
go
exec sp_bindefault DF_0, 'OTPMANUT.OBJMANUT'
go

INSERT INTO OTPMANUT (DSCMANUT, OBJMANUT) VALUES ('Troca de Água', 1)
GO
INSERT INTO OTPMANUT (DSCMANUT, OBJMANUT) VALUES ('Troca de Lampada', 2)
GO

CREATE TABLE OMAQMANUT
(	IDMANUT  integer  IDENTITY (1,1),
	IDTPMANUT  int  NULL,
	IDMAQUINA  int  NULL,
	IDMANIPULO  int  NULL,
	DTMANUT  datetime  NULL,
	DSCMANUT  varchar(100)  NULL,
	ALTERSTAMP  integer  NULL,
	TIMESTAMP  datetime  NULL
)
go
ALTER TABLE OMAQMANUT ADD CONSTRAINT  PK_IDMANUT PRIMARY KEY CLUSTERED (IDMANUT  ASC)
go
exec sp_bindefault DF_1, 'OMAQMANUT.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OMAQMANUT.TIMESTAMP'
go

CREATE TABLE OTPMANIPULO
(	IDTPMANIPULO  int  IDENTITY (1,1),
	DSCMANIPULO  varchar(20)  NULL, 
	ALTERSTAMP  integer  NULL,
	TIMESTAMP  datetime  NULL
)
go
ALTER TABLE OTPMANIPULO	ADD CONSTRAINT  PK_IDTPMANIPULO PRIMARY KEY CLUSTERED (IDTPMANIPULO  ASC)
go
exec sp_bindefault DF_1, 'OTPMANIPULO.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OTPMANIPULO.TIMESTAMP'
go
INSERT INTO OTPMANIPULO (DSCMANIPULO) VALUES ('Pequeno')
GO
INSERT INTO OTPMANIPULO (DSCMANIPULO) VALUES ('Grande')
GO

CREATE TABLE OMANIPULO
(	IDMANIPULO  int  IDENTITY (1,1),
	CODMANIPULO  varchar(20)  NULL,
	IDTPMANIPULO  int  NULL,
	ALTERSTAMP  integer  NULL,
	TIMESTAMP  datetime  NULL
)
go
ALTER TABLE OMANIPULO ADD CONSTRAINT  PK_IDMANIPULO PRIMARY KEY CLUSTERED (IDMANIPULO  ASC)
go
exec sp_bindefault DF_1, 'OMANIPULO.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OMANIPULO.TIMESTAMP'
go
INSERT INTO OMANIPULO (CODMANIPULO, IDTPMANIPULO) VALUES ('MP01',1)
GO

CREATE TABLE OLAMPADA
(	IDMANIPULO  int  NOT NULL,
	IDLAMP  int  NOT NULL,	
	ALTERSTAMP  integer  NULL,
	TIMESTAMP  datetime  NULL
)
go
ALTER TABLE OLAMPADA ADD CONSTRAINT PK_IDLAMPADA PRIMARY KEY   NONCLUSTERED (IDMANIPULO  ASC,IDLAMP  ASC)
go
exec sp_bindefault DF_1, 'OLAMPADA.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OLAMPADA.TIMESTAMP'
go

INSERT INTO OLAMPADA(IDMANIPULO, IDLAMP) VALUES (1, 1)
GO


ALTER TABLE OLAMPADA
	ADD CONSTRAINT  R_129 FOREIGN KEY (IDMANIPULO) REFERENCES OMANIPULO(IDMANIPULO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE OMANIPULO
	ADD CONSTRAINT  R_126 FOREIGN KEY (IDTPMANIPULO) REFERENCES OTPMANIPULO(IDTPMANIPULO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE OMAQMANUT
	ADD CONSTRAINT  R_132 FOREIGN KEY (IDTPMANUT) REFERENCES OTPMANUT(IDTPMANUT)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE OMAQMANUT
	ADD CONSTRAINT  R_133 FOREIGN KEY (IDMAQUINA) REFERENCES OMAQUINA(IDMAQUINA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go


ALTER TABLE OMAQMANUT
	ADD CONSTRAINT  R_134 FOREIGN KEY (IDMANIPULO) REFERENCES OMANIPULO(IDMANIPULO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE OMAQDISPAROS
	ADD CONSTRAINT  R_130 FOREIGN KEY (IDMANIPULO,IDLAMP) REFERENCES OLAMPADA(IDMANIPULO,IDLAMP)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go
ALTER TABLE OMAQUINA
	ADD CONSTRAINT  R_127 FOREIGN KEY (IDTPMAQ) REFERENCES OTPMAQ(IDTPMAQ)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

CREATE TABLE OAREA_TRATAMENTO
(	IDAREA  int  NOT NULL,
	IDTPTRATAMENTO  int  NOT NULL,
	IDTPMANIPULO  int  NOT NULL, 
	TEMPOMIN  integer  NULL,
	TEMPOMED  integer  NULL,
	TEMPOMAX  varchar(50)  NULL,
	INDICEH  decimal(3,2)  NULL,
	ALTERSTAMP  integer  NULL,
	TIMESTAMP  datetime  NULL
)
go

--Alter Table OAREA_TRATAMENTO ADD INDICEH decimal(3,2)  NULL;

ALTER TABLE OAREA_TRATAMENTO ADD CONSTRAINT  PK_AREATRATAMENTO PRIMARY KEY CLUSTERED (IDAREA  ASC,IDTPTRATAMENTO  ASC,IDTPMANIPULO  ASC)
go
exec sp_bindefault DF_1, 'OAREA_TRATAMENTO.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OAREA_TRATAMENTO.TIMESTAMP'
go
ALTER TABLE OAREA_TRATAMENTO
	ADD CONSTRAINT  R_124 FOREIGN KEY (IDAREA) REFERENCES OAREA(IDAREA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go
ALTER TABLE OAREA_TRATAMENTO
	ADD CONSTRAINT  R_125 FOREIGN KEY (IDTPTRATAMENTO) REFERENCES OTPTRATAMENTO(IDTPTRATAMENTO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go
ALTER TABLE OAREA_TRATAMENTO
	ADD CONSTRAINT  R_135 FOREIGN KEY (IDTPMANIPULO) REFERENCES OTPMANIPULO(IDTPMANIPULO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE OMAQDISPAROS
	ADD CONSTRAINT  R_136 FOREIGN KEY (IDTPTRATAMENTO) REFERENCES OTPTRATAMENTO(IDTPTRATAMENTO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE OATENDIMENTO
	ADD CONSTRAINT  R_137 FOREIGN KEY (IDMANIPULO) REFERENCES OMANIPULO(IDMANIPULO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

UPDATE OCLIENTE SET ISENTO=0
GO
UPDATE OATENDIMENTO SET IDMANIPULO=1
GO
UPDATE OSESSAO SET IDMANIPULO=1
GO
UPDATE OMAQDISPAROS SET IDMANIPULO=1, IDLAMP=1
GO
UPDATE OMAQDISPAROS SET IDTPTRATAMENTO=(SELECT OSESSAO.IDTPTRATAMENTO FROM OATENDIMENTO JOIN OSESSAO ON OSESSAO.IDATENDIMENTO=OATENDIMENTO.IDATENDIMENTO WHERE OSESSAO.IDATENDIMENTO=OMAQDISPAROS.IDATENDIMENTO AND OSESSAO.IDSESSAO=OMAQDISPAROS.IDSESSAO)
GO

DECLARE @LOJA AS VARCHAR(20)
Select @LOJA=NOME from OLOJA WHERE IDLOJA=1;
IF @LOJA='FREGUESIA' UPDATE OMAQUINA SET IDTPMAQ=1;
IF @LOJA='COPACABANA1' UPDATE OMAQUINA SET IDTPMAQ=2;

INSERT INTO OAREA_TRATAMENTO 
(IDAREA, IDTPTRATAMENTO, IDTPMANIPULO, TEMPOMIN, TEMPOMED, TEMPOMAX, INDICEH)
VALUES (1, 1, 1, 0, 15, 0, 0);

INSERT INTO OAREA_TRATAMENTO 
(IDAREA, IDTPTRATAMENTO, IDTPMANIPULO, TEMPOMIN, TEMPOMED, TEMPOMAX, INDICEH)
VALUES (2, 1, 1, 0, 15, 0, 0);

INSERT INTO OAREA_TRATAMENTO 
(IDAREA, IDTPTRATAMENTO, IDTPMANIPULO, TEMPOMIN, TEMPOMED, TEMPOMAX, INDICEH)
VALUES (3, 1, 1, 0, 10, 0, 0);

INSERT INTO OAREA_TRATAMENTO 
(IDAREA, IDTPTRATAMENTO, IDTPMANIPULO, TEMPOMIN, TEMPOMED, TEMPOMAX, INDICEH)
VALUES (4, 1, 1, 0, 15, 0, 0);

INSERT INTO OAREA_TRATAMENTO 
(IDAREA, IDTPTRATAMENTO, IDTPMANIPULO, TEMPOMIN, TEMPOMED, TEMPOMAX, INDICEH)
VALUES (5, 1, 1, 0, 15, 0, 0);

INSERT INTO OAREA_TRATAMENTO 
(IDAREA, IDTPTRATAMENTO, IDTPMANIPULO, TEMPOMIN, TEMPOMED, TEMPOMAX, INDICEH)
VALUES (6, 1, 1, 0, 30, 0, 0);

INSERT INTO OAREA_TRATAMENTO 
(IDAREA, IDTPTRATAMENTO, IDTPMANIPULO, TEMPOMIN, TEMPOMED, TEMPOMAX, INDICEH)
VALUES (7, 1, 1, 0, 15, 0, 2);

INSERT INTO OAREA_TRATAMENTO 
(IDAREA, IDTPTRATAMENTO, IDTPMANIPULO, TEMPOMIN, TEMPOMED, TEMPOMAX, INDICEH)
VALUES (8, 1, 1, 0, 30, 0, 0);

INSERT INTO OAREA_TRATAMENTO 
(IDAREA, IDTPTRATAMENTO, IDTPMANIPULO, TEMPOMIN, TEMPOMED, TEMPOMAX, INDICEH)
VALUES (9, 1, 1, 0, 15, 0, 2);

INSERT INTO OAREA_TRATAMENTO 
(IDAREA, IDTPTRATAMENTO, IDTPMANIPULO, TEMPOMIN, TEMPOMED, TEMPOMAX, INDICEH)
VALUES (10, 1, 1, 0, 15, 0, 0);

INSERT INTO OAREA_TRATAMENTO 
(IDAREA, IDTPTRATAMENTO, IDTPMANIPULO, TEMPOMIN, TEMPOMED, TEMPOMAX, INDICEH)
VALUES (11, 1, 1, 0, 10, 0, 0);

INSERT INTO OAREA_TRATAMENTO 
(IDAREA, IDTPTRATAMENTO, IDTPMANIPULO, TEMPOMIN, TEMPOMED, TEMPOMAX, INDICEH)
VALUES (12, 1, 1, 0, 15, 0, 0);

INSERT INTO OAREA_TRATAMENTO 
(IDAREA, IDTPTRATAMENTO, IDTPMANIPULO, TEMPOMIN, TEMPOMED, TEMPOMAX, INDICEH)
VALUES (13, 1, 1, 0, 30, 0, 0);

INSERT INTO OAREA_TRATAMENTO 
(IDAREA, IDTPTRATAMENTO, IDTPMANIPULO, TEMPOMIN, TEMPOMED, TEMPOMAX, INDICEH)
VALUES (14, 1, 1, 0, 15, 0, 0);

INSERT INTO OAREA_TRATAMENTO 
(IDAREA, IDTPTRATAMENTO, IDTPMANIPULO, TEMPOMIN, TEMPOMED, TEMPOMAX, INDICEH)
VALUES (15, 1, 1, 0, 10, 0, 0);

INSERT INTO OAREA_TRATAMENTO 
(IDAREA, IDTPTRATAMENTO, IDTPMANIPULO, TEMPOMIN, TEMPOMED, TEMPOMAX, INDICEH)
VALUES (16, 1, 1, 0, 30, 0, 0);

INSERT INTO OAREA_TRATAMENTO 
(IDAREA, IDTPTRATAMENTO, IDTPMANIPULO, TEMPOMIN, TEMPOMED, TEMPOMAX, INDICEH)
VALUES (17, 1, 1, 0, 30, 0, 0);

INSERT INTO OAREA_TRATAMENTO 
(IDAREA, IDTPTRATAMENTO, IDTPMANIPULO, TEMPOMIN, TEMPOMED, TEMPOMAX, INDICEH)
VALUES (18, 1, 1, 0, 20, 0, 0);

INSERT INTO OAREA_TRATAMENTO 
(IDAREA, IDTPTRATAMENTO, IDTPMANIPULO, TEMPOMIN, TEMPOMED, TEMPOMAX, INDICEH)
VALUES (19, 1, 1, 0, 30, 0, 0);

INSERT INTO OAREA_TRATAMENTO 
(IDAREA, IDTPTRATAMENTO, IDTPMANIPULO, TEMPOMIN, TEMPOMED, TEMPOMAX, INDICEH)
VALUES (20, 1, 1, 0, 40, 0, 0);

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CPROMO]') AND parent_object_id = OBJECT_ID(N'[dbo].[CVENDA]'))
ALTER TABLE [dbo].[CVENDA] DROP CONSTRAINT [FK_CPROMO]
GO
ALTER TABLE [dbo].[CVENDA]  WITH NOCHECK ADD  CONSTRAINT [FK_CPROMO] FOREIGN KEY([IDPROMO])
REFERENCES [dbo].[CPROMOCAO] ([IDPROMO])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
GO

ALTER TABLE [dbo].[CVENDA] NOCHECK CONSTRAINT [FK_CPROMO]
GO

