/****************************************************************************
****************************************************************************/
USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='21', ARQATU='Rev21.sql';
/****************************************************************************
****************************************************************************/

Alter Table OCLIENTE ADD FLGMARKETING int NULL
GO
Alter Table OCLIENTE ADD FLGAGENDA int NULL
GO
exec sp_bindefault DF_1, 'OCLIENTE.FLGMARKETING'
go
exec sp_bindefault DF_1, 'OCLIENTE.FLGAGENDA'
go

CREATE TABLE FLOTERPS
(	IDLOTE  int  IDENTITY (1,1) ,
	NUMLOTE  varchar(8)  NULL ,
	DTINI  datetime  NULL ,
	DTFIM  datetime  NULL ,
	IDLOJA  int  NULL ,
	DTENVIO  varchar(50)  NULL ,
	SITLOTE  integer  NULL ,
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NULL 
)
go

ALTER TABLE FLOTERPS
	ADD CONSTRAINT  PK_FLOTERPS PRIMARY KEY   NONCLUSTERED (IDLOTE  ASC)
go

exec sp_bindefault DF_1, 'FLOTERPS.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'FLOTERPS.TIMESTAMP'
go

--alter table FNOTAFISCAL add SERIE  varchar(5)  NOT NULL
--ALTER TABLE FNOTAFISCAL drop CONSTRAINT  PK_FNOTAFISCAL

CREATE TABLE FNOTAFISCAL
(	IDLOJA  int  NOT NULL ,
    SERIE  varchar(5)  NOT NULL,
    IDNOTA  int  NOT NULL ,	
	IDVENDA  int  NULL ,	
	IDRECIBO  int  NULL ,
	DTEMISSAO  datetime  NULL ,
	VLTOTAL  decimal(9,2)  NULL ,
	FLGENVIADA  int  NULL ,
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NULL )
go

ALTER TABLE FNOTAFISCAL
	ADD CONSTRAINT  PK_FNOTAFISCAL PRIMARY KEY   NONCLUSTERED (IDLOJA  ASC,SERIE ASC, IDNOTA  ASC)
go

exec sp_bindefault DF_1, 'FNOTAFISCAL.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'FNOTAFISCAL.TIMESTAMP'
go
exec sp_bindefault DF_0, 'FNOTAFISCAL.FLGENVIADA'
go


CREATE TABLE FRECIBO
(	IDLOJA  int  NOT NULL ,
	IDVENDA  int  NULL ,
    SERIE  varchar(5)  NOT NULL ,
	IDRECIBO  int  NOT NULL ,
	DTEMISSAO  datetime  NULL ,
	VLTOTAL  decimal(9,2)  NULL ,
	TIPO  int  NOT NULL ,
	IDLOTE  int  NULL ,	
	STATUS  int  NULL ,
	NATUREZAOP  int  NOT NULL ,
	ASSINATURA  varchar(50)  NULL ,
	REGESPECIALTRIB  int  NULL ,
	SIMPLES  int  NOT NULL ,
	IDRECIBO0  int  NULL ,
	SERIE0  varchar(5)  NULL ,
	TRIBUTACAO  int  NOT NULL ,
	INCENTIVOCULT  integer  NOT NULL ,
	CODSERVFEDERAL  varchar(4)  NOT NULL ,
	CODSERVMUNIC  varchar(20)  NOT NULL ,
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NOT NULL )
go


ALTER TABLE FRECIBO
	ADD CONSTRAINT  PK_FRECIBO PRIMARY KEY   NONCLUSTERED (IDLOJA  ASC, SERIE ASC, IDRECIBO  ASC)
go

--ALTER TABLE FRECIBO drop CONSTRAINT  PK_FRECIBO

exec sp_bindefault DF_1, 'FRECIBO.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'FRECIBO.TIMESTAMP'
go
exec sp_bindefault DF_0, 'FRECIBO.TIPO'
go
exec sp_bindefault DF_1, 'FRECIBO.SERIE'
go
exec sp_bindefault DF_1, 'FRECIBO.STATUS'
go
exec sp_bindefault DF_1, 'FRECIBO.SIMPLES'
go
exec sp_bindefault DF_0, 'FRECIBO.REGESPECIALTRIB'
go
exec sp_bindefault DF_1, 'FRECIBO.TRIBUTACAO'
go
exec sp_bindefault DF_0, 'FRECIBO.INCENTIVOCULT'
go


ALTER TABLE FLOTERPS
	ADD CONSTRAINT  R_144 FOREIGN KEY (IDLOJA) REFERENCES OLOJA(IDLOJA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE FNOTAFISCAL
	ADD CONSTRAINT  R_142 FOREIGN KEY (IDLOJA,IDVENDA) REFERENCES CVENDA(IDLOJA,IDVENDA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE FNOTAFISCAL
	ADD CONSTRAINT  R_143 FOREIGN KEY (IDLOJA,IDRECIBO) REFERENCES FRECIBO(IDLOJA,IDRECIBO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE FRECIBO
	ADD CONSTRAINT  R_141 FOREIGN KEY (IDLOJA,IDVENDA) REFERENCES CVENDA(IDLOJA,IDVENDA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE FRECIBO
	ADD CONSTRAINT  R_145 FOREIGN KEY (IDLOTE) REFERENCES FLOTERPS(IDLOTE)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE FRECIBO drop CONSTRAINT  R_145 
go

ALTER TABLE FRECIBO WITH NOCHECK
	ADD CONSTRAINT  R_145 FOREIGN KEY (IDLOTE) REFERENCES FLOTERPS(IDLOTE)
go
ALTER TABLE [dbo].[FRECIBO] NOCHECK CONSTRAINT [R_145]
GO
