/****************************************************************************
****************************************************************************/
USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='22', ARQATU='Rev22.sql';
/****************************************************************************
****************************************************************************/

Alter Table CVENDA ADD FLGCANCELADA int NULL
GO
Alter Table FNOTAFISCAL ADD FLGCANCELADA int NULL
GO
exec sp_bindefault DF_0, 'CVENDA.FLGCANCELADA'
go
exec sp_bindefault DF_0, 'FNOTAFISCAL.FLGCANCELADA'
go

ALTER TABLE [dbo].[OTAREFAEVT] DROP CONSTRAINT [FK_ATENDIMENTO] 
GO

Alter Table OTAREFAEVT DROP COLUMN IDATENDIMENTO 
GO
Alter Table OTAREFAEVT DROP COLUMN VLPERC 
GO

Alter Table OTAREFAEVT ALTER COLUMN SITTAREFA INT 
GO
Alter Table OTAREFAEVT ADD IDCLIENTE int NULL
GO
Alter Table OTAREFAEVT ADD PRIORIDADE int NULL
GO
Alter Table OTAREFAEVT ADD FLGLEMBRETE int NULL
GO
Alter Table OTAREFAEVT ADD DTLEMBRETE DATETIME NULL
GO
Alter Table OTAREFAEVT ADD IDCLIENTE int NULL
GO
Alter Table OTAREFAEVT ADD IDTPTAREFA int NULL
GO
Alter Table OTAREFAEVT ADD FLGDELETE int NULL
GO
Alter Table OTAREFAEVT ADD FLGAUTO int NULL
GO

exec sp_bindefault DF_0, 'OTAREFAEVT.FLGDELETE'
go
exec sp_bindefault DF_0, 'OTAREFAEVT.FLGAUTO'
go

----------------------------------------------------------------
ALTER TABLE [dbo].[OTAREFAEVT] DROP CONSTRAINT [FK_EVENTO] 
GO
ALTER TABLE [dbo].[OTAREFAEVT]  WITH NOCHECK ADD  CONSTRAINT [FK_EVENTO] FOREIGN KEY([IDLOJA], [IDEVENTO])
REFERENCES [dbo].[OEVENTOAGENDA] ([IDLOJA], [IDEVENTO])
GO
ALTER TABLE [dbo].[OTAREFAEVT] NOCHECK CONSTRAINT [FK_EVENTO]
GO
----------------------------------------------------------------
--ALTER TABLE [dbo].[OTAREFAEVT] DROP CONSTRAINT [FK_ATENDIMENTO] 
--GO
--ALTER TABLE [dbo].[OTAREFAEVT]  WITH NOCHECK ADD  CONSTRAINT [FK_ATENDIMENTO] FOREIGN KEY([IDLOJA], [IDATENDIMENTO])
--REFERENCES [dbo].[OATENDIMENTO] ([IDLOJA], [IDATENDIMENTO])
--GO
--ALTER TABLE [dbo].[OTAREFAEVT] NOCHECK CONSTRAINT [FK_ATENDIMENTO]
--GO
----------------------------------------------------------------
CREATE TABLE OCATTAREFA
(
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NULL ,
	IDCATTAREFA  int  IDENTITY (1,1) ,
	DSCCATTAREFA  varchar(50)  NULL ,
	ATIVO  int  NULL 
)
go

ALTER TABLE OCATTAREFA
	ADD CONSTRAINT  PK_OCATTAREFA PRIMARY KEY   NONCLUSTERED (IDCATTAREFA  ASC)
go
exec sp_bindefault DF_1, 'OCATTAREFA.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OCATTAREFA.TIMESTAMP'
go


CREATE TABLE OTAREFA_CAT
(
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NULL ,
	IDCATTAREFA  int  NOT NULL ,
	IDTAREFA  integer  NOT NULL ,
	IDLOJA  int  NOT NULL 
)
go

ALTER TABLE OTAREFA_CAT
	ADD CONSTRAINT  XPKdboOTAREFA_CAT PRIMARY KEY   NONCLUSTERED (IDCATTAREFA  ASC,IDTAREFA  ASC,IDLOJA  ASC)
go
exec sp_bindefault DF_1, 'OTAREFA_CAT.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OTAREFA_CAT.TIMESTAMP'
go

ALTER TABLE OTAREFA_CAT
	ADD CONSTRAINT  R_146 FOREIGN KEY (IDCATTAREFA) REFERENCES OCATTAREFA(IDCATTAREFA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go
ALTER TABLE OTAREFA_CAT
	ADD CONSTRAINT  R_148 FOREIGN KEY (IDTAREFA,IDLOJA) REFERENCES OTAREFAEVT(IDTAREFA,IDLOJA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

CREATE TABLE OTIPOTAREFA
(	IDTPTAREFA  int  IDENTITY (1,1) ,
	DSCTPTAREFA  varchar(50)  NULL ,
    ATIVO int  NULL ,
    DIFHORA int NULL, 
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NULL
)
go
ALTER TABLE OTIPOTAREFA ADD CONSTRAINT  PK_OTIPOTAREFA PRIMARY KEY NONCLUSTERED (IDTPTAREFA  ASC)
go
exec sp_bindefault DF_1, 'OTIPOTAREFA.ALTERSTAMP'
go
exec sp_bindefault DF_1, 'OTIPOTAREFA.ATIVO'
go
exec sp_bindefault DF_Now, 'OTIPOTAREFA.TIMESTAMP'
go

delete from OTIPOTAREFA
SET IDENTITY_INSERT OTIPOTAREFA on;
INSERT INTO OTIPOTAREFA (IDTPTAREFA, ATIVO, DIFHORA, DSCTPTAREFA) VALUES (1, 1,  -24, 'Confirmar Agenda');
INSERT INTO OTIPOTAREFA (IDTPTAREFA, ATIVO, DIFHORA, DSCTPTAREFA) VALUES (2, 1, -120, 'Enviar e-Mail de Orientação');
INSERT INTO OTIPOTAREFA (IDTPTAREFA, ATIVO, DIFHORA, DSCTPTAREFA) VALUES (3, 1,   48, 'Verificar Avaliação');
INSERT INTO OTIPOTAREFA (IDTPTAREFA, ATIVO, DIFHORA, DSCTPTAREFA) VALUES (4, 1,   24, 'Verificar Cancelamento/Falta de Sessão');
INSERT INTO OTIPOTAREFA (IDTPTAREFA, ATIVO, DIFHORA, DSCTPTAREFA) VALUES (5, 1,  600, 'Verificar Sessão não Marcada');
SET IDENTITY_INSERT OTIPOTAREFA off;

CREATE TABLE GFERIADO
(	DATA  smalldatetime  NOT NULL ,
	DSCFERIADO  varchar(20)  NULL ,
	ESCOPO  int  NULL, 
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NULL )
go
ALTER TABLE GFERIADO ADD CONSTRAINT  PK_GFERIADO PRIMARY KEY   NONCLUSTERED (DATA  ASC)
go
exec sp_bindefault DF_1, 'GFERIADO.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'GFERIADO.TIMESTAMP'
go
exec sp_bindefault DF_0, 'GFERIADO.ESCOPO'
go

Delete From GFERIADO;
INSERT INTO GFERIADO (DATA, DSCFERIADO, ESCOPO) VALUES ('2011-01-01', 'Paz', 1);
INSERT INTO GFERIADO (DATA, DSCFERIADO, ESCOPO) VALUES ('2011-01-20', 'Aniversario Cidade', 1);
INSERT INTO GFERIADO (DATA, DSCFERIADO, ESCOPO) VALUES ('2011-04-21', 'Tiradentes', 1);
INSERT INTO GFERIADO (DATA, DSCFERIADO, ESCOPO) VALUES ('2011-04-23', 'São Jorge', 1);
INSERT INTO GFERIADO (DATA, DSCFERIADO, ESCOPO) VALUES ('2011-09-07', 'Independência', 1);
INSERT INTO GFERIADO (DATA, DSCFERIADO, ESCOPO) VALUES ('2011-10-12', 'Padroeira', 1);
INSERT INTO GFERIADO (DATA, DSCFERIADO, ESCOPO) VALUES ('2011-11-15', 'República', 1);
INSERT INTO GFERIADO (DATA, DSCFERIADO, ESCOPO) VALUES ('2011-12-24', 'Natal', 1);
INSERT INTO GFERIADO (DATA, DSCFERIADO, ESCOPO) VALUES ('2011-12-25', 'Natal', 1);
INSERT INTO GFERIADO (DATA, DSCFERIADO, ESCOPO) VALUES ('2011-12-31', 'Paz', 1);
