/****************************************************************************
****************************************************************************/
USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='20', ARQATU='Rev20.sql';
/****************************************************************************
****************************************************************************/
Alter Table OEVENTOAGENDA     ADD [FLGREMARCADO] [int] NULL
GO
exec sp_bindefault DF_0, 'OEVENTOAGENDA.[FLGREMARCADO]'
go

Update OEVENTOAGENDA Set OEVENTOAGENDA.FLGREMARCADO=1
Where OEVENTOAGENDA.IDEVENTO In (Select Distinct E.IDEVENTO
From OEVENTOAGENDA E join OEVENTOAGENDA E2 On E.IDLOJA=E2.IDLOJA And E.IDCLIENTE=E2.IDCLIENTE
Where E.FLGCANCELADO=1
And E.StartDateTime < E2.StartDateTime
And E2.FLGCANCELADO=0)
go

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CPROMO]') AND parent_object_id = OBJECT_ID(N'[dbo].[CVENDA]'))
ALTER TABLE [dbo].[CVENDA] DROP CONSTRAINT [FK_CPROMO]
go
ALTER TABLE [dbo].[CVENDA] DROP COLUMN IDPROMO
go
ALTER TABLE [dbo].[FLAN] DROP COLUMN OBS
go
ALTER TABLE [dbo].[OLOJA] ADD	[INSCMUNIC]  VARCHAR(20) NULL
go
ALTER TABLE [dbo].[CPROMOCAO] ADD	[DTVENC]  datetime  NULL
go
ALTER TABLE [dbo].[CPROMOCAO] ADD	[DTEMISSAO]  datetime  NULL
go
ALTER TABLE [dbo].[CPROMOCAO] ADD	[NPARCELA]  int  NULL
go
ALTER TABLE [dbo].[CPROMOCAO] ADD	[PRAZO]  int  NULL
go


CREATE TABLE CCUPOM
(	IDCUPOM  integer  IDENTITY (1,1) ,
    IDPROMO  int  NULL ,
	CODCUPOM  varchar(20)  NULL ,
	DTEMISSAO  datetime  NULL ,
	DTVENC  datetime  NULL ,
	ATIVO  int  NULL ,
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NULL 
)
go

ALTER TABLE CCUPOM ADD CONSTRAINT  PK_CCUPOM PRIMARY KEY   NONCLUSTERED (IDCUPOM  ASC)
go

exec sp_bindefault DF_1, 'CCUPOM.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'CCUPOM.TIMESTAMP'
go


CREATE TABLE CCUPOM_VENDA
(	IDCUPOM  integer  NOT NULL ,
	IDLOJA  int  NOT NULL ,
	IDVENDA  int  NOT NULL ,
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NULL 
)
go


ALTER TABLE CCUPOM_VENDA ADD CONSTRAINT  PK_CCUPOMVENDA PRIMARY KEY   NONCLUSTERED (IDLOJA  ASC,IDVENDA  ASC,IDCUPOM  ASC)
go
exec sp_bindefault DF_1, 'CCUPOM_VENDA.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'CCUPOM_VENDA.TIMESTAMP'
go

ALTER TABLE CCUPOM
	ADD CONSTRAINT  R_138 FOREIGN KEY (IDPROMO) REFERENCES CPROMOCAO(IDPROMO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE CCUPOM_VENDA
	ADD CONSTRAINT  R_139 FOREIGN KEY (IDCUPOM) REFERENCES CCUPOM(IDCUPOM)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE CCUPOM_VENDA
	ADD CONSTRAINT  R_140 FOREIGN KEY (IDLOJA,IDVENDA) REFERENCES CVENDA(IDLOJA,IDVENDA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go




