/****************************************************************************
****************************************************************************/
USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='24', ARQATU='Rev24.sql';
/****************************************************************************
****************************************************************************/

Alter Table OTPMAQ ADD NUMTRATAMENTO int NULL
GO
exec sp_bindefault DF_0, 'OTPMAQ.NUMTRATAMENTO'
GO
sp_RENAME 'FNOTAFISCAL.IDNOTA' , 'NUMNOTA', 'COLUMN'
GO

ALTER TABLE FRECIBO DROP CONSTRAINT  R_145 
go
ALTER TABLE FLOTERPS DROP CONSTRAINT  PK_FLOTERPS 
go
ALTER TABLE FLOTERPS ADD IDLOTE2 INT NULL
go
UPDATE FLOTERPS SET IDLOTE2=IDLOTE
GO 
ALTER TABLE FLOTERPS DROP COLUMN IDLOTE 
go
sp_RENAME 'FLOTERPS.IDLOTE2' , 'IDLOTE', 'COLUMN'
GO

ALTER TABLE FLOTERPS ALTER COLUMN IDLOJA INT NOT NULL
go
ALTER TABLE FLOTERPS ALTER COLUMN IDLOTE INT NOT NULL
go

ALTER TABLE FLOTERPS ADD CONSTRAINT  PK_FLOTERPS PRIMARY KEY   NONCLUSTERED (IDLOJA ASC, IDLOTE  ASC)
go

ALTER TABLE FRECIBO  WITH NOCHECK
   ADD  CONSTRAINT R_145 FOREIGN KEY(IDLOJA, IDLOTE) REFERENCES FLOTERPS(IDLOJA, IDLOTE)
GO
ALTER TABLE FRECIBO NOCHECK CONSTRAINT R_145
GO
