/****************************************************************************
****************************************************************************/
--USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='44', ARQATU='Rev44.sql';
/****************************************************************************
****************************************************************************/

IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OTRATAMENTO_PROD]') AND name = N'PK_OTRATAMENTO_PROD') ALTER TABLE [dbo].[OTRATAMENTO_PROD] DROP CONSTRAINT [PK_OTRATAMENTO_PROD]
GO
EXECUTE sp_rename N'dbo.OTRATAMENTO_PROD', N'OTRATAMENTO_PROD1', 'OBJECT'  
GO 
/**/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OTRATAMENTO_PROD](
	[IDLOJA] [int] NOT NULL,
	[ID] [int] NOT NULL,
	[IDTPSERVICO] [int] NULL,
	[IDTPTRATAMENTO] [int] NULL,
	[IDAREA] [int] NULL,
	[IDPROD] [decimal](10, 0) NULL,
	[ALTERSTAMP] [int] NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
 CONSTRAINT [PK_OTRATAMENTO_PROD] PRIMARY KEY CLUSTERED 
([IDLOJA] ASC, [ID] ASC) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]) ON [PRIMARY]
GO
exec sp_bindefault DF_1, 'OTRATAMENTO_PROD.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OTRATAMENTO_PROD.TIMESTAMP'
go
SET ANSI_PADDING OFF
GO

INSERT INTO dbo.OTRATAMENTO_PROD (
[IDLOJA],[ID],[IDTPSERVICO],[IDTPTRATAMENTO],[IDAREA],[IDPROD],[ALTERSTAMP],[TIMESTAMP]
) 
SELECT 
(SELECT MIN(IDLOJA) FROM OLOJA),[ID],[IDTPSERVICO],[IDTPTRATAMENTO],[IDAREA],[IDPROD],[ALTERSTAMP],[TIMESTAMP]
FROM OTRATAMENTO_PROD1
GO 

DROP TABLE OTRATAMENTO_PROD1
GO
/*******************************************************/
/*******************************************************/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_SESTPROD_PRODUTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[SESTPROD]')) ALTER TABLE [dbo].[SESTPROD] DROP CONSTRAINT [FK_SESTPROD_PRODUTO]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_SESTPROD_ESTOQUE]') AND parent_object_id = OBJECT_ID(N'[dbo].[SESTPROD]')) ALTER TABLE [dbo].[SESTPROD] DROP CONSTRAINT [FK_SESTPROD_ESTOQUE]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_SEST_EST]') AND parent_object_id = OBJECT_ID(N'[dbo].[SEST_LOJA]')) ALTER TABLE [dbo].[SEST_LOJA] DROP CONSTRAINT [FK_SEST_EST]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[SESTOQUE]') AND name = N'PK_SESTOQUE') ALTER TABLE [dbo].[SESTOQUE] DROP CONSTRAINT [PK_SESTOQUE]
GO
EXECUTE sp_rename N'dbo.SESTOQUE', N'SESTOQUE1', 'OBJECT'  
GO 
/**/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SESTOQUE]
(	[IDLOJA] int NOT NULL,
	[IDEST] int NOT NULL,
	[DSCEST] varchar(20)  NULL ,
	[DTFECHAMENTO] datetime  NULL ,
	[ATIVO] int  NULL ,
	[ALTERSTAMP] int NULL ,
	[TIMESTAMP] datetime  NULL
)
go
ALTER TABLE SESTOQUE ADD CONSTRAINT PK_SESTOQUE PRIMARY KEY   NONCLUSTERED (IDLOJA ASC, IDEST  ASC)
go
exec sp_bindefault DF_1, 'SESTOQUE.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'SESTOQUE.TIMESTAMP'
go
exec sp_bindefault DF_1, 'SESTOQUE.ATIVO'
go
SET ANSI_PADDING OFF
GO

INSERT INTO dbo.SESTOQUE (
[IDLOJA],[IDEST],[DSCEST],[DTFECHAMENTO],[ATIVO],[ALTERSTAMP]
) 
SELECT 
(SELECT MIN(IDLOJA) FROM OLOJA),[IDEST],[DSCEST],[DTFECHAMENTO],[ATIVO],[ALTERSTAMP]
FROM SESTOQUE1
GO 

DROP TABLE SESTOQUE1
GO
/*******************************************************/
/*******************************************************/
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='SESTPROD' AND C.NAME='IDLOJA') ALTER TABLE SESTPROD ADD IDLOJA INT
GO
UPDATE SESTPROD SET IDLOJA=(SELECT MIN(IDLOJA) FROM OLOJA)
GO
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='SEST_LOJA' AND C.NAME='IDLOJA') ALTER TABLE SEST_LOJA ADD IDLOJA INT
GO
UPDATE SEST_LOJA SET IDLOJA=(SELECT MIN(IDLOJA) FROM OLOJA)
GO
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='SMOVEST' AND C.NAME='IDLOJA') ALTER TABLE SMOVEST ADD IDLOJA INT
GO
UPDATE SMOVEST SET IDLOJA=(SELECT MIN(IDLOJA) FROM OLOJA)
GO
ALTER TABLE SESTPROD
	ADD CONSTRAINT  FK_SESTPROD_ESTOQUE FOREIGN KEY (IDLOJA, IDEST) REFERENCES SESTOQUE(IDLOJA, IDEST)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
GO
ALTER TABLE SEST_LOJA
	ADD CONSTRAINT  FK_SEST_EST FOREIGN KEY (IDLOJA,IDEST) REFERENCES SESTOQUE(IDLOJA,IDEST)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
go
ALTER TABLE SESTPROD
	ADD CONSTRAINT  FK_SESTPROD_PRODUTO FOREIGN KEY (IDLOJA,IDPROD) REFERENCES SPRODUTO(IDLOJA,IDPROD)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
go
/*******************************************************/
/*******************************************************/
/**/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[SMOVEST]') AND name = N'PK_SMOVEST_1') ALTER TABLE [dbo].[SMOVEST] DROP CONSTRAINT [PK_SMOVEST_1]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[SMOVEST]') AND name = N'PK_SMOVEST') ALTER TABLE [dbo].[SMOVEST] DROP CONSTRAINT [PK_SMOVEST]
GO

EXECUTE sp_rename N'dbo.SMOVEST', N'SMOVEST1', 'OBJECT'  
GO 
/**/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SMOVEST]
(	[IDLOJA] [int] NOT NULL,
	[IDMOV]  int NOT NULL ,
	[IDEST]  int  NULL ,
	[IDPROD] [decimal](10, 0) NOT NULL,		
	[DTMOV]  datetime  NULL ,
	[QTDITEM]  decimal(9,2)  NULL ,
	[UNIDCONTROLE]  varchar(5)  NULL ,
	[TPDOC]  char(2)  NULL ,
	[NUMDOC]  varchar(20)  NULL ,
	[IDFOR]  int  NULL ,
	[ITEMDOC]  int  NULL ,
	[FAVORECIDO]  varchar(50)  NULL ,
	[TPLAN]  char(1)  NULL ,
	[TPTRANSA]  char(1)  NULL ,
	[IDTRANSF] integer  NULL ,
	[SALDO]  decimal(9,2)  NULL ,	
	[IDVENDA] INTEGER NULL,
	[OBS] Varchar(80) NULL,	
	[FLGDELETE] int NULL ,
	[DTCADASTRO]  datetime  NULL ,
	[CODSIT]  char(1) NULL ,
	[ALTERSTAMP]  integer  NULL ,
	[TIMESTAMP]  datetime  NULL 
)
go
ALTER TABLE SMOVEST	ADD CONSTRAINT  PK_SMOVEST PRIMARY KEY   NONCLUSTERED (IDLOJA ASC, IDMOV  ASC)
go
exec sp_bindefault DF_0, 'SMOVEST.FLGDELETE'
go
exec sp_bindefault DF_1, 'SMOVEST.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'SMOVEST.TIMESTAMP'
go
SET ANSI_PADDING OFF
GO

INSERT INTO dbo.SMOVEST (
[IDLOJA],[IDMOV],[IDEST],[IDPROD],[DTMOV],[QTDITEM],[UNIDCONTROLE],[TPDOC],[NUMDOC],[IDFOR],[ITEMDOC],[ALTERSTAMP],[TIMESTAMP],[FLGDELETE],[SALDO],[TPLAN],[TPTRANSA],[IDTRANSF],[IDVENDA],[OBS],[DTCADASTRO],[CODSIT],[FAVORECIDO]
) 
SELECT 
[IDLOJA],[IDMOV],[IDEST],[IDPROD],[DTMOV],[QTDITEM],[UNIDCONTROLE],[TPDOC],[NUMDOC],[IDFOR],[ITEMDOC],[ALTERSTAMP],[TIMESTAMP],[FLGDELETE],[SALDO],[TPLAN],[TPTRANSA],[IDTRANSF],[IDVENDA],[OBS],[DTCADASTRO],[CODSIT],[FAVORECIDO]
FROM SMOVEST1
GO 

DROP TABLE SMOVEST1
GO
/*******************************************************/
/*******************************************************/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_AV_OATENDIMENTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[OATENDIMENTO_VENDA]')) ALTER TABLE [dbo].[OATENDIMENTO_VENDA] DROP CONSTRAINT [FK_AV_OATENDIMENTO]
GO
IF  EXISTS (SELECT * FROM sys.check_constraints WHERE object_id = OBJECT_ID(N'[dbo].[CK_IDEVENTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[OATENDIMENTO]')) ALTER TABLE [dbo].[OATENDIMENTO] DROP CONSTRAINT [CK_IDEVENTO]
GO
IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_OATENDIMENTO_SITATEND]') AND type = 'D') BEGIN ALTER TABLE [dbo].[OATENDIMENTO] DROP CONSTRAINT [DF_OATENDIMENTO_SITATEND] END
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_137]') AND parent_object_id = OBJECT_ID(N'[dbo].[OATENDIMENTO]')) ALTER TABLE [dbo].[OATENDIMENTO] DROP CONSTRAINT [R_137]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_164]') AND parent_object_id = OBJECT_ID(N'[dbo].[OATENDIMENTO]')) ALTER TABLE [dbo].[OATENDIMENTO] DROP CONSTRAINT [R_164]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_166]') AND parent_object_id = OBJECT_ID(N'[dbo].[OSESSAO]')) ALTER TABLE [dbo].[OSESSAO] DROP CONSTRAINT [R_166]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_OATENDIMENTO_PRODUTO_OATENDIMENTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[OATENDIMENTO_PRODUTO]')) ALTER TABLE [dbo].[OATENDIMENTO_PRODUTO] DROP CONSTRAINT [FK_OATENDIMENTO_PRODUTO_OATENDIMENTO]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_179]') AND parent_object_id = OBJECT_ID(N'[dbo].[OCLIENTEFOTOS]')) ALTER TABLE [dbo].[OCLIENTEFOTOS] DROP CONSTRAINT [R_179]
GO
/**/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OATENDIMENTO]') AND name = N'PK_OATENDIMENTO') ALTER TABLE [dbo].[OATENDIMENTO] DROP CONSTRAINT [PK_OATENDIMENTO]
GO

EXECUTE sp_rename N'dbo.OATENDIMENTO', N'OATENDIMENTO1', 'OBJECT'  
GO 
/**/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OATENDIMENTO](
	[IDLOJA] [int] NOT NULL,
	[IDATENDIMENTO] [int] NOT NULL,	
	[IDMAQUINA] [int] NULL,
	[IDSALA] [int] NULL,
	[IDMANIPULO] [int] NULL,
	[IDEVENTO] [int] NULL,
	[IDCLIENTE] [int] NULL,
	[IDFUNCIONARIO] [int] NULL,
	[OBS] [ntext] NULL,
	[DTATEND] [datetime] NOT NULL,
	[HHINI] [datetime] NULL,
	[HHFIM] [datetime] NULL,
	[SITATEND] [char](2) NULL,
	[ALTERSTAMP] [int] NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
 CONSTRAINT [PK_OATENDIMENTO] PRIMARY KEY NONCLUSTERED 
(	[IDLOJA] ASC,
	[IDATENDIMENTO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
exec sp_bindefault DF_0, 'OATENDIMENTO.SITATEND'
go
exec sp_bindefault DF_1, 'OATENDIMENTO.IDMANIPULO'
go
exec sp_bindefault DF_1, 'OATENDIMENTO.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OATENDIMENTO.TIMESTAMP'
go
ALTER TABLE [dbo].[OATENDIMENTO]  WITH CHECK ADD  CONSTRAINT [CK_IDEVENTO] CHECK  (([IDEVENTO]>(0)))
GO
ALTER TABLE [dbo].[OATENDIMENTO] CHECK CONSTRAINT [CK_IDEVENTO]
GO
SET ANSI_PADDING OFF
GO

INSERT INTO dbo.OATENDIMENTO (
[IDATENDIMENTO],[IDLOJA],[IDMAQUINA],[IDSALA],[IDEVENTO],[IDCLIENTE],[IDFUNCIONARIO],[OBS],[DTATEND],[HHINI],[HHFIM],[SITATEND],[ALTERSTAMP],[TIMESTAMP],[IDMANIPULO]
) 
SELECT 
[IDATENDIMENTO],[IDLOJA],[IDMAQUINA],[IDSALA],[IDEVENTO],[IDCLIENTE],[IDFUNCIONARIO],[OBS],[DTATEND],[HHINI],[HHFIM],[SITATEND],[ALTERSTAMP],[TIMESTAMP],[IDMANIPULO]
FROM OATENDIMENTO1
GO 
ALTER TABLE [dbo].[OATENDIMENTO]  WITH NOCHECK ADD  CONSTRAINT [R_164] FOREIGN KEY([IDLOJA], [IDCLIENTE]) REFERENCES [dbo].[OCLIENTE] ([IDLOJA], [IDCLIENTE])
GO
ALTER TABLE [dbo].[OATENDIMENTO] NOCHECK CONSTRAINT [R_164]
GO
DELETE OSESSAO WHERE IDATENDIMENTO IN (SELECT IDATENDIMENTO FROM OSESSAO S WHERE S.IDATENDIMENTO NOT IN (SELECT A.IDATENDIMENTO FROM OATENDIMENTO A ))
GO
ALTER TABLE [dbo].[OSESSAO]  WITH CHECK ADD  CONSTRAINT [R_166] FOREIGN KEY([IDLOJA], [IDATENDIMENTO]) REFERENCES [dbo].[OATENDIMENTO] ([IDLOJA], [IDATENDIMENTO])
GO
ALTER TABLE [dbo].[OSESSAO] CHECK CONSTRAINT [R_166]
GO
ALTER TABLE [dbo].[OATENDIMENTO_PRODUTO]  WITH CHECK ADD  CONSTRAINT [FK_OATENDIMENTO_PRODUTO_OATENDIMENTO] FOREIGN KEY([IDLOJA], [IDATENDIMENTO]) REFERENCES [dbo].[OATENDIMENTO] ([IDLOJA], [IDATENDIMENTO])
GO
ALTER TABLE [dbo].[OATENDIMENTO_PRODUTO] CHECK CONSTRAINT [FK_OATENDIMENTO_PRODUTO_OATENDIMENTO]
GO
ALTER TABLE OATENDIMENTO_VENDA ADD CONSTRAINT  FK_AV_OATENDIMENTO FOREIGN KEY (IDLOJA,IDATENDIMENTO)  REFERENCES OATENDIMENTO(IDLOJA,IDATENDIMENTO) ON UPDATE CASCADE
go
ALTER TABLE [dbo].[OATENDIMENTO_VENDA] CHECK CONSTRAINT [FK_AV_OATENDIMENTO]
go
ALTER TABLE OCLIENTEFOTOS ADD CONSTRAINT  R_179 FOREIGN KEY (IDLOJA,IDATENDIMENTO) REFERENCES OATENDIMENTO(IDLOJA,IDATENDIMENTO) ON UPDATE CASCADE
go
DROP TABLE OATENDIMENTO1
GO
/*******************************************************/
/*******************************************************/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_SESTPROD_PRODUTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[SESTPROD]')) ALTER TABLE [dbo].[SESTPROD] DROP CONSTRAINT [FK_SESTPROD_PRODUTO]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_SESTPROD_ESTOQUE]') AND parent_object_id = OBJECT_ID(N'[dbo].[SESTPROD]')) ALTER TABLE [dbo].[SESTPROD] DROP CONSTRAINT [FK_SESTPROD_ESTOQUE]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_SEST_EST]') AND parent_object_id = OBJECT_ID(N'[dbo].[SEST_LOJA]')) ALTER TABLE [dbo].[SEST_LOJA] DROP CONSTRAINT [FK_SEST_EST]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[SESTOQUE]') AND name = N'PK_SESTOQUE') ALTER TABLE [dbo].[SESTOQUE] DROP CONSTRAINT [PK_SESTOQUE]
GO
EXECUTE sp_rename N'dbo.SESTOQUE', N'SESTOQUE1', 'OBJECT'  
GO 
/**/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SESTOQUE]
(	[IDLOJA] int NOT NULL,
	[IDEST] int NOT NULL,
	[DSCEST] varchar(20)  NULL ,
	[DTFECHAMENTO] datetime  NULL ,
	[ATIVO] int  NULL ,
	[ALTERSTAMP] int NULL ,
	[TIMESTAMP] datetime  NULL
)
go
ALTER TABLE SESTOQUE ADD CONSTRAINT PK_SESTOQUE PRIMARY KEY   NONCLUSTERED (IDLOJA ASC, IDEST  ASC)
go
exec sp_bindefault DF_1, 'SESTOQUE.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'SESTOQUE.TIMESTAMP'
go
exec sp_bindefault DF_1, 'SESTOQUE.ATIVO'
go
SET ANSI_PADDING OFF
GO

INSERT INTO dbo.SESTOQUE (
[IDLOJA],[IDEST],[DSCEST],[DTFECHAMENTO],[ATIVO],[ALTERSTAMP]
) 
SELECT 
(SELECT MIN(IDLOJA) FROM OLOJA),[IDEST],[DSCEST],[DTFECHAMENTO],[ATIVO],[ALTERSTAMP]
FROM SESTOQUE1
GO 

DROP TABLE SESTOQUE1
GO
/*******************************************************/
/*******************************************************/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TPCONHEC]') AND parent_object_id = OBJECT_ID(N'[dbo].[OCLIENTE]')) ALTER TABLE [dbo].[OCLIENTE] DROP CONSTRAINT [FK_TPCONHEC]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OTPCONHEC]') AND name = N'XPK_OTPCONHEC') ALTER TABLE [dbo].[OTPCONHEC] DROP CONSTRAINT [XPK_OTPCONHEC]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_LOJA_CLASSE]') AND parent_object_id = OBJECT_ID(N'[dbo].[OCLASSE]')) ALTER TABLE [dbo].[OCLASSE] DROP CONSTRAINT [FK_LOJA_CLASSE]
go
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_233]') AND parent_object_id = OBJECT_ID(N'[dbo].[OCLASSE_CLIENTE]')) ALTER TABLE [dbo].[OCLASSE_CLIENTE] DROP CONSTRAINT [R_233]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_168]') AND parent_object_id = OBJECT_ID(N'[dbo].[OCLIENTEFOTOS]')) ALTER TABLE [dbo].[OCLIENTEFOTOS] DROP CONSTRAINT [R_168]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_234]') AND parent_object_id = OBJECT_ID(N'[dbo].[OCLASSE_CONTATO]')) ALTER TABLE [dbo].[OCLASSE_CONTATO] DROP CONSTRAINT [R_234]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OCLASSE]') AND name = N'PK_OCLASSE') ALTER TABLE [dbo].[OCLASSE] DROP CONSTRAINT [PK_OCLASSE]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CPGTOSVENDA_CCONDPGTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[CPGTOSVENDA]')) ALTER TABLE [dbo].[CPGTOSVENDA] DROP CONSTRAINT [FK_CPGTOSVENDA_CCONDPGTO]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[CCONDPGTO]') AND name = N'PK_CCONDPGTO') ALTER TABLE [dbo].[CCONDPGTO] DROP CONSTRAINT [PK_CCONDPGTO]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CPGTOSVENDA_CFORMAPGTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[CPGTOSVENDA]')) ALTER TABLE [dbo].[CPGTOSVENDA] DROP CONSTRAINT [FK_CPGTOSVENDA_CFORMAPGTO]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[CFORMAPGTO]') AND name = N'PK_CFORMAPGTO') ALTER TABLE [dbo].[CFORMAPGTO] DROP CONSTRAINT [PK_CFORMAPGTO]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_155]') AND parent_object_id = OBJECT_ID(N'[dbo].[OCONTATO]')) ALTER TABLE [dbo].[OCONTATO] DROP CONSTRAINT [R_155]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_235]') AND parent_object_id = OBJECT_ID(N'[dbo].[OCLASSE_CONTATO]')) ALTER TABLE [dbo].[OCLASSE_CONTATO] DROP CONSTRAINT [R_235]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OCONTATO]') AND name = N'PK_OCONTATO') ALTER TABLE [dbo].[OCONTATO] DROP CONSTRAINT [PK_OCONTATO]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_153]') AND parent_object_id = OBJECT_ID(N'[dbo].[OCLIENTE]')) ALTER TABLE [dbo].[OCLIENTE] DROP CONSTRAINT [R_153]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_173]') AND parent_object_id = OBJECT_ID(N'[dbo].[OTRATAMENTOCLI]')) ALTER TABLE [dbo].[OTRATAMENTOCLI] DROP CONSTRAINT [R_173]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_164]') AND parent_object_id = OBJECT_ID(N'[dbo].[OATENDIMENTO]')) ALTER TABLE [dbo].[OATENDIMENTO] DROP CONSTRAINT [R_164]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_154]') AND parent_object_id = OBJECT_ID(N'[dbo].[OPENDENCIACLI]')) ALTER TABLE [dbo].[OPENDENCIACLI] DROP CONSTRAINT [R_154]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_169]') AND parent_object_id = OBJECT_ID(N'[dbo].[OEVENTOAGENDA]')) ALTER TABLE [dbo].[OEVENTOAGENDA] DROP CONSTRAINT [R_169]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_232]') AND parent_object_id = OBJECT_ID(N'[dbo].[OCLASSE_CLIENTE]')) ALTER TABLE [dbo].[OCLASSE_CLIENTE] DROP CONSTRAINT [R_232]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CVENDA_OCLIENTE]') AND parent_object_id = OBJECT_ID(N'[dbo].[CVENDA]')) ALTER TABLE [dbo].[CVENDA] DROP CONSTRAINT [FK_CVENDA_OCLIENTE]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OCLIENTE]') AND name = N'PK_CLIENTE') ALTER TABLE [dbo].[OCLIENTE] DROP CONSTRAINT [PK_CLIENTE]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_209]') AND parent_object_id = OBJECT_ID(N'[dbo].[FCCORRENTE]')) ALTER TABLE [dbo].[FCCORRENTE] DROP CONSTRAINT [R_209]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_210]') AND parent_object_id = OBJECT_ID(N'[dbo].[FLAN]')) ALTER TABLE [dbo].[FLAN] DROP CONSTRAINT [R_210]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_FLAN_FDESPESA]') AND parent_object_id = OBJECT_ID(N'[dbo].[FLAN]')) ALTER TABLE [dbo].[FLAN] DROP CONSTRAINT [FK_FLAN_FDESPESA]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_FLAN_FCCORRENTE]') AND parent_object_id = OBJECT_ID(N'[dbo].[FLAN]')) ALTER TABLE [dbo].[FLAN] DROP CONSTRAINT [FK_FLAN_FCCORRENTE]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[FCCORRENTE]') AND name = N'PK_FCCORRENTE') ALTER TABLE [dbo].[FCCORRENTE] DROP CONSTRAINT [PK_FCCORRENTE]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_210]') AND parent_object_id = OBJECT_ID(N'[dbo].[FLAN]')) ALTER TABLE [dbo].[FLAN] DROP CONSTRAINT [R_210]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CPGTOSVENDA_FLAN]') AND parent_object_id = OBJECT_ID(N'[dbo].[FLAN]')) ALTER TABLE [dbo].[FLAN] DROP CONSTRAINT [FK_CPGTOSVENDA_FLAN]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[FLAN]') AND name = N'PK_FLAN') ALTER TABLE [dbo].[FLAN] DROP CONSTRAINT [PK_FLAN]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_GRP_DESP]') AND parent_object_id = OBJECT_ID(N'[dbo].[FDESPESA]')) ALTER TABLE [dbo].[FDESPESA] DROP CONSTRAINT [R_GRP_DESP]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[FGRUPODESP]') AND name = N'PK_GRPDESP') ALTER TABLE [dbo].[FGRUPODESP] DROP CONSTRAINT [PK_GRPDESP]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[FDESPESA]') AND name = N'PK__DESPESA__35BCFE0A') ALTER TABLE [dbo].[FDESPESA] DROP CONSTRAINT [PK__DESPESA__35BCFE0A]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_160]') AND parent_object_id = OBJECT_ID(N'[dbo].[RFUNCIONARIO]')) ALTER TABLE [dbo].[RFUNCIONARIO] DROP CONSTRAINT [R_160]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CVENDA_RFUNC]') AND parent_object_id = OBJECT_ID(N'[dbo].[CVENDA]')) ALTER TABLE [dbo].[CVENDA] DROP CONSTRAINT [FK_CVENDA_RFUNC]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_159]') AND parent_object_id = OBJECT_ID(N'[dbo].[RBATIDA]')) ALTER TABLE [dbo].[RBATIDA] DROP CONSTRAINT [R_159]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_163]') AND parent_object_id = OBJECT_ID(N'[dbo].[OATENDIMENTO1]')) ALTER TABLE [dbo].[OATENDIMENTO] DROP CONSTRAINT [R_163]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[RFUNCIONARIO]') AND name = N'PK_FUNCIONARIO') ALTER TABLE [dbo].[RFUNCIONARIO] DROP CONSTRAINT [PK_FUNCIONARIO]
GO
EXECUTE sp_rename N'dbo.OTPCONHEC', N'OTPCONHEC1', 'OBJECT'  
GO 
EXECUTE sp_rename N'dbo.OCLASSE', N'OCLASSE1', 'OBJECT'  
GO 
EXECUTE sp_rename N'dbo.CCONDPGTO', N'CCONDPGTO1', 'OBJECT'  
GO 
EXECUTE sp_rename N'dbo.CFORMAPGTO', N'CFORMAPGTO1', 'OBJECT'  
GO 
EXECUTE sp_rename N'dbo.OCONTATO', N'OCONTATO1', 'OBJECT'  
GO 
EXECUTE sp_rename N'dbo.OCLIENTE', N'OCLIENTE1', 'OBJECT'  
GO 
EXECUTE sp_rename N'dbo.FCCORRENTE', N'FCCORRENTE1', 'OBJECT'  
GO 
EXECUTE sp_rename N'dbo.FGRUPODESP', N'FGRUPODESP1', 'OBJECT'  
GO 
EXECUTE sp_rename N'dbo.FDESPESA', N'FDESPESA1', 'OBJECT'  
GO 
EXECUTE sp_rename N'dbo.FLAN', N'FLAN1', 'OBJECT'  
GO 
EXECUTE sp_rename N'dbo.RFUNCIONARIO', N'RFUNCIONARIO1', 'OBJECT'  
GO 
/****************************************/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING OFF
GO 
/****************************************/
CREATE TABLE [dbo].[OTPCONHEC]
(	IDLOJA int  NOT NULL ,
	IDTPCONHEC  int  NOT NULL ,
	NMCONHEC  varchar(25)  NULL ,
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NULL 
)
go
ALTER TABLE OTPCONHEC ADD CONSTRAINT  PK_OTPCONHEC PRIMARY KEY   NONCLUSTERED (IDLOJA ASC, IDTPCONHEC  ASC)
go
exec sp_bindefault DF_1, 'OTPCONHEC.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OTPCONHEC.TIMESTAMP'
go
CREATE TABLE [dbo].[OCLASSE]
(	IDLOJA int NOT NULL,
	IDCLASSE  int  NOT NULL,
	DSCCLASSE varchar(20)  NOT NULL ,
	IDPAI  int  NULL ,
	ATIVO  int  NOT NULL ,
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NULL 
)
go
ALTER TABLE OCLASSE ADD CONSTRAINT  PK_OCLASSE PRIMARY KEY   NONCLUSTERED (IDLOJA ASC, IDCLASSE  ASC)
go
exec sp_bindefault DF_0, 'OCLASSE.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OCLASSE.TIMESTAMP'
go
exec sp_bindefault DF_1, 'OCLASSE.ATIVO'
go
CREATE TABLE [dbo].[CCONDPGTO](
	[IDLOJA] [int] NOT NULL,
	[IDCONDPGTO] [int] NOT NULL,
	[CONDPGTO] [varchar](25) NOT NULL,
	[ATIVO] [int] NOT NULL,
	[ALTERSTAMP] [int] NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
 CONSTRAINT [PK_CCONDPGTO] PRIMARY KEY CLUSTERED 
([IDLOJA] ASC, 	[IDCONDPGTO] ASC)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]) ON [PRIMARY]

GO
exec sp_bindefault DF_1, 'CCONDPGTO.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'CCONDPGTO.TIMESTAMP'
go
exec sp_bindefault DF_1, 'CCONDPGTO.ATIVO'
go
CREATE TABLE [dbo].[CFORMAPGTO](
	[IDLOJA] [int] NOT NULL,
	[IDFORMAPGTO] [int] NOT NULL,
	[FORMAPGTO] [varchar](25) NULL,
    [TXSERV] [DECIMAL](4,2)  NULL,
    [TXPARC] [DECIMAL](4,2)  NULL,
	[ATIVO] [int] NOT NULL,	
	[ALTERSTAMP] [int] NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
 CONSTRAINT [PK_CFORMAPGTO] PRIMARY KEY CLUSTERED 
([IDLOJA] ASC,	[IDFORMAPGTO] ASC)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]) ON [PRIMARY]
GO
exec sp_bindefault DF_1, 'CFORMAPGTO.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'CFORMAPGTO.TIMESTAMP'
go
exec sp_bindefault DF_1, 'CFORMAPGTO.ATIVO'
go
CREATE TABLE [dbo].[OCONTATO](
	[IDLOJA] [int] NOT NULL,
	[IDCONTATO] [int] NOT NULL,
	[IDCOLIGADA] [int] NULL,
	[IDLOJA0] [int] NULL,
	[EMPRESA] [varchar](50) NULL,
	[REGISTRO] [varchar](14) NULL,
	[TEL1] [varchar](20) NULL,
	[TEL2] [varchar](20) NULL,
	[FAX] [varchar](20) NULL,
	[EMAIL] [varchar](50) NULL,
	[ENDERECO] [varchar](50) NULL,
	[BAIRRO] [varchar](20) NULL,
	[CIDADE] [varchar](50) NULL,
	[ESTADO] [varchar](50) NULL,
	[CEP] [varchar](15) NULL,
	[CARGO] [varchar](30) NULL,
	[DTCADASTRO] [datetime] NOT NULL,
	[PJ] [int] NOT NULL,
	[PAIS] [varchar](30) NULL,
	[OBS] [ntext] NULL,
	[NOME] [varchar](50) NOT NULL,
	[DTNASC] [datetime] NULL,
	[ATIVO] [integer] NULL,
	[TIMESTAMP] [datetime] NOT NULL,
	[ALTERSTAMP] [int] NOT NULL,
 CONSTRAINT [PK_OCONTATO] PRIMARY KEY CLUSTERED 
([IDLOJA] ASC,	[IDCONTATO] ASC)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
exec sp_bindefault DF_0, 'OCONTATO.PJ'
go
exec sp_bindefault DF_1, 'OCONTATO.ATIVO'
go
exec sp_bindefault DF_Now, 'OCONTATO.DTCADASTRO'
go
exec sp_bindefault DF_1, 'OCONTATO.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OCONTATO.TIMESTAMP'
go
CREATE TABLE [dbo].[OCLIENTE](
	[IDLOJA] [int] NOT NULL,
	[IDCLIENTE] [int] NOT NULL,		
	[IDCOLIGADA] [int] NULL,
	[IDLOJA0] [int] NULL,
	[IDTPCONHEC] [int] NULL,	
	[DSCTPCONHEC] [varchar](20) NULL,
	[NOME] [varchar](50) NOT NULL,	
	[DTNASC] [datetime] NULL,
	[REGISTRO] [varchar](14) NULL,
	[FOTOTIPO] [int] NULL,
	[SEXO] [char](1) NULL,
	[TEL1] [varchar](20) NULL,
	[TEL2] [varchar](20) NULL,
	[FAX] [varchar](20) NULL,
	[EMAIL] [varchar](50) NULL,
	[ENDERECO] [varchar](100) NULL,
	[BAIRRO] [varchar](50) NULL,
	[CIDADE] [varchar](50) NULL,
	[ESTADO] [varchar](50) NULL,
	[PAIS] [varchar](30) NULL,
	[CEP] [varchar](15) NULL,
	[EMPRESA] [varchar](50) NULL,	
	[CARGO] [varchar](30) NULL,		
	[OBS] [ntext] NULL,
	[ATIVO] [int] NULL,
	[ISENTO] [int] NULL,
	[MOTIVOINAT] [ntext] NULL,
	[DTCADASTRO] [datetime] NOT NULL,
	[FLGMARKETING] [int] NOT NULL,
	[FLGAGENDA] [int] NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
	[ALTERSTAMP] [int] NOT NULL,
 CONSTRAINT [PK_CLIENTE] PRIMARY KEY CLUSTERED 
(	[IDLOJA] ASC,	[IDCLIENTE] ASC)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
exec sp_bindefault DF_1, 'OCLIENTE.ATIVO'
go
exec sp_bindefault DF_F, 'OCLIENTE.SEXO'
go
exec sp_bindefault DF_Now, 'OCLIENTE.DTCADASTRO'
go
exec sp_bindefault DF_1, 'OCLIENTE.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OCLIENTE.TIMESTAMP'
go
exec sp_bindefault DF_0, 'OCLIENTE.FLGMARKETING'
go
exec sp_bindefault DF_0, 'OCLIENTE.FLGAGENDA'
go


CREATE TABLE [dbo].[FCCORRENTE](
	[IDLOJA] [int] NOT NULL,
	[IDCONTA] [int] NOT NULL,	
	[DSCCONTA] [varchar](30) NULL,
	[NUMBANCO] [varchar](4) NULL,
	[NUMCONTA] [varchar](20) NULL,
	[DVCONTA] [char](1) NULL,
	[NUMAGENCIA] [varchar](10) NULL,
	[TPCONTA] [char](1) NULL,
	[EVENDA] [int] NULL,
	[DTFECHAMENTO]  datetime  NULL ,
	[SLDFECHAMENTO]  decimal(9,2)  NULL ,
    [ATIVO] [int] NOT NULL,
	[ALTERSTAMP] [int] NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
 CONSTRAINT [PK_FCCORRENTE] PRIMARY KEY CLUSTERED 
([IDLOJA] ASC,	[IDCONTA] ASC)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
exec sp_bindefault DF_1, 'FCCORRENTE.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'FCCORRENTE.TIMESTAMP'
go
exec sp_bindefault DF_0, 'FCCORRENTE.EVENDA'
go
exec sp_bindefault DF_1, 'FCCORRENTE.ATIVO'
go
CREATE TABLE [dbo].[FGRUPODESP]
(	IDLOJA INT NOT NULL,
    IDGRPDESP  int NOT NULL,
	DSCGRUPO  varchar(50)  NULL,
	IDPAI  int  NULL,
	ALTERSTAMP  int  NULL ,
	TIMESTAMP  datetime  NULL)
go
ALTER TABLE FGRUPODESP ADD CONSTRAINT PK_GRPDESP PRIMARY KEY   NONCLUSTERED (IDLOJA ASC,IDGRPDESP  ASC)
go
exec sp_bindefault DF_1, 'FGRUPODESP.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'FGRUPODESP.TIMESTAMP'
go
CREATE TABLE [dbo].[FDESPESA](
	[IDLOJA] [int] NOT NULL,
	[IDDESP] [int] NOT NULL,
	[DSCDESP] [varchar](40) NOT NULL,
	[CODDESP] [varchar](10) NULL,
	[IDPAI] [int] NULL,
	[IDGRPDESP] [int] NULL,
	[ATIVO] [int] NULL,
	[OCULTO] [int] NULL,
	[TPDESP] [int] NULL,
	[ALTERSTAMP] [int] NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
 CONSTRAINT [PK_DESPESA] PRIMARY KEY CLUSTERED 
([IDLOJA] ASC, [IDDESP] ASC)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
exec sp_bindefault DF_1, 'FDESPESA.ATIVO'
go
exec sp_bindefault DF_0, 'FDESPESA.OCULTO'
go
exec sp_bindefault DF_2, 'FDESPESA.TPDESP'
go
exec sp_bindefault DF_1, 'FDESPESA.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'FDESPESA.TIMESTAMP'
go
CREATE TABLE [dbo].[FLAN](
	[IDLOJA] [int] NOT NULL,
	[IDCONTA] [int] NOT NULL,	
	[IDLAN] [int] NOT NULL,
	[IDVENDA] [int] NULL,
	[IDDESP] [int] NOT NULL,
	[IDSUBDESP] [int] NOT NULL,
	[IDPGTO] [int] NULL,
	[NDOC] [varchar](20) NULL,
	[VALOR] [decimal](9, 2) NULL,	
	[HISTORICO] [varchar](80) NULL,
	[NPARCELA] [int] NULL,
	[TPARCELA] [int] NULL,
	[IDFAVORECIDO] [int] NULL,
	[FAVORECIDO] [varchar](50) NULL,
	[TPFAVORECIDO] [char](1) NULL,
	[DTCADASTRO] [datetime] NULL,
	[DTEMISSAO] [datetime] NULL,
	[DTVENCIMENTO] [datetime] NULL,
	[DTBAIXA] [datetime] NULL,
	[DTCONTAB] [datetime] NULL,
	[TPLAN] [char](1) NULL,
	[TPTRANSA] [char](1) NULL,
	[IDTRANSF] [int] NULL,
	[CODSIT] [char](1) NULL,
	[IDPAI]  int  NULL ,
	[FLGDELETE]  int  NULL ,
    [FLGEXPORT]  int  NULL ,
	[OBS]  [varchar](255)  NULL ,
	[SALDO]  decimal(9,2)  NULL ,
	[TPDOC]  char(2)  NULL ,
	[ALTERSTAMP] [int] NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
 CONSTRAINT [PK_FLAN] PRIMARY KEY CLUSTERED 
([IDLOJA] ASC,	[IDCONTA] ASC,	[IDLAN] ASC)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]) ON [PRIMARY]
GO
exec sp_bindefault DF_0, 'FLAN.FLGDELETE'
go
exec sp_bindefault DF_0, 'FLAN.FLGEXPORT'
go
exec sp_bindefault DF_Now, 'FLAN.DTCADASTRO'
go
exec sp_bindefault DF_1, 'FLAN.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'FLAN.TIMESTAMP'
go
CREATE TABLE [dbo].[RFUNCIONARIO](
	[IDLOJA] [int] NOT NULL,
	[IDFUNCIONARIO] [int] NOT NULL,	
	[IDCOLIGADA] [int] NULL,
	[IDLOJA0] [int] NULL,
	[IDFINGER] [int] NULL,
	[CHAPA] [char](6) NULL,
	[NOME] [varchar](50) NULL,
	[DTADMISSAO] [datetime] NULL,
	[DTDEMISSAO] [datetime] NULL,
	[FLGCERTIFICADO] [int] NULL,
	[SITFUNC] [char](1) NULL,
	[COMPROD] [int] NULL,
	[VLCOMPROD] [decimal](9, 2) NULL,	
	[TPCOMPROD] [int] NULL,
	[COMSERV] [int] NULL,
	[VLCOMSERV] [decimal](9, 2) NULL,	
	[TPCOMSERV] [int] NULL,
	[OBS] [varchar](80) NULL,
	[TELEFONE] [varchar](20) NULL,
	[CELULAR] [varchar](20) NULL,
	[EMAIL] [varchar](80) NULL,
	[ENDERECO] [varchar](100) NULL,
	[BAIRRO] [varchar](50) NULL,
	[CIDADE] [varchar](50) NULL,
	[ESTADO] [varchar](2) NULL,
	[CEP] [varchar](15) NULL,
	[PAIS] [varchar](30) NULL,
	[DTNASC] [datetime] NULL,
	[SALARIO] [decimal](9,2) NULL,
	[SENHA] [varchar](100) NULL,
	[DTCADASTRO] [datetime] NULL,
	[ALTERSTAMP] [int] NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
 CONSTRAINT [PK_FUNCIONARIO] PRIMARY KEY NONCLUSTERED 
(	[IDLOJA] ASC, [IDFUNCIONARIO] ASC)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]) ON [PRIMARY]
GO
exec sp_bindefault DF_0, 'RFUNCIONARIO.COMPROD'
go
exec sp_bindefault DF_0, 'RFUNCIONARIO.TPCOMPROD'
go
exec sp_bindefault DF_0, 'RFUNCIONARIO.COMSERV'
go
exec sp_bindefault DF_0, 'RFUNCIONARIO.TPCOMSERV'
go
exec sp_bindefault DF_1, 'RFUNCIONARIO.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'RFUNCIONARIO.TIMESTAMP'
go
/****************************************/
SET ANSI_PADDING OFF
GO
/****************************************/
INSERT INTO dbo.OTPCONHEC (IDLOJA,IDTPCONHEC,NMCONHEC,ALTERSTAMP,TIMESTAMP) SELECT 
 (SELECT MIN(IDLOJA) FROM OLOJA),IDTPCONHEC,NMCONHEC,ALTERSTAMP,TIMESTAMP
FROM OTPCONHEC1
GO 
INSERT INTO dbo.OCLASSE (IDLOJA,IDCLASSE,DSCCLASSE,IDPAI,ATIVO,ALTERSTAMP,TIMESTAMP) SELECT 
 (SELECT MIN(IDLOJA) FROM OLOJA),IDCLASSE,DSCCLASSE,IDPAI,ATIVO,ALTERSTAMP,TIMESTAMP
FROM OCLASSE1
GO 
INSERT INTO dbo.CCONDPGTO (IDLOJA,IDCONDPGTO,CONDPGTO,ATIVO,ALTERSTAMP,TIMESTAMP) SELECT 
 (SELECT MIN(IDLOJA) FROM OLOJA),IDCONDPGTO,CONDPGTO,ATIVO,ALTERSTAMP,TIMESTAMP
FROM CCONDPGTO1
GO 
INSERT INTO dbo.CFORMAPGTO (IDLOJA,IDFORMAPGTO,FORMAPGTO,TXSERV,TXPARC,ATIVO,ALTERSTAMP,TIMESTAMP) SELECT 
 (SELECT MIN(IDLOJA) FROM OLOJA),IDFORMAPGTO,FORMAPGTO,TXSERV,TXPARC,ATIVO,ALTERSTAMP,TIMESTAMP
FROM CFORMAPGTO1
GO 
INSERT INTO dbo.OCONTATO (IDLOJA,IDCONTATO,IDCOLIGADA,IDLOJA0,EMPRESA,REGISTRO,TEL1,TEL2,FAX,EMAIL,ENDERECO,BAIRRO,CIDADE,ESTADO,CEP,CARGO,DTCADASTRO,PJ,PAIS,OBS,NOME,DTNASC,ATIVO,TIMESTAMP,ALTERSTAMP) SELECT 
 (SELECT MIN(IDLOJA) FROM OLOJA),IDCONTATO,(SELECT MIN(IDCOLIGADA) FROM OLOJA),IDLOJA0,EMPRESA,REGISTRO,TEL1,TEL2,FAX,EMAIL,ENDERECO,BAIRRO,CIDADE,ESTADO,CEP,CARGO,DTCADASTRO,PJ,PAIS,OBS,NOME,DTNASC,ATIVO,TIMESTAMP,ALTERSTAMP
FROM OCONTATO1
GO 
INSERT INTO dbo.OCLIENTE (IDLOJA,IDCLIENTE,IDCOLIGADA,IDLOJA0,IDTPCONHEC,DSCTPCONHEC,NOME,DTNASC,REGISTRO,FOTOTIPO,SEXO,TEL1,TEL2,FAX,EMAIL,ENDERECO,BAIRRO,CIDADE,ESTADO,PAIS,CEP,EMPRESA,CARGO,OBS,ATIVO,ISENTO,MOTIVOINAT,DTCADASTRO,FLGMARKETING,FLGAGENDA,TIMESTAMP,ALTERSTAMP) SELECT 
 (SELECT MIN(IDLOJA) FROM OLOJA),IDCLIENTE,(SELECT Min(IDCOLIGADA) FROM OLOJA),IDLOJA0,IDTPCONHEC,DSCTPCONHEC,NOME,DTNASC,REGISTRO,FOTOTIPO,SEXO,TEL1,TEL2,FAX,EMAIL,ENDERECO,BAIRRO,CIDADE,ESTADO,PAIS,CEP,EMPRESA,CARGO,OBS,ATIVO,ISENTO,MOTIVOINAT,DTCADASTRO,ISNULL(FLGMARKETING,0),ISNULL(FLGAGENDA,0),TIMESTAMP,ALTERSTAMP
FROM OCLIENTE1
GO 
INSERT INTO dbo.FCCORRENTE (IDLOJA,IDCONTA,DSCCONTA,NUMBANCO,NUMCONTA,DVCONTA,NUMAGENCIA,TPCONTA,EVENDA,DTFECHAMENTO,SLDFECHAMENTO,ATIVO,ALTERSTAMP,TIMESTAMP) SELECT 
 (SELECT MIN(IDLOJA) FROM OLOJA),IDCONTA,DSCCONTA,NUMBANCO,NUMCONTA,DVCONTA,NUMAGENCIA,TPCONTA,EVENDA,DTFECHAMENTO,SLDFECHAMENTO,ISNULL(ATIVO,1),ALTERSTAMP,TIMESTAMP
FROM FCCORRENTE1
GO 
INSERT INTO dbo.FGRUPODESP (IDLOJA,IDGRPDESP,DSCGRUPO,IDPAI,ALTERSTAMP,TIMESTAMP) SELECT 
 (SELECT MIN(IDLOJA) FROM OLOJA),IDGRPDESP,DSCGRUPO,IDPAI,ALTERSTAMP,TIMESTAMP
FROM FGRUPODESP1
GO 
INSERT INTO dbo.FDESPESA (IDLOJA,IDDESP,DSCDESP,CODDESP,IDPAI,IDGRPDESP,ATIVO,OCULTO,TPDESP,ALTERSTAMP,TIMESTAMP) SELECT 
 (SELECT MIN(IDLOJA) FROM OLOJA),IDDESP,DSCDESP,CODDESP,IDPAI,IDGRPDESP,ATIVO,OCULTO,TPDESP,ALTERSTAMP,TIMESTAMP
FROM FDESPESA1
GO 
IF  NOT EXISTS (SELECT O.NAME [TABELA], C.NAME [COLUNA], C.COLORDER FROM SYSCOLUMNS C JOIN SYSOBJECTS O ON C.ID=O.ID WHERE O.NAME IN ('FLAN1') AND C.NAME = 'OBS') ALTER TABLE FLAN1 ADD OBS  varchar(255) NULL
GO
INSERT INTO dbo.FLAN (IDLOJA,IDCONTA,IDLAN,IDVENDA,IDDESP,IDSUBDESP,IDPGTO,NDOC,VALOR,HISTORICO,NPARCELA,TPARCELA,IDFAVORECIDO,FAVORECIDO,TPFAVORECIDO,DTCADASTRO,DTEMISSAO,DTVENCIMENTO,DTBAIXA,DTCONTAB,TPLAN,TPTRANSA,IDTRANSF,CODSIT,IDPAI,FLGDELETE,FLGEXPORT,OBS,SALDO,TPDOC,ALTERSTAMP,TIMESTAMP) SELECT 
 (SELECT MIN(IDLOJA) FROM OLOJA),IDCONTA,IDLAN,IDVENDA,ISNULL(IDDESP,0),ISNULL(IDSUBDESP,0),IDPGTO,NDOC,VALOR,HISTORICO,NPARCELA,TPARCELA,IDFAVORECIDO,FAVORECIDO,TPFAVORECIDO,DTCADASTRO,DTEMISSAO,DTVENCIMENTO,DTBAIXA,DTCONTAB,TPLAN,TPTRANSA,IDTRANSF,CODSIT,IDPAI,FLGDELETE,FLGEXPORT,OBS,SALDO,TPDOC,ALTERSTAMP,TIMESTAMP
FROM FLAN1
GO 
INSERT INTO dbo.RFUNCIONARIO (IDLOJA,IDFUNCIONARIO,IDCOLIGADA,IDLOJA0,IDFINGER,CHAPA,NOME,DTADMISSAO,DTDEMISSAO,FLGCERTIFICADO,SITFUNC,COMPROD,VLCOMPROD,TPCOMPROD,COMSERV,VLCOMSERV,TPCOMSERV,OBS,TELEFONE,CELULAR,EMAIL,ENDERECO,BAIRRO,CIDADE,ESTADO,CEP,PAIS,DTNASC,SALARIO,SENHA,DTCADASTRO,ALTERSTAMP,TIMESTAMP) SELECT 
 (SELECT MIN(IDLOJA) FROM OLOJA),IDFUNCIONARIO,(SELECT MIN(IDCOLIGADA) FROM OLOJA),IDLOJA0,IDFINGER,CHAPA,NOME,DTADMISSAO,DTDEMISSAO,FLGCERTIFICADO,SITFUNC,COMPROD,VLCOMPROD,TPCOMPROD,COMSERV,VLCOMSERV,TPCOMSERV,OBS,TELEFONE,CELULAR,EMAIL,ENDERECO,BAIRRO,CIDADE,ESTADO,CEP,PAIS,DTNASC,SALARIO,SENHA,DTCADASTRO,ALTERSTAMP,TIMESTAMP
FROM RFUNCIONARIO1
GO 
/****************************************/
ALTER TABLE OCLASSE	ADD CONSTRAINT  FK_LOJA_CLASSE FOREIGN KEY (IDLOJA) REFERENCES OLOJA(IDLOJA)
go
ALTER TABLE OCLASSE_CLIENTE	ADD CONSTRAINT  R_233 FOREIGN KEY (IDLOJA, IDCLASSE) REFERENCES OCLASSE(IDLOJA, IDCLASSE)
go
ALTER TABLE OCLIENTEFOTOS	ADD CONSTRAINT  R_168 FOREIGN KEY (IDLOJA,IDCLIENTE) REFERENCES OCLIENTE(IDLOJA,IDCLIENTE) ON UPDATE CASCADE
go
ALTER TABLE OCLASSE_CONTATO	ADD CONSTRAINT  R_234 FOREIGN KEY (IDLOJA, IDCLASSE) REFERENCES OCLASSE(IDLOJA, IDCLASSE)
go
ALTER TABLE [dbo].[OCLIENTE]  WITH CHECK ADD  CONSTRAINT [R_153] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[OCLIENTE] CHECK CONSTRAINT [R_153]
GO
ALTER TABLE [dbo].[OCONTATO]  WITH CHECK ADD  CONSTRAINT [R_155] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[OCONTATO] CHECK CONSTRAINT [R_155]
GO
ALTER TABLE OCLIENTE ADD CONSTRAINT  FK_TPCONHEC FOREIGN KEY (IDLOJA, IDTPCONHEC) REFERENCES OTPCONHEC(IDLOJA, IDTPCONHEC)
go
ALTER TABLE [dbo].[FCCORRENTE]  WITH CHECK ADD  CONSTRAINT [R_209] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[FCCORRENTE] CHECK CONSTRAINT [R_209]
GO
ALTER TABLE [dbo].[FLAN]  WITH CHECK ADD  CONSTRAINT [R_210] FOREIGN KEY([IDLOJA], [IDCONTA]) REFERENCES [dbo].[FCCORRENTE] ([IDLOJA], [IDCONTA])
GO
ALTER TABLE [dbo].[FLAN]  WITH NOCHECK ADD  CONSTRAINT [FK_FLAN_FDESPESA] FOREIGN KEY([IDLOJA], [IDDESP]) REFERENCES [dbo].[FDESPESA] ([IDLOJA],[IDDESP]) ON UPDATE CASCADE
go
ALTER TABLE [dbo].[FLAN]  WITH NOCHECK ADD  CONSTRAINT [FK_CPGTOSVENDA_FLAN] FOREIGN KEY([IDLOJA], [IDVENDA], [IDPGTO]) REFERENCES [dbo].[CPGTOSVENDA] ([IDLOJA], [IDVENDA], [IDPGTO]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[FLAN] NOCHECK CONSTRAINT [FK_CPGTOSVENDA_FLAN]
GO
ALTER TABLE FDESPESA ADD CONSTRAINT  R_GRP_DESP FOREIGN KEY (IDLOJA, IDGRPDESP) REFERENCES FGRUPODESP(IDLOJA, IDGRPDESP) ON UPDATE NO ACTION
go
ALTER TABLE [dbo].[RFUNCIONARIO]  WITH CHECK ADD  CONSTRAINT [R_160] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[RFUNCIONARIO] CHECK CONSTRAINT [R_160]
GO
ALTER TABLE [dbo].[CPGTOSVENDA]  WITH CHECK ADD  CONSTRAINT [FK_CPGTOSVENDA_CCONDPGTO] FOREIGN KEY([IDLOJA],[IDCONDPGTO]) REFERENCES [dbo].[CCONDPGTO] ([IDLOJA],[IDCONDPGTO]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CPGTOSVENDA]  WITH CHECK ADD  CONSTRAINT [FK_CPGTOSVENDA_CFORMAPGTO] FOREIGN KEY([IDLOJA],[IDFORMAPGTO]) REFERENCES [dbo].[CFORMAPGTO] ([IDLOJA], [IDFORMAPGTO]) ON UPDATE CASCADE
GO
/****/
ALTER TABLE CBANDCTX ADD CONSTRAINT  R_181 FOREIGN KEY (IDLOJA,IDFORMAPGTO) REFERENCES CFORMAPGTO(IDLOJA,IDFORMAPGTO) ON UPDATE CASCADE
go
/****/
ALTER TABLE OCLASSE_CONTATO ADD CONSTRAINT  R_235 FOREIGN KEY (IDLOJA,IDCONTATO) REFERENCES OCONTATO(IDLOJA,IDCONTATO)
GO
ALTER TABLE [dbo].[OTRATAMENTOCLI]  WITH CHECK ADD  CONSTRAINT [R_173] FOREIGN KEY([IDLOJA], [IDCLIENTE]) REFERENCES [dbo].[OCLIENTE] ([IDLOJA], [IDCLIENTE])
GO
ALTER TABLE [dbo].[OTRATAMENTOCLI] CHECK CONSTRAINT [R_173]
GO
ALTER TABLE [dbo].[OATENDIMENTO]  WITH NOCHECK ADD  CONSTRAINT [R_164] FOREIGN KEY([IDLOJA], [IDCLIENTE]) REFERENCES [dbo].[OCLIENTE] ([IDLOJA], [IDCLIENTE])
GO
ALTER TABLE [dbo].[OATENDIMENTO] NOCHECK CONSTRAINT [R_164]
GO
ALTER TABLE [dbo].[OPENDENCIACLI]  WITH CHECK ADD  CONSTRAINT [R_154] FOREIGN KEY([IDLOJA], [IDCLIENTE]) REFERENCES [dbo].[OCLIENTE] ([IDLOJA], [IDCLIENTE])
GO
ALTER TABLE [dbo].[OPENDENCIACLI] CHECK CONSTRAINT [R_154]
GO
ALTER TABLE [dbo].[OEVENTOAGENDA]  WITH NOCHECK ADD  CONSTRAINT [R_169] FOREIGN KEY([IDLOJA], [IDCLIENTE]) REFERENCES [dbo].[OCLIENTE] ([IDLOJA], [IDCLIENTE])
GO
ALTER TABLE [dbo].[OEVENTOAGENDA] NOCHECK CONSTRAINT [R_169]
GO
ALTER TABLE OCLASSE_CLIENTE	ADD CONSTRAINT  R_232 FOREIGN KEY (IDLOJA,IDCLIENTE) REFERENCES OCLIENTE(IDLOJA,IDCLIENTE)
go
ALTER TABLE [dbo].[CVENDA]  WITH NOCHECK ADD  CONSTRAINT [FK_CVENDA_OCLIENTE] FOREIGN KEY([IDLOJA], [IDCLIENTE]) REFERENCES [dbo].[OCLIENTE] ([IDLOJA], [IDCLIENTE])
GO
ALTER TABLE [dbo].[CVENDA]  WITH NOCHECK ADD CONSTRAINT [FK_CVENDA_RFUNC] FOREIGN KEY([IDLOJA], [IDFUNCIONARIO]) REFERENCES [dbo].[RFUNCIONARIO] ([IDLOJA], [IDFUNCIONARIO])
GO
ALTER TABLE [dbo].[CVENDA] NOCHECK CONSTRAINT [FK_CVENDA_RFUNC]
GO
ALTER TABLE RBATIDA ADD CONSTRAINT  R_159 FOREIGN KEY (IDLOJA,IDFUNCIONARIO) REFERENCES RFUNCIONARIO(IDLOJA,IDFUNCIONARIO)
go
/****************************************/
DROP TABLE OTPCONHEC1
GO
DROP TABLE OCLASSE1
GO
DROP TABLE CCONDPGTO1
GO
DROP TABLE CFORMAPGTO1
GO
DROP TABLE OCONTATO1
GO
DROP TABLE OCLIENTE1
GO
DROP TABLE FCCORRENTE1
GO
DROP TABLE FGRUPODESP1
GO
DROP TABLE FDESPESA1
GO
DROP TABLE FLAN1
GO
DROP TABLE RFUNCIONARIO1
GO
