
/****************************************************************************
****************************************************************************/
--USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='41', ARQATU='Rev41.sql';
/****************************************************************************
****************************************************************************/

ALTER TABLE CVENDA ADD CODVENDA int NULL
go
UPDATE CVENDA SET CODVENDA=IDVENDA
go
IF  EXISTS (SELECT * FROM syscolumns  WHERE  name='IDITEMV')
ALTER TABLE OSESSAO DROP COLUMN IDITEMV 
GO
ALTER TABLE OMANIPULO ADD IDLOJA int  NULL
go
ALTER TABLE OMANIPULO ADD ATIVO int NULL
go
UPDATE OMANIPULO SET IDLOJA=(SELECT MIN(IDLOJA) FROM OLOJA), ATIVO=1
go
exec sp_bindefault DF_1, 'OMANIPULO.ATIVO'
go
ALTER TABLE OMAQUINA ADD IDLOJA int  NULL
go
UPDATE OMAQUINA SET IDLOJA=(SELECT MIN(IDLOJA) FROM OLOJA)
go
ALTER TABLE OCLASSE ADD IDLOJA int  NULL
go
UPDATE OCLASSE SET IDLOJA=(SELECT MIN(IDLOJA) FROM OLOJA)
go
ALTER TABLE CFORMAPGTO ADD TXPARC decimal(4,2)  NULL
go

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_234]') AND parent_object_id = OBJECT_ID(N'[dbo].[OCLASSE_CONTATO]')) ALTER TABLE [dbo].[OCLASSE_CONTATO] DROP CONSTRAINT [R_234]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_233]') AND parent_object_id = OBJECT_ID(N'[dbo].[OCLASSE_CLIENTE]')) ALTER TABLE [dbo].[OCLASSE_CLIENTE] DROP CONSTRAINT [R_233]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OCLASSE]') AND name = N'PK_OCLASSE') ALTER TABLE [dbo].[OCLASSE] DROP CONSTRAINT [PK_OCLASSE]
GO
EXECUTE sp_rename N'dbo.OCLASSE', N'OCLASSE1', 'OBJECT'  
GO 
CREATE TABLE [dbo].[OCLASSE]
(	IDLOJA int NOT NULL,
	IDCLASSE  int  NOT NULL,
	DSCCLASSE varchar(20)  NOT NULL ,
	IDPAI  int  NULL ,
	ATIVO  int  NOT NULL ,
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NULL 
)
go

INSERT INTO dbo.OCLASSE (IDLOJA, IDCLASSE, DSCCLASSE, IDPAI, ATIVO) SELECT IDLOJA, IDCLASSE, DSCCLASSE, IDPAI, ATIVO FROM OCLASSE1
GO 
ALTER TABLE [dbo].[OCLASSE] ADD  CONSTRAINT [PK_OCLASSE] PRIMARY KEY NONCLUSTERED ([IDLOJA] ASC, [IDCLASSE] ASC) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OCLASSE_CONTATO]  WITH CHECK ADD  CONSTRAINT [R_234] FOREIGN KEY([IDLOJA], [IDCLASSE]) REFERENCES [dbo].[OCLASSE] ([IDLOJA], [IDCLASSE]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO
ALTER TABLE [dbo].[OCLASSE_CONTATO] CHECK CONSTRAINT [R_234]
GO
ALTER TABLE [dbo].[OCLASSE_CLIENTE]  WITH CHECK ADD  CONSTRAINT [R_233] FOREIGN KEY([IDLOJA], [IDCLASSE]) REFERENCES [dbo].[OCLASSE] ([IDLOJA], [IDCLASSE]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO
ALTER TABLE [dbo].[OCLASSE_CLIENTE] CHECK CONSTRAINT [R_233]
GO
ALTER TABLE OCLASSE	ADD CONSTRAINT  FK_LOJA_CLASSE FOREIGN KEY (IDLOJA) REFERENCES OLOJA(IDLOJA) ON DELETE NO ACTION ON UPDATE NO ACTION
go
DROP TABLE OCLASSE1
GO
/*******************************************************************************/
/*******************************************************************************/
DELETE FROM CCUPOM_VENDA
GO
DELETE FROM CCUPOM
GO
DELETE FROM CPROMOCAO
go
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_140]') AND parent_object_id = OBJECT_ID(N'[dbo].[CCUPOM_VENDA]')) ALTER TABLE [dbo].[CCUPOM_VENDA] DROP CONSTRAINT [R_140]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_139]') AND parent_object_id = OBJECT_ID(N'[dbo].[CCUPOM_VENDA]')) ALTER TABLE [dbo].[CCUPOM_VENDA] DROP CONSTRAINT [R_139]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_138]') AND parent_object_id = OBJECT_ID(N'[dbo].[CCUPOM]')) ALTER TABLE [dbo].[CCUPOM] DROP CONSTRAINT [R_138]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[CCUPOM_VENDA]') AND name = N'PK_CCUPOMVENDA') ALTER TABLE [dbo].[CCUPOM_VENDA] DROP CONSTRAINT [PK_CCUPOMVENDA]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[CCUPOM]') AND name = N'PK_CCUPOM') ALTER TABLE [dbo].[CCUPOM] DROP CONSTRAINT [PK_CCUPOM]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[CPROMOCAO]') AND name = N'PK_CPROMOCAO') ALTER TABLE [dbo].[CPROMOCAO] DROP CONSTRAINT [PK_CPROMOCAO]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_140]') AND parent_object_id = OBJECT_ID(N'[dbo].[CCUPOM_VENDA]')) ALTER TABLE [dbo].[CCUPOM_VENDA] DROP CONSTRAINT [R_140]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CCUPOM_VENDA]') AND type in (N'U')) DROP TABLE [dbo].[CCUPOM_VENDA]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CCUPOM]') AND type in (N'U')) DROP TABLE [dbo].[CCUPOM]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CPROMOCAO]') AND type in (N'U')) DROP TABLE [dbo].[CPROMOCAO]
GO
/*******************************************************************************/
/*******************************************************************************/
CREATE TABLE [dbo].[CPROMOCAO]
(	[IDLOJA]    int NOT NULL,	
	[IDPROMO]    int NOT NULL,	
	[DSCPROMO]	 varchar(30) NULL,
	[ATIVO]		 int NULL,
	[VLDESC]	 decimal(9,2) NULL ,
	[DTVENC]  datetime  NULL ,
	[DTEMISSAO]  datetime  NULL ,
	[NPARCELA]  int  NULL ,	
	[PRAZO]  int  NULL,
	[IDPROD]  int  NULL,
	[QTDPROD]  decimal(9,2) NULL,
	[ALTERSTAMP] int NULL,
	[TIMESTAMP]  datetime NULL,		
 CONSTRAINT [PK_CPROMOCAO] PRIMARY KEY CLUSTERED 
([IDLOJA] ASC, [IDPROMO] ASC)
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]) ON [PRIMARY]
GO

exec sp_bindefault DF_1, 'CPROMOCAO.ATIVO'
go
exec sp_bindefault DF_1, 'CPROMOCAO.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'CPROMOCAO.TIMESTAMP'
go

CREATE TABLE [dbo].[CCUPOM]
(	IDLOJA  int NOT NULL,
	IDPROMO  int NOT NULL,
	IDCUPOM  int NOT NULL,    
	CODCUPOM  varchar(20)  NULL ,
	DTEMISSAO  datetime  NULL ,
	DTVENC  datetime  NULL ,
	VLDESC decimal(9,2)  NULL ,
	ATIVO  int  NULL ,
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NULL 
)
go

ALTER TABLE CCUPOM ADD CONSTRAINT  PK_CCUPOM PRIMARY KEY   NONCLUSTERED (IDLOJA ASC, IDPROMO ASC, IDCUPOM  ASC)
go
exec sp_bindefault DF_1, 'CCUPOM.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'CCUPOM.TIMESTAMP'
go

ALTER TABLE CPROMOCAO
	ADD CONSTRAINT  PK_LOJA_PROMOCAO FOREIGN KEY (IDLOJA) REFERENCES OLOJA(IDLOJA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

CREATE TABLE [dbo].[CCUPOM_VENDA]
(	IDLOJA  int  NOT NULL ,
	IDPROMO  int  NOT NULL ,
	IDCUPOM  int  NOT NULL ,
	IDVENDA  int  NOT NULL ,
	QTD  int  NULL ,
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NULL 
)
go


ALTER TABLE CCUPOM_VENDA ADD CONSTRAINT  PK_CCUPOMVENDA PRIMARY KEY   NONCLUSTERED (IDLOJA  ASC,IDVENDA  ASC,IDCUPOM  ASC)
go
exec sp_bindefault DF_1, 'CCUPOM_VENDA.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'CCUPOM_VENDA.TIMESTAMP'
go

ALTER TABLE CCUPOM
	ADD CONSTRAINT  R_138 FOREIGN KEY (IDLOJA, IDPROMO) REFERENCES CPROMOCAO(IDLOJA, IDPROMO)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
go

ALTER TABLE CCUPOM_VENDA
	ADD CONSTRAINT  R_139 FOREIGN KEY (IDLOJA, IDPROMO, IDCUPOM) REFERENCES CCUPOM(IDLOJA, IDPROMO, IDCUPOM)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
go

ALTER TABLE CCUPOM_VENDA
	ADD CONSTRAINT  R_140 FOREIGN KEY (IDLOJA,IDVENDA) REFERENCES CVENDA(IDLOJA,IDVENDA)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
go
/*******************************************************************************/
/*******************************************************************************/

