
/****************************************************************************
****************************************************************************/
--USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='43', ARQATU='Rev43.sql';
/****************************************************************************
****************************************************************************/

IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='RFUNCIONARIO' AND C.NAME='SENHA') ALTER TABLE RFUNCIONARIO ADD SENHA VARCHAR(100)
GO
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='DELETEDROWS' AND C.NAME='TIMESTAMP') ALTER TABLE DELETEDROWS ADD TIMESTAMP datetime
GO
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='DELETEDROWS' AND C.NAME='ALTERSTAMP') ALTER TABLE DELETEDROWS ADD ALTERSTAMP INT
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[CVENDA]') AND name = N'X_CVENDA_ATEND') DROP INDEX [X_CVENDA_ATEND] ON [dbo].[CVENDA] WITH ( ONLINE = OFF )
GO
IF EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='CVENDA' AND C.NAME='IDATENDIMENTO') ALTER TABLE CVENDA DROP COLUMN IDATENDIMENTO
GO
IF EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='FLOTERPS' AND C.NAME='IDLOTE2') ALTER TABLE FLOTERPS DROP COLUMN IDLOTE2
GO
IF (EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='PMETAITEM' AND C.NAME='DTPREV') AND NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='PMETAITEM' AND C.NAME='DTITEM')) EXEC sp_RENAME 'PMETAITEM.DTPREV', 'DTITEM' , 'COLUMN'
GO
IF EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='PMETAITEM' AND C.NAME='DTPREV') AND EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='PMETAITEM' AND C.NAME='DTITEM') ALTER TABLE PMETAITEM DROP COLUMN DTPREV
GO
exec sp_bindefault DF_Now, 'DELETEDROWS.TIMESTAMP'
go
exec sp_bindefault DF_1, 'DELETEDROWS.ALTERSTAMP'
go
IF Not EXISTS (SELECT * FROM sys.COLUMNS C JOIN sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='CVENDA' AND C.NAME='FLGBXMANUAL') Alter Table CVENDA ADD FLGBXMANUAL Int
go
exec sp_bindefault DF_0, 'CVENDA.FLGBXMANUAL'
go
/*******************************************************/
/*******************************************************/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_43]') AND parent_object_id = OBJECT_ID(N'[dbo].[OLOJA]')) ALTER TABLE [dbo].[OLOJA] DROP CONSTRAINT [R_43]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_LOJA]') AND parent_object_id = OBJECT_ID(N'[dbo].[OTAREFAEVT]')) ALTER TABLE [dbo].[OTAREFAEVT] DROP CONSTRAINT [FK_LOJA]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_SEST_LOJA]') AND parent_object_id = OBJECT_ID(N'[dbo].[SEST_LOJA]')) ALTER TABLE [dbo].[SEST_LOJA] DROP CONSTRAINT [FK_SEST_LOJA]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_209]') AND parent_object_id = OBJECT_ID(N'[dbo].[FCCORRENTE]')) ALTER TABLE [dbo].[FCCORRENTE] DROP CONSTRAINT [R_209]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_160]') AND parent_object_id = OBJECT_ID(N'[dbo].[RFUNCIONARIO]')) ALTER TABLE [dbo].[RFUNCIONARIO] DROP CONSTRAINT [R_160]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_OLOJA_DIARIO]') AND parent_object_id = OBJECT_ID(N'[dbo].[ODIARIO]')) ALTER TABLE [dbo].[ODIARIO] DROP CONSTRAINT [R_OLOJA_DIARIO]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_3]') AND parent_object_id = OBJECT_ID(N'[dbo].[OSALA]'))ALTER TABLE [dbo].[OSALA] DROP CONSTRAINT [R_3]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_144]') AND parent_object_id = OBJECT_ID(N'[dbo].[FLOTERPS]')) ALTER TABLE [dbo].[FLOTERPS] DROP CONSTRAINT [R_144]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_155]') AND parent_object_id = OBJECT_ID(N'[dbo].[OCONTATO]')) ALTER TABLE [dbo].[OCONTATO] DROP CONSTRAINT [R_155]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_153]') AND parent_object_id = OBJECT_ID(N'[dbo].[OCLIENTE]')) ALTER TABLE [dbo].[OCLIENTE] DROP CONSTRAINT [R_153]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_182]') AND parent_object_id = OBJECT_ID(N'[dbo].[SPRODUTO]')) ALTER TABLE [dbo].[SPRODUTO] DROP CONSTRAINT [R_182]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_OAGENDA_OLOJA]') AND parent_object_id = OBJECT_ID(N'[dbo].[OAGENDA]')) ALTER TABLE [dbo].[OAGENDA] DROP CONSTRAINT [FK_OAGENDA_OLOJA]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[PK_LOJA_PROMOCAO]') AND parent_object_id = OBJECT_ID(N'[dbo].[CPROMOCAO]')) ALTER TABLE [dbo].[CPROMOCAO] DROP CONSTRAINT [PK_LOJA_PROMOCAO]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_LOJA_PROMOCAO]') AND parent_object_id = OBJECT_ID(N'[dbo].[CPROMOCAO]')) ALTER TABLE [dbo].[CPROMOCAO] DROP CONSTRAINT [FK_LOJA_PROMOCAO]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_OLOJA_FFATURA]') AND parent_object_id = OBJECT_ID(N'[dbo].[FFATURA]'))ALTER TABLE [dbo].[FFATURA] DROP CONSTRAINT [FK_OLOJA_FFATURA]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_LOJA_CLASSE]') AND parent_object_id = OBJECT_ID(N'[dbo].[OCLASSE]')) ALTER TABLE [dbo].[OCLASSE] DROP CONSTRAINT [FK_LOJA_CLASSE]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_AGENDA_SALA]') AND parent_object_id = OBJECT_ID(N'[dbo].[OAGENDA]')) ALTER TABLE [dbo].[OAGENDA] DROP CONSTRAINT [FK_AGENDA_SALA]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_SALA_MAQUINA_SALA]') AND parent_object_id = OBJECT_ID(N'[dbo].[OSALA_MAQUINA]')) ALTER TABLE [dbo].[OSALA_MAQUINA] DROP CONSTRAINT [FK_SALA_MAQUINA_SALA]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OLOJA]') AND name = N'PK_LOJA') ALTER TABLE [dbo].[OLOJA] DROP CONSTRAINT [PK_LOJA]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OSALA]') AND name = N'PK_SALA') ALTER TABLE [dbo].[OSALA] DROP CONSTRAINT [PK_SALA]
GO

EXECUTE sp_rename N'dbo.OSALA', N'OSALA1', 'OBJECT'  
GO 
EXECUTE sp_rename N'dbo.OLOJA', N'OLOJA1', 'OBJECT'  
GO 

SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[OLOJA](
	IDLOJA int NOT NULL,
	IDCOLIGADA int NOT NULL,
	CNPJ varchar(14) NULL,
	NOME varchar(20) NOT NULL,
	ENDERECO varchar(50) NULL,
	BAIRRO varchar(50) NULL,
	CIDADE varchar(20) NULL,
	ESTADO varchar(20) NULL,
	INSCEST varchar(20) NULL,
    INSCMUNIC varchar(20) NULL,
	EMAIL varchar(50) NULL,
	TELEFONE1 varchar(20) NULL,
	TELEFONE2 varchar(20) NULL,
	CEP varchar(20) NULL,
	FAX varchar(20) NULL,
	IDPAIS int NULL,
	NMCONTATO varchar(30) NULL,
	CARGOCONTATO varchar(30) NULL,
	DTOPERACAO datetime NOT NULL,
	DIMENSAO varchar(20) NULL,
    RAZAO varchar(50) NULL,
	NMFANTASIA varchar(50) NULL,
    RZABREV varchar(50) NULL,
    FLGFILIAL int NULL,
    CODSERVMUNIC varchar(20) NULL,
    CODSERVFEDERAL varchar(20) NULL,
    REGESPECIALTRIB int NULL,
    SIMPLES int NULL,
    TRIBUTACAO int NULL,
    INCENTIVOCULT int NULL,
	ALTERSTAMP int NOT NULL,
	TIMESTAMP datetime NOT NULL,
 CONSTRAINT [PK_LOJA] PRIMARY KEY NONCLUSTERED 
([IDLOJA] ASC)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]) ON [PRIMARY]
GO
exec sp_bindefault DF_1, 'OLOJA.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OLOJA.TIMESTAMP'
go
exec sp_bindefault DF_Now, 'OLOJA.DTOPERACAO'
go
EXEC sp_bindefault DF_0,'OLOJA.FLGFILIAL'
GO
EXEC sp_bindefault DF_0,'OLOJA.REGESPECIALTRIB'
GO
EXEC sp_bindefault DF_1,'OLOJA.SIMPLES'
GO
EXEC sp_bindefault DF_1,'OLOJA.TRIBUTACAO'
GO
EXEC sp_bindefault DF_0,'OLOJA.INCENTIVOCULT'
GO
CREATE TABLE [dbo].[OSALA](
	[IDLOJA] [int] NOT NULL,
	[IDSALA] [int] NOT NULL,		
	[CODSALA] [varchar](5) NULL,
	[DIMENSAO] [varchar](20) NULL,
	[DTOPERACAO] [datetime] NULL,
	[ATIVO] [int] NULL,
	[ALTERSTAMP] [int] NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
 CONSTRAINT [PK_SALA] PRIMARY KEY NONCLUSTERED 
([IDLOJA] ASC,[IDSALA] ASC)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]) ON [PRIMARY]
GO
exec sp_bindefault DF_1, 'OSALA.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OSALA.TIMESTAMP'
go
exec sp_bindefault DF_Now, 'OSALA.DTOPERACAO'
go
SET ANSI_PADDING OFF
GO
INSERT INTO dbo.OLOJA (IDLOJA,IDCOLIGADA,CNPJ,NOME,ENDERECO,BAIRRO,CIDADE,ESTADO,INSCEST,INSCMUNIC,EMAIL,TELEFONE1,TELEFONE2,CEP,FAX,IDPAIS,NMCONTATO,CARGOCONTATO,DTOPERACAO,DIMENSAO,RAZAO,NMFANTASIA,RZABREV,FLGFILIAL,CODSERVMUNIC,CODSERVFEDERAL,REGESPECIALTRIB,SIMPLES,TRIBUTACAO,INCENTIVOCULT,ALTERSTAMP,TIMESTAMP) SELECT IDLOJA,IDCOLIGADA,CNPJ,NOME,ENDERECO,BAIRRO,CIDADE,ESTADO,INSCEST,INSCMUNIC,EMAIL,TELEFONE1,TELEFONE2,CEP,FAX,IDPAIS,NMCONTATO,CARGOCONTATO,DTOPERACAO,DIMENSAO,RAZAO,NMFANTASIA,RZABREV,FLGFILIAL,CODSERVMUNIC,CODSERVFEDERAL,REGESPECIALTRIB,SIMPLES,TRIBUTACAO,INCENTIVOCULT,ALTERSTAMP,TIMESTAMP FROM OLOJA1
GO 
INSERT INTO dbo.OSALA (IDLOJA,IDSALA,CODSALA,DIMENSAO,DTOPERACAO,ATIVO,ALTERSTAMP,TIMESTAMP) SELECT IDLOJA,IDSALA,CODSALA,DIMENSAO,DTOPERACAO,ATIVO,ALTERSTAMP,TIMESTAMP FROM OSALA1
GO 
ALTER TABLE [dbo].[OLOJA]  WITH CHECK ADD  CONSTRAINT [R_43] FOREIGN KEY([IDCOLIGADA]) REFERENCES [dbo].[COLIGADA] ([IDCOLIGADA])
GO
ALTER TABLE [dbo].[OLOJA] CHECK CONSTRAINT [R_43]
GO
ALTER TABLE OTAREFAEVT ADD CONSTRAINT  FK_LOJA FOREIGN KEY (IDLOJA) REFERENCES OLOJA(IDLOJA)
go
ALTER TABLE SEST_LOJA ADD CONSTRAINT  FK_SEST_LOJA FOREIGN KEY (IDLOJA) REFERENCES OLOJA(IDLOJA)
go
ALTER TABLE [dbo].[FCCORRENTE]  WITH CHECK ADD  CONSTRAINT [R_209] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[FCCORRENTE] CHECK CONSTRAINT [R_209]
GO
ALTER TABLE [dbo].[RFUNCIONARIO]  WITH CHECK ADD  CONSTRAINT [R_160] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[RFUNCIONARIO] CHECK CONSTRAINT [R_160]
GO
ALTER TABLE ODIARIO	ADD CONSTRAINT  R_OLOJA_DIARIO FOREIGN KEY (IDLOJA) REFERENCES OLOJA(IDLOJA)
go
ALTER TABLE [dbo].[OSALA]  WITH CHECK ADD  CONSTRAINT [R_3] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[OSALA] CHECK CONSTRAINT [R_3]
GO
ALTER TABLE FLOTERPS ADD CONSTRAINT  R_144 FOREIGN KEY (IDLOJA) REFERENCES OLOJA(IDLOJA)
go
ALTER TABLE [dbo].[OCONTATO]  WITH CHECK ADD  CONSTRAINT [R_155] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[OCONTATO] CHECK CONSTRAINT [R_155]
GO
ALTER TABLE [dbo].[OCLIENTE]  WITH CHECK ADD  CONSTRAINT [R_153] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[OCLIENTE] CHECK CONSTRAINT [R_153]
GO
UPDATE SPRODUTO SET IDLOJA =(Select Min(IDLOJA) FROM OLOJA)
GO
ALTER TABLE SPRODUTO ADD CONSTRAINT  R_182 FOREIGN KEY (IDLOJA) REFERENCES OLOJA(IDLOJA)
go
ALTER TABLE [dbo].[OAGENDA]  WITH CHECK ADD  CONSTRAINT [FK_OAGENDA_OLOJA] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[OAGENDA] CHECK CONSTRAINT [FK_OAGENDA_OLOJA]
GO
ALTER TABLE CPROMOCAO ADD CONSTRAINT  FK_LOJA_PROMOCAO FOREIGN KEY (IDLOJA) REFERENCES OLOJA(IDLOJA)
go
ALTER TABLE FFATURA	ADD CONSTRAINT  FK_OLOJA_FFATURA FOREIGN KEY (IDLOJA) REFERENCES OLOJA(IDLOJA)
go
ALTER TABLE OCLASSE	ADD CONSTRAINT  FK_LOJA_CLASSE FOREIGN KEY (IDLOJA) REFERENCES OLOJA(IDLOJA)
go
ALTER TABLE [dbo].[OAGENDA]  WITH CHECK ADD  CONSTRAINT [FK_AGENDA_SALA] FOREIGN KEY([IDLOJA], [IDSALA]) REFERENCES [dbo].[OSALA] ([IDLOJA], [IDSALA]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[OAGENDA] CHECK CONSTRAINT [FK_AGENDA_SALA]
GO
ALTER TABLE [dbo].[OSALA_MAQUINA]  WITH CHECK ADD  CONSTRAINT [FK_SALA_MAQUINA_SALA] FOREIGN KEY([IDLOJA], [IDSALA]) REFERENCES [dbo].[OSALA] ([IDLOJA], [IDSALA]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[OSALA_MAQUINA] CHECK CONSTRAINT [FK_SALA_MAQUINA_SALA]
GO

DROP TABLE OLOJA1
GO
DROP TABLE OSALA1
GO

/****************************************************************************/
/****************************************************************************/
DROP TABLE FORNECEDOR_PRODUTO
GO
DROP TABLE FORNECEDOR
GO
/**/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FORNECEDOR](
	[IDLOJA] [int] NOT NULL,
	[IDFOR] [int] NOT NULL,
	[NMFOR] [varchar](30) NULL,
	[RZFOR] [varchar](80) NULL,
	[CNPJFOR] [varchar](14) NULL,
	[INSCMUNIC] [varchar](20) NULL,
	[TELFOR1] [varchar](20) NULL,
	[TELFOR2] [varchar](20) NULL,
	[FAXFOR] [varchar](20) NULL,
	[EMAIL] [varchar](50) NULL,
	[ENDFOR] [varchar](100) NULL,
	[BAIFOR] [varchar](50) NULL,
	[CIDFOR] [varchar](50) NULL,
	[ESTADOFOR] [varchar](50) NULL,
	[CEPFOR] [varchar](15) NULL,
	[NMCONTATO] [varchar](30) NULL,
	[CARGOCONTATO] [varchar](30) NULL,
	[CONDPGTO] [varchar](20) NULL,
	[GRUPO] [varchar](50) NULL,
	[FORMAPGTO] [char](1) NULL,
	[SIGLAPAIS] [varchar](5) NULL,
	[DTCADASTRO] [datetime] NULL,
	[QLFFOR] [varchar](1) NULL,
	[IDUSU] [varchar](10) NULL,
	[INSCEST] [varchar](20) NULL,
	[INSCOUTROS] [varchar](20) NULL,
	[PJ] [char](1) NULL,
	[OBS] [varchar](255) NULL,
	[TELCONTATO1] [varchar](20) NULL,
	[TELCONTATO2] [varchar](20) NULL,
	[FAXCONTATO] [varchar](20) NULL,
	[EMAILCONTATO] [varchar](50) NULL,
	[NUMBANCO] [varchar](20) NULL,
	[NMBANCO] [varchar](50) NULL,
	[NUMAGENCIA] [varchar](20) NULL,
	[NMAGENCIA] [varchar](50) NULL,
	[NUMCONTA] [varchar](20) NULL,
	[OPCSIMPLES] [char](1) NULL,
	[SERVICO] [char](1) NULL,
	[MATERIAL] [char](1) NULL,
	[VERIFDOC] [char](1) NULL,
	[DSCPAIS] [varchar](30) NULL,
	[IDPAIS] [int] NULL,
	[IDMATRIZ] [int] NULL,
	[IDAUXILIAR] [varchar](10) NULL,
	[DVCONTA] [char](1) NULL,
PRIMARY KEY CLUSTERED 
( [IDLOJA] ASC,	[IDFOR] ASC) 
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[FORNECEDOR_PRODUTO](
	[IDLOJA] [int] NOT NULL,
	[IDFOR] [int] NOT NULL,
	[IDPROD] [decimal](10, 0) NOT NULL,	
 CONSTRAINT [PK_FORNECEDOR_PRODUTO] PRIMARY KEY CLUSTERED 
([IDLOJA] ASC, [IDFOR] ASC, [IDPROD] ASC) 
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/*******************************************************/
/*******************************************************/
EXECUTE sp_rename N'dbo.OAGENDA', N'OAGENDA1', 'OBJECT'  
GO 
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_OEVENTOREC_OAGENDA]') AND parent_object_id = OBJECT_ID(N'[dbo].[OEVENTOREC]')) ALTER TABLE [dbo].[OEVENTOREC] DROP CONSTRAINT [FK_OEVENTOREC_OAGENDA]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_OEVENTOAGENDA_OAGENDA]') AND parent_object_id = OBJECT_ID(N'[dbo].[OEVENTOAGENDA]')) ALTER TABLE [dbo].[OEVENTOAGENDA] DROP CONSTRAINT [FK_OEVENTOAGENDA_OAGENDA]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OAGENDA1]') AND name = N'PK_OAGENDA') ALTER TABLE [dbo].[OAGENDA1] DROP CONSTRAINT [PK_OAGENDA]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_AGENDA_SALA]') AND parent_object_id = OBJECT_ID(N'[dbo].[OAGENDA1]')) ALTER TABLE [dbo].[OAGENDA1] DROP CONSTRAINT [FK_AGENDA_SALA]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_OAGENDA_OLOJA]') AND parent_object_id = OBJECT_ID(N'[dbo].[OAGENDA1]')) ALTER TABLE [dbo].[OAGENDA1] DROP CONSTRAINT [FK_OAGENDA_OLOJA]
GO

SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[OAGENDA](
	[IDLOJA] [int] NOT NULL,
	[IDAGENDA] [int] NOT NULL,
	[IDSALA] [int] NULL,
	[CODAGENDA] [varchar](10) NULL,	
	[ALTERSTAMP] [int] NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
 CONSTRAINT [PK_OAGENDA] PRIMARY KEY CLUSTERED 
([IDLOJA] ASC, [IDAGENDA] ASC) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]) ON [PRIMARY]
GO
exec sp_bindefault DF_1, 'OAGENDA.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OAGENDA.TIMESTAMP'
go
SET ANSI_PADDING OFF
GO

INSERT INTO dbo.OAGENDA (IDLOJA,IDAGENDA,IDSALA,CODAGENDA) SELECT IDLOJA,IDAGENDA,IDSALA,CODAGENDA FROM OAGENDA1
GO 
ALTER TABLE [dbo].[OAGENDA]  WITH CHECK ADD CONSTRAINT [FK_AGENDA_SALA] FOREIGN KEY([IDLOJA], [IDSALA]) REFERENCES [dbo].[OSALA] ([IDLOJA], [IDSALA]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[OAGENDA] CHECK CONSTRAINT [FK_AGENDA_SALA]
GO
ALTER TABLE [dbo].[OEVENTOREC]  WITH CHECK ADD CONSTRAINT [FK_OEVENTOREC_OAGENDA] FOREIGN KEY([IDLOJA], [IDAGENDA]) REFERENCES [dbo].[OAGENDA] ([IDLOJA], [IDAGENDA]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[OEVENTOREC] CHECK CONSTRAINT [FK_OEVENTOREC_OAGENDA]
GO
ALTER TABLE [dbo].[OEVENTOAGENDA]  WITH CHECK ADD  CONSTRAINT [FK_OEVENTOAGENDA_OAGENDA] FOREIGN KEY([IDLOJA],[IDAGENDA]) REFERENCES [dbo].[OAGENDA] ([IDLOJA], [IDAGENDA]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[OEVENTOAGENDA] CHECK CONSTRAINT [FK_OEVENTOAGENDA_OAGENDA]
GO
DROP TABLE OAGENDA1
GO
/*******************************************************/
/*******************************************************/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_EVENTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[OTAREFAEVT]')) ALTER TABLE [dbo].[OTAREFAEVT] DROP CONSTRAINT [FK_EVENTO]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_22]') AND parent_object_id = OBJECT_ID(N'[dbo].[OSERVICOEVT]')) ALTER TABLE [dbo].[OSERVICOEVT] DROP CONSTRAINT [R_22]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_22]') AND parent_object_id = OBJECT_ID(N'[dbo].[OSERVICOEVT]')) ALTER TABLE [dbo].[OSERVICOEVT] DROP CONSTRAINT [R_22]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_165]') AND parent_object_id = OBJECT_ID(N'[dbo].[OATENDIMENTO]')) ALTER TABLE [dbo].[OATENDIMENTO] DROP CONSTRAINT [R_165]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OEVENTOAGENDA]') AND name = N'PK_EVENTOAGENDA') ALTER TABLE [dbo].[OEVENTOAGENDA] DROP CONSTRAINT [PK_EVENTOAGENDA]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_OEVENTOAGENDA_OAGENDA]') AND parent_object_id = OBJECT_ID(N'[dbo].[OEVENTOAGENDA]')) ALTER TABLE [dbo].[OEVENTOAGENDA] DROP CONSTRAINT [FK_OEVENTOAGENDA_OAGENDA]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_169]') AND parent_object_id = OBJECT_ID(N'[dbo].[OEVENTOAGENDA]')) ALTER TABLE [dbo].[OEVENTOAGENDA] DROP CONSTRAINT [R_169]
GO
/**/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OEVENTOAGENDA]') AND name = N'R_25') ALTER TABLE [dbo].[OEVENTOAGENDA] DROP CONSTRAINT [R_25]
GO
EXECUTE sp_rename N'dbo.OEVENTOAGENDA', N'OEVENTOAGENDA1', 'OBJECT'  
GO 

SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[OEVENTOAGENDA](
	[IDLOJA] [int] NOT NULL,
	[IDEVENTO] [int] NOT NULL,	
	[IDEVENTOREC] [int] NULL,
	[IDAGENDA] [int] NULL,
	[IDCLIENTE] [int] NULL,
	[StartDateTime] [datetime] NULL,
	[EndDateTime] [datetime] NULL,
	[RecurrenceState] [int] NULL,
	[Subject] [nvarchar](255) NULL,
	[Location] [nvarchar](255) NULL,
	[Body] [nvarchar](max) NULL,
	[BusyStatus] [int] NULL,
	[ImportanceLevel] [int] NULL,
	[LabelID] [int] NULL,
	[ScheduleID] [int] NULL,
	[IsRecurrenceExceptionDeleted] [int] NULL,
	[RExceptionStartTimeOrig] [datetime] NULL,
	[RExceptionEndTimeOrig] [datetime] NULL,
	[IsAllDayEvent] [int] NULL,
	[IsMeeting] [int] NULL,
	[IsPrivate] [int] NULL,
	[IsReminder] [int] NULL,
	[ReminderMinutesBeforeStart] [int] NULL,
	[RemainderSoundFile] [nvarchar](255) NULL,
	[CustomPropertiesXMLData] [ntext] NULL,
	[CustomIconsIDs] [ntext] NULL,
	[Created] [datetime] NULL,
	[Modified] [datetime] NULL,
	[FLGCONFIRMADO] [int] NULL,
	[FLGCANCELADO] [int] NULL,
	[FLGREMARCADO] [int] NULL,   
	[ALTERSTAMP] [int] NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
 CONSTRAINT [PK_EVENTOAGENDA] PRIMARY KEY NONCLUSTERED 
([IDLOJA] ASC, [IDEVENTO] ASC)
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
exec sp_bindefault DF_0, 'OEVENTOAGENDA.FLGCONFIRMADO'
go
exec sp_bindefault DF_0, 'OEVENTOAGENDA.FLGCANCELADO'
go
exec sp_bindefault DF_1, 'OEVENTOAGENDA.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OEVENTOAGENDA.TIMESTAMP'
go
SET ANSI_PADDING OFF
GO

INSERT INTO dbo.OEVENTOAGENDA ([IDLOJA],[IDEVENTO],[IDEVENTOREC],[IDAGENDA],[IDCLIENTE],[StartDateTime],[EndDateTime],[RecurrenceState],[Subject],[Location],[Body],[BusyStatus],[ImportanceLevel],[LabelID],[ScheduleID],[IsRecurrenceExceptionDeleted],[RExceptionStartTimeOrig],[RExceptionEndTimeOrig],[IsAllDayEvent],[IsMeeting],[IsPrivate],[IsReminder],[ReminderMinutesBeforeStart],[RemainderSoundFile],[CustomPropertiesXMLData],[CustomIconsIDs],[Created],[Modified],[FLGCONFIRMADO],[FLGCANCELADO],[FLGREMARCADO],[ALTERSTAMP],[TIMESTAMP])  SELECT [IDLOJA],[IDEVENTO],[IDEVENTOREC],[IDAGENDA],[IDCLIENTE],[StartDateTime],[EndDateTime],[RecurrenceState],[Subject],[Location],[Body],[BusyStatus],[ImportanceLevel],[LabelID],[ScheduleID],[IsRecurrenceExceptionDeleted],[RExceptionStartTimeOrig],[RExceptionEndTimeOrig],[IsAllDayEvent],[IsMeeting],[IsPrivate],[IsReminder],[ReminderMinutesBeforeStart],[RemainderSoundFile],[CustomPropertiesXMLData],[CustomIconsIDs],[Created],[Modified],[FLGCONFIRMADO],[FLGCANCELADO],[FLGREMARCADO],[ALTERSTAMP],[TIMESTAMP] FROM OEVENTOAGENDA1
GO 
ALTER TABLE [dbo].[OEVENTOAGENDA]  WITH CHECK ADD  CONSTRAINT [FK_OEVENTOAGENDA_OAGENDA] FOREIGN KEY([IDLOJA], [IDAGENDA]) REFERENCES [dbo].[OAGENDA] ([IDLOJA], [IDAGENDA]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[OEVENTOAGENDA] CHECK CONSTRAINT [FK_OEVENTOAGENDA_OAGENDA]
GO
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='SESTOQUE' AND C.NAME='IDLOJA') ALTER TABLE SESTOQUE ADD IDLOJA INT NOT NULL DEFAULT 1
GO
IF EXISTS (SELECT * FROM SESTOQUE WHERE IDLOJA IS NULL ) UPDATE SESTOQUE SET IDLOJA =(SELECT MIN(IDLOJA) FROM OLOJA) WHERE IDLOJA IS NULL
GO
IF  NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OCLIENTE]') AND name = N'PK_CLIENTE') ALTER TABLE OCLIENTE ADD CONSTRAINT PK_OCLIENTE PRIMARY KEY CLUSTERED ([IDLOJA] ASC,[IDCLIENTE] ASC)WITH (PAD_INDEX  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OEVENTOAGENDA]  WITH NOCHECK ADD  CONSTRAINT [R_169] FOREIGN KEY([IDLOJA], [IDCLIENTE]) REFERENCES [dbo].[OCLIENTE] ([IDLOJA], [IDCLIENTE])
GO
ALTER TABLE [dbo].[OEVENTOAGENDA] NOCHECK CONSTRAINT [R_169]
GO
IF  NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OEVENTOAGENDA]') AND name = N'PK_EVENTOAGENDA') ALTER TABLE OEVENTOAGENDA ADD CONSTRAINT PK_EVENTOAGENDA PRIMARY KEY CLUSTERED ([IDLOJA] ASC,[IDEVENTO] ASC)WITH (PAD_INDEX  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF) ON [PRIMARY]
GO

ALTER TABLE [dbo].[OATENDIMENTO]  WITH NOCHECK ADD  CONSTRAINT [R_165] FOREIGN KEY([IDLOJA], [IDEVENTO]) REFERENCES [dbo].[OEVENTOAGENDA] ([IDLOJA], [IDEVENTO])
GO
ALTER TABLE [dbo].[OATENDIMENTO] NOCHECK CONSTRAINT [R_165]
GO

DROP TABLE OEVENTOAGENDA1
GO
/****************************************************************************/
/****************************************************************************/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_25]') AND parent_object_id = OBJECT_ID(N'[dbo].[OEVENTOAGENDA]')) ALTER TABLE [dbo].[OEVENTOAGENDA] DROP CONSTRAINT [R_25]
GO
/**/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OEVENTOREC]') AND name = N'PK_EVENTOREC') ALTER TABLE [dbo].[OEVENTOREC] DROP CONSTRAINT [PK_EVENTOREC]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_OEVENTOREC_OAGENDA]') AND parent_object_id = OBJECT_ID(N'[dbo].[OEVENTOREC]')) ALTER TABLE [dbo].[OEVENTOREC] DROP CONSTRAINT [FK_OEVENTOREC_OAGENDA]
GO
EXECUTE sp_rename N'dbo.OEVENTOREC', N'OEVENTOREC1', 'OBJECT'  
go
/**/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OEVENTOREC](
	[IDEVENTOREC] [int] NOT NULL,
	[IDLOJA] [int] NOT NULL,
	[IDAGENDA] [int] NOT NULL,
	[MasterEventID] [int] NULL,
	[PatternStartDate] [datetime] NULL,
	[PatternEndMethod] [int] NULL,
	[PatternEndDate] [datetime] NULL,
	[PatternEndAfterOccurrences] [int] NULL,
	[EventStartTime] [varchar](8) NULL,
	[EventDuration] [int] NULL,
	[OptionsData1] [int] NULL,
	[OptionsData2] [int] NULL,
	[OptionsData3] [int] NULL,
	[OptionsData4] [int] NULL,
	[CustomPropertiesXMLData] [ntext] NULL,
	[ALTERSTAMP] [int] NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
 CONSTRAINT [PK_EVENTOREC] PRIMARY KEY NONCLUSTERED 
(
	[IDLOJA] ASC,
	[IDEVENTOREC] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

exec sp_bindefault DF_1, 'OEVENTOREC.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OEVENTOREC.TIMESTAMP'
go
SET ANSI_PADDING OFF
GO

INSERT INTO dbo.OEVENTOREC ([IDLOJA],[IDEVENTOREC],[IDAGENDA],[MasterEventID],[PatternStartDate],[PatternEndMethod],[PatternEndDate],[PatternEndAfterOccurrences],[EventStartTime],[EventDuration],[OptionsData1],[OptionsData2],[OptionsData3],[OptionsData4],[CustomPropertiesXMLData],[ALTERSTAMP],[TIMESTAMP]) SELECT [IDLOJA],[IDEVENTOREC],[IDAGENDA],[MasterEventID],[PatternStartDate],[PatternEndMethod],[PatternEndDate],[PatternEndAfterOccurrences],[EventStartTime],[EventDuration],[OptionsData1],[OptionsData2],[OptionsData3],[OptionsData4],[CustomPropertiesXMLData],[ALTERSTAMP],[TIMESTAMP] FROM OEVENTOREC1
GO 

ALTER TABLE [dbo].[OEVENTOREC]  WITH CHECK ADD CONSTRAINT [FK_OEVENTOREC_OAGENDA] FOREIGN KEY([IDLOJA], [IDAGENDA]) REFERENCES [dbo].[OAGENDA] ([IDLOJA], [IDAGENDA]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[OEVENTOREC] CHECK CONSTRAINT [FK_OEVENTOREC_OAGENDA]
GO
DROP TABLE OEVENTOREC1
GO
/*******************************************************/
/*******************************************************/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_148]') AND parent_object_id = OBJECT_ID(N'[dbo].[OTAREFA_CAT]')) ALTER TABLE [dbo].[OTAREFA_CAT] DROP CONSTRAINT [R_148]
GO

/**/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OTAREFAEVT]') AND name = N'PK_OTAREFAEVT') ALTER TABLE [dbo].[OTAREFAEVT] DROP CONSTRAINT [PK_OTAREFAEVT]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_LOJA]') AND parent_object_id = OBJECT_ID(N'[dbo].[OTAREFAEVT]')) ALTER TABLE [dbo].[OTAREFAEVT] DROP CONSTRAINT [FK_LOJA]
GO
EXECUTE sp_rename N'dbo.OTAREFAEVT', N'OTAREFAEVT1', 'OBJECT'  
GO 
/**/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OTAREFAEVT](
	[IDLOJA] [int] NOT NULL,	
	[IDTAREFA] [int] NOT NULL,	
	[IDEVENTO] [int] NULL,
	[DSCTAREFA] [ntext] NULL,
	[TITULO] [varchar](80) NULL,
	[DTTAREFA] [datetime] NULL,
	[SITTAREFA] [int] NULL,
	[IDCLIENTE] [int] NULL,
	[PRIORIDADE] [int] NULL,
	[FLGLEMBRETE] [int] NULL,
	[DTLEMBRETE] [datetime] NULL,
	[IDTPTAREFA] [int] NULL,
	[FLGDELETE] [int] NULL,
	[FLGAUTO] [int] NULL,
	[ALTERSTAMP] [int] NULL,
	[TIMESTAMP] [datetime] NULL,
 CONSTRAINT [PK_OTAREFAEVT] PRIMARY KEY NONCLUSTERED 
([IDLOJA] ASC, [IDTAREFA] ASC) 
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
exec sp_bindefault DF_1, 'OTAREFAEVT.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OTAREFAEVT.TIMESTAMP'
go
exec sp_bindefault DF_0, 'OTAREFAEVT.FLGDELETE'
go
exec sp_bindefault DF_0, 'OTAREFAEVT.FLGAUTO'
go
SET ANSI_PADDING OFF
GO

INSERT INTO dbo.OTAREFAEVT (
[IDLOJA],[IDTAREFA],[IDEVENTO],[DSCTAREFA],[TITULO],[DTTAREFA],[SITTAREFA],[IDCLIENTE],[PRIORIDADE],[FLGLEMBRETE],[DTLEMBRETE],[IDTPTAREFA],[FLGDELETE],[FLGAUTO],[ALTERSTAMP],[TIMESTAMP]
) 
SELECT 
[IDLOJA],[IDTAREFA],[IDEVENTO],[DSCTAREFA],[TITULO],[DTTAREFA],[SITTAREFA],[IDCLIENTE],[PRIORIDADE],[FLGLEMBRETE],[DTLEMBRETE],[IDTPTAREFA],[FLGDELETE],[FLGAUTO],[ALTERSTAMP],[TIMESTAMP]
FROM OTAREFAEVT1
GO 

ALTER TABLE OTAREFAEVT ADD CONSTRAINT  FK_LOJA FOREIGN KEY (IDLOJA) REFERENCES OLOJA(IDLOJA)
GO
ALTER TABLE [dbo].[OTAREFAEVT] CHECK CONSTRAINT [FK_LOJA]
GO
ALTER TABLE OTAREFA_CAT	ADD CONSTRAINT  R_148 FOREIGN KEY (IDLOJA,IDTAREFA) REFERENCES OTAREFAEVT(IDLOJA,IDTAREFA)
go
ALTER TABLE [dbo].[OEVENTOAGENDA]  WITH NOCHECK ADD  CONSTRAINT [R_25] FOREIGN KEY([IDLOJA], [IDEVENTOREC]) REFERENCES [dbo].[OEVENTOREC] ([IDLOJA], [IDEVENTOREC])
GO
ALTER TABLE [dbo].[OEVENTOAGENDA] NOCHECK CONSTRAINT [R_25]
GO
DROP TABLE OTAREFAEVT1
GO
/*******************************************************/
/*******************************************************/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_146]') AND parent_object_id = OBJECT_ID(N'[dbo].[OTAREFA_CAT]')) ALTER TABLE [dbo].[OTAREFA_CAT] DROP CONSTRAINT [R_146]
GO
/**/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OCATTAREFA]') AND name = N'PK_OCATTAREFA') ALTER TABLE [dbo].[OCATTAREFA] DROP CONSTRAINT [PK_OCATTAREFA]
GO
EXECUTE sp_rename N'dbo.OCATTAREFA', N'OCATTAREFA1', 'OBJECT'  
GO 
/**/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OCATTAREFA]
(	IDLOJA INT NOT NULL,
	IDCATTAREFA INT NOT NULL,
	DSCCATTAREFA varchar(50) NULL,
	ATIVO int NULL,
	ALTERSTAMP integer NULL ,
	TIMESTAMP datetime NULL 
)
go
ALTER TABLE OCATTAREFA ADD CONSTRAINT  PK_OCATTAREFA PRIMARY KEY   NONCLUSTERED (IDLOJA ASC, IDCATTAREFA ASC)
go
exec sp_bindefault DF_1, 'OCATTAREFA.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OCATTAREFA.TIMESTAMP'
go
SET ANSI_PADDING OFF
GO
INSERT INTO dbo.OCATTAREFA ([IDLOJA],[IDCATTAREFA],[DSCCATTAREFA],[ATIVO],[ALTERSTAMP],[TIMESTAMP]) SELECT (SELECT MIN(IDLOJA) FROM OLOJA),[IDCATTAREFA],[DSCCATTAREFA],[ATIVO],[ALTERSTAMP],[TIMESTAMP] FROM OCATTAREFA1
GO 
ALTER TABLE OTAREFA_CAT ADD CONSTRAINT  R_146 FOREIGN KEY (IDLOJA, IDCATTAREFA) REFERENCES OCATTAREFA(IDLOJA, IDCATTAREFA)
go
DROP TABLE OCATTAREFA1
GO
/*******************************************************/
/*******************************************************/
/**/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OTIPOTAREFA]') AND name = N'PK_OTIPOTAREFA') ALTER TABLE [dbo].[OTIPOTAREFA] DROP CONSTRAINT [PK_OTIPOTAREFA]
GO
EXECUTE sp_rename N'dbo.OTIPOTAREFA', N'OTIPOTAREFA1', 'OBJECT'  
GO 
/**/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OTIPOTAREFA]
(	IDLOJA int NOT NULL,
	IDTPTAREFA  int NOT NULL,
	DSCTPTAREFA varchar(50) NULL,
    ATIVO int NULL,
    DIFHORA int NULL,
	ALTERSTAMP integer  NULL ,
	TIMESTAMP  datetime  NULL
)
go
ALTER TABLE OTIPOTAREFA ADD CONSTRAINT  PK_OTIPOTAREFA PRIMARY KEY NONCLUSTERED (IDLOJA ASC,IDTPTAREFA  ASC)
go
exec sp_bindefault DF_1, 'OTIPOTAREFA.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OTIPOTAREFA.TIMESTAMP'
go
exec sp_bindefault DF_1, 'OTIPOTAREFA.ATIVO'
go
SET ANSI_PADDING OFF
GO

INSERT INTO dbo.OTIPOTAREFA (
[IDLOJA],[IDTPTAREFA],[DSCTPTAREFA],[ATIVO],[DIFHORA],[ALTERSTAMP],[TIMESTAMP]
) 
SELECT 
(SELECT MIN(IDLOJA) FROM OLOJA),[IDTPTAREFA],[DSCTPTAREFA],[ATIVO],[DIFHORA],[ALTERSTAMP],[TIMESTAMP]
FROM OTIPOTAREFA1
GO 

DROP TABLE OTIPOTAREFA1
GO
/*******************************************************/
/*******************************************************/
/**/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OTRATAMENTO_PROD]') AND name = N'PK_OTRATAMENTO_PROD') ALTER TABLE [dbo].[OTRATAMENTO_PROD] DROP CONSTRAINT [PK_OTRATAMENTO_PROD]
GO
EXECUTE sp_rename N'dbo.OTRATAMENTO_PROD', N'OTRATAMENTO_PROD1', 'OBJECT'  
GO 
/**/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OTRATAMENTO_PROD](
	[IDLOJA] [int] NOT NULL,
	[ID] [int] NOT NULL,
	[IDTPSERVICO] [int] NULL,
	[IDTPTRATAMENTO] [int] NULL,
	[IDAREA] [int] NULL,
	[IDPROD] [decimal](10, 0) NULL,
	[ALTERSTAMP] [int] NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
 CONSTRAINT [PK_OTRATAMENTO_PROD] PRIMARY KEY CLUSTERED 
([IDLOJA] ASC, [ID] ASC) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]) ON [PRIMARY]
GO
exec sp_bindefault DF_1, 'OTRATAMENTO_PROD.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OTRATAMENTO_PROD.TIMESTAMP'
go
SET ANSI_PADDING OFF
GO

INSERT INTO dbo.OTRATAMENTO_PROD (
[IDLOJA],[ID],[IDTPSERVICO],[IDTPTRATAMENTO],[IDAREA],[IDPROD],[ALTERSTAMP],[TIMESTAMP]
) 
SELECT 
(SELECT MIN(IDLOJA) FROM OLOJA),[ID],[IDTPSERVICO],[IDTPTRATAMENTO],[IDAREA],[IDPROD],[ALTERSTAMP],[TIMESTAMP]
FROM OTRATAMENTO_PROD1
GO 
DROP TABLE OTRATAMENTO_PROD1
GO
/*******************************************************/
/*******************************************************/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_OATENDIMENTO_PRODUTO_PRODUTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[OATENDIMENTO_PRODUTO]')) ALTER TABLE [dbo].[OATENDIMENTO_PRODUTO] DROP CONSTRAINT [FK_OATENDIMENTO_PRODUTO_PRODUTO]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_FORNECEDOR_PRODUTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[FORNECEDOR_PRODUTO]')) ALTER TABLE [dbo].[FORNECEDOR_PRODUTO] DROP CONSTRAINT [FK_FORNECEDOR_PRODUTO]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_158]') AND parent_object_id = OBJECT_ID(N'[dbo].[FITEMFATURA]')) ALTER TABLE [dbo].[FITEMFATURA] DROP CONSTRAINT [R_158]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_SESTPROD_ESTOQUE]') AND parent_object_id = OBJECT_ID(N'[dbo].[SESTPROD]')) ALTER TABLE [dbo].[SESTPROD] DROP CONSTRAINT [FK_SESTPROD_ESTOQUE]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_SESTPROD_PRODUTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[SESTPROD]')) ALTER TABLE [dbo].[SESTPROD] DROP CONSTRAINT [FK_SESTPROD_PRODUTO]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_182]') AND parent_object_id = OBJECT_ID(N'[dbo].[SPRODUTO]')) ALTER TABLE [dbo].[SPRODUTO] DROP CONSTRAINT [R_182]
GO
/******/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[SPRODUTO]') AND name = N'PK_PRODUTO') ALTER TABLE [dbo].[SPRODUTO] DROP CONSTRAINT [PK_PRODUTO]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[SPRODUTO]') AND name = N'XCODPROD') DROP INDEX [XCODPROD] ON [dbo].[SPRODUTO] WITH ( ONLINE = OFF ) 
GO
ALTER TABLE [dbo].[SPRODUTO] DROP CONSTRAINT [DF_PRODUTO_SIGLAUNID]
GO
/******/
UPDATE SPRODUTO SET IDLOJA =(SELECT MIN(IDLOJA) FROM OLOJA) 
go
ALTER TABLE [dbo].[SPRODUTO] ADD  CONSTRAINT [PK_PRODUTO] PRIMARY KEY CLUSTERED ([IDLOJA] ASC, [IDPROD] ASC) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OATENDIMENTO_PRODUTO]  WITH CHECK ADD  CONSTRAINT [FK_OATENDIMENTO_PRODUTO_PRODUTO] FOREIGN KEY([IDLOJA], [IDPROD]) REFERENCES [dbo].[SPRODUTO] ([IDLOJA], [IDPROD])
GO
ALTER TABLE [dbo].[OATENDIMENTO_PRODUTO] CHECK CONSTRAINT [FK_OATENDIMENTO_PRODUTO_PRODUTO]
GO
ALTER TABLE [dbo].[FORNECEDOR_PRODUTO]  WITH CHECK ADD  CONSTRAINT [FK_FORNECEDOR_PRODUTO] FOREIGN KEY([IDLOJA],[IDPROD]) REFERENCES [dbo].[SPRODUTO] ([IDLOJA],[IDPROD]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[FORNECEDOR_PRODUTO] CHECK CONSTRAINT [FK_FORNECEDOR_PRODUTO]
GO
IF EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='SESTPROD' AND C.NAME='IDLOJA') 
	ALTER TABLE [dbo].[SESTPROD]  WITH CHECK ADD  CONSTRAINT [FK_SESTPROD_ESTOQUE] FOREIGN KEY([IDLOJA],[IDEST]) REFERENCES [dbo].[SESTOQUE] ([IDLOJA],[IDEST]) ON UPDATE CASCADE
ELSE	
    ALTER TABLE [dbo].[SESTPROD]  WITH CHECK ADD  CONSTRAINT [FK_SESTPROD_ESTOQUE] FOREIGN KEY([IDEST]) REFERENCES [dbo].[SESTOQUE] ([IDEST]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[SESTPROD] CHECK CONSTRAINT [FK_SESTPROD_ESTOQUE]
GO
ALTER TABLE SPRODUTO ADD CONSTRAINT  R_182 FOREIGN KEY (IDLOJA) REFERENCES OLOJA(IDLOJA)
go
CREATE  UNIQUE INDEX XCODPROD ON SPRODUTO (IDLOJA ASC, CODPROD ASC)
go
ALTER TABLE [dbo].[SPRODUTO] ADD  CONSTRAINT [DF_PRODUTO_SIGLAUNID]  DEFAULT ('pç') FOR [UNIDCOMPRA]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PPN]') AND type in (N'U')) EXECUTE sp_rename N'dbo.PPN', N'PPN1', 'OBJECT'  
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_149]') AND parent_object_id = OBJECT_ID(N'[dbo].[PPNITEM]')) ALTER TABLE [dbo].[PPNITEM] DROP CONSTRAINT [R_149]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[PPN1]') AND name = N'PK_PPN') ALTER TABLE [dbo].[PPN1] DROP CONSTRAINT [PK_PPN]
GO

CREATE TABLE [dbo].[PPN]
(	IDLOJA  int  NOT NULL, 
	IDPN  int  NOT NULL ,
	CODPN  varchar(10)  NULL ,
	DSCPN  varchar(50)  NULL ,	
	ALTERSTAMP  int  NULL ,
	TIMESTAMP  datetime  NULL
)
go
ALTER TABLE PPN	ADD CONSTRAINT  PK_PPN PRIMARY KEY   NONCLUSTERED (IDLOJA  ASC,IDPN  ASC)
go
exec sp_bindefault DF_1, 'PPN.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'PPN.TIMESTAMP'
go

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PPNITEM]') AND type in (N'U')) DROP TABLE [dbo].[PPNITEM]
GO

CREATE TABLE [dbo].[PPNITEM]
(	IDLOJA  int  NOT NULL,
	IDPN  int  NOT NULL ,
	ITEM  int  NOT NULL ,
	DTITEM  datetime  NULL ,
	VLAREA  numeric(9,2)  NULL ,
	VLPROD  numeric(9,2)  NULL ,
	VLFAT  numeric(9,2)  NULL ,
	ALTERSTAMP  int  NULL ,
	TIMESTAMP  datetime  NULL		
)
go
ALTER TABLE PPNITEM	ADD CONSTRAINT  PK_PPNITEM PRIMARY KEY   NONCLUSTERED (IDLOJA  ASC,IDPN  ASC,ITEM  ASC)
go
exec sp_bindefault DF_1, 'PPNITEM.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'PPNITEM.TIMESTAMP'
go
ALTER TABLE PPNITEM ADD CONSTRAINT  R_149 FOREIGN KEY (IDLOJA,IDPN) REFERENCES PPN(IDLOJA,IDPN)	ON UPDATE CASCADE
go

CREATE TABLE [dbo].[OCLIENTEFOTOS]
(	IDLOJA  int  NOT NULL ,
	IDCLIENTE  int  NOT NULL ,
	IDFOTO  int  NOT NULL ,
	ARQUIVO  varchar(500)  NULL ,
	IDATENDIMENTO  int  NULL ,
	ALTERSTAMP  int  NULL ,
	TIMESTAMP  datetime  NULL
)
go
ALTER TABLE OCLIENTEFOTOS ADD CONSTRAINT  PK_OCLIENTEFOTOS PRIMARY KEY   NONCLUSTERED (IDLOJA  ASC,IDCLIENTE  ASC,IDFOTO  ASC)
go
exec sp_bindefault DF_1, 'OCLIENTEFOTOS.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OCLIENTEFOTOS.TIMESTAMP'
go
ALTER TABLE OCLIENTEFOTOS	ADD CONSTRAINT  R_168 FOREIGN KEY (IDLOJA,IDCLIENTE) REFERENCES OCLIENTE(IDLOJA,IDCLIENTE) ON UPDATE CASCADE
go

CREATE TABLE [dbo].[CBANDC]
(	IDLOJA  int  NOT NULL ,
	IDBANDC  int  NOT NULL ,
	DSCBANDC  varchar(20)  NULL ,
	ATIVO  int  NULL,
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NULL 
)
go
ALTER TABLE CBANDC ADD CONSTRAINT  PK_CBANDC PRIMARY KEY   NONCLUSTERED (IDLOJA  ASC,IDBANDC  ASC)
go
exec sp_bindefault DF_1, 'CBANDC.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'CBANDC.TIMESTAMP'
go
exec sp_bindefault DF_1, 'CBANDC.ATIVO'
go

CREATE TABLE [dbo].[CBANDCTX]
(	IDLOJA  int  NOT NULL ,
	IDBANDC  int  NOT NULL ,
	IDFORMAPGTO  int  NOT NULL,
	TXSERV  decimal(4,2)  NULL ,
	TXPARC  decimal(4,2)  NULL ,
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NULL 
)
go
ALTER TABLE CBANDCTX ADD CONSTRAINT  PK_CBANDCTX PRIMARY KEY   NONCLUSTERED (IDLOJA  ASC,IDBANDC  ASC,IDFORMAPGTO  ASC)
go
exec sp_bindefault DF_1, 'CBANDCTX.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'CBANDCTX.TIMESTAMP'
go
ALTER TABLE CBANDCTX ADD CONSTRAINT  R_180 FOREIGN KEY (IDLOJA,IDBANDC) REFERENCES CBANDC(IDLOJA,IDBANDC) ON UPDATE CASCADE
go
/***************************************************************/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[GFERIADO]') AND name = N'PK_GFERIADO') ALTER TABLE [dbo].[GFERIADO] DROP CONSTRAINT [PK_GFERIADO]
GO
EXECUTE sp_rename N'dbo.GFERIADO', N'GFERIADO1', 'OBJECT'  
GO 
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[GFERIADO]
(	IDLOJA int NOT NULL ,
	DATA  smalldatetime  NOT NULL ,
	DSCFERIADO  varchar(20)  NULL ,
	ESCOPO  int  NULL, 
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NULL )
go
ALTER TABLE GFERIADO ADD CONSTRAINT  PK_GFERIADO PRIMARY KEY   NONCLUSTERED (IDLOJA ASC, DATA  ASC)
go
exec sp_bindefault DF_1, 'GFERIADO.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'GFERIADO.TIMESTAMP'
go
exec sp_bindefault DF_0, 'GFERIADO.ESCOPO'
go
SET ANSI_PADDING OFF
GO
DROP TABLE GFERIADO1
GO
