/****************************************************************************
****************************************************************************/
--USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='45', ARQATU='Rev45.sql';
/****************************************************************************
****************************************************************************/
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='FCCORRENTE' AND C.NAME='IDCOLIGADA') ALTER TABLE FCCORRENTE ADD IDCOLIGADA INT
GO
/***** OTPMAQ ***/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_127]') AND parent_object_id = OBJECT_ID(N'[dbo].[OMAQUINA]')) ALTER TABLE [dbo].[OMAQUINA] DROP CONSTRAINT [R_127]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OTPMAQ]') AND name = N'PK_IDTPMAQ') ALTER TABLE [dbo].[OTPMAQ] DROP CONSTRAINT [PK_IDTPMAQ]
GO
/***** OSALA_MAQUINA ***/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_SALA_MAQUINA_SALA]') AND parent_object_id = OBJECT_ID(N'[dbo].[OSALA_MAQUINA]')) ALTER TABLE [dbo].[OSALA_MAQUINA] DROP CONSTRAINT [FK_SALA_MAQUINA_SALA]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OSALA_MAQUINA]') AND name = N'PK_OSALA_MAQUINA') ALTER TABLE [dbo].[OSALA_MAQUINA] DROP CONSTRAINT [PK_OSALA_MAQUINA]
GO
/***** OMAQUINA ***/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_15]') AND parent_object_id = OBJECT_ID(N'[dbo].[OSALA_MAQUINA]')) ALTER TABLE [dbo].[OSALA_MAQUINA] DROP CONSTRAINT [R_15]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_225]') AND parent_object_id = OBJECT_ID(N'[dbo].[OMAQDISPAROS]')) ALTER TABLE [dbo].[OMAQDISPAROS] DROP CONSTRAINT [R_225]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_133]') AND parent_object_id = OBJECT_ID(N'[dbo].[OMAQMANUT]')) ALTER TABLE [dbo].[OMAQMANUT] DROP CONSTRAINT [R_133]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OMAQUINA]') AND name = N'PK_OMAQUINA') ALTER TABLE [dbo].[OMAQUINA] DROP CONSTRAINT [PK_OMAQUINA]
GO
/***** OTPMANUT ***/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_132]') AND parent_object_id = OBJECT_ID(N'[dbo].[OMAQMANUT]')) ALTER TABLE [dbo].[OMAQMANUT] DROP CONSTRAINT [R_132]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OTPMANUT]') AND name = N'PK_IDTPMANUT') ALTER TABLE [dbo].[OTPMANUT] DROP CONSTRAINT [PK_IDTPMANUT]
GO
/***** OMAQMANUT ***/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_134]') AND parent_object_id = OBJECT_ID(N'[dbo].[OMAQMANUT]')) ALTER TABLE [dbo].[OMAQMANUT] DROP CONSTRAINT [R_134]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OMAQMANUT]') AND name = N'PK_IDMANUT') ALTER TABLE [dbo].[OMAQMANUT] DROP CONSTRAINT [PK_IDMANUT]
GO
/***** OTPMANIPULO ***/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_135]') AND parent_object_id = OBJECT_ID(N'[dbo].[OAREA_TRATAMENTO]')) ALTER TABLE [dbo].[OAREA_TRATAMENTO] DROP CONSTRAINT [R_135]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_126]') AND parent_object_id = OBJECT_ID(N'[dbo].[OMANIPULO]')) ALTER TABLE [dbo].[OMANIPULO] DROP CONSTRAINT [R_126]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_OTPMANIPULO_DISPARO]') AND parent_object_id = OBJECT_ID(N'[dbo].[OMAQDISPAROS]')) ALTER TABLE [dbo].[OMAQDISPAROS] DROP CONSTRAINT [R_OTPMANIPULO_DISPARO]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OTPMANIPULO]') AND name = N'PK_IDTPMANIPULO') ALTER TABLE [dbo].[OTPMANIPULO] DROP CONSTRAINT [PK_IDTPMANIPULO]
GO
/***** OMANIPULO ***/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_137]') AND parent_object_id = OBJECT_ID(N'[dbo].[OATENDIMENTO]')) ALTER TABLE [dbo].[OATENDIMENTO] DROP CONSTRAINT [R_137]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_129]') AND parent_object_id = OBJECT_ID(N'[dbo].[OLAMPADA]')) ALTER TABLE [dbo].[OLAMPADA] DROP CONSTRAINT [R_129]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OMANIPULO]') AND name = N'PK_IDMANIPULO') ALTER TABLE [dbo].[OMANIPULO] DROP CONSTRAINT [PK_IDMANIPULO]
GO
/***** OLAMPADA ***/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_130]') AND parent_object_id = OBJECT_ID(N'[dbo].[OMAQDISPAROS]')) ALTER TABLE [dbo].[OMAQDISPAROS] DROP CONSTRAINT [R_130]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OLAMPADA]') AND name = N'PK_IDLAMPADA') ALTER TABLE [dbo].[OLAMPADA] DROP CONSTRAINT [PK_IDLAMPADA]
GO
/***** OMAQDISPAROS ***/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OMAQDISPAROS]') AND name = N'PK_OMAQDISPAROS') ALTER TABLE [dbo].[OMAQDISPAROS] DROP CONSTRAINT [PK_OMAQDISPAROS]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_136]') AND parent_object_id = OBJECT_ID(N'[dbo].[OMAQDISPAROS]')) ALTER TABLE [dbo].[OMAQDISPAROS] DROP CONSTRAINT [R_136]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_226]') AND parent_object_id = OBJECT_ID(N'[dbo].[OMAQDISPAROS]')) ALTER TABLE [dbo].[OMAQDISPAROS] DROP CONSTRAINT [R_226]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_230]') AND parent_object_id = OBJECT_ID(N'[dbo].[OMAQDISPAROS]')) ALTER TABLE [dbo].[OMAQDISPAROS] DROP CONSTRAINT [R_230]
GO
/***** OAREA ***/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_172]') AND parent_object_id = OBJECT_ID(N'[dbo].[OTRATAMENTOCLI]')) ALTER TABLE [dbo].[OTRATAMENTOCLI] DROP CONSTRAINT [R_172]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_48]') AND parent_object_id = OBJECT_ID(N'[dbo].[OSESSAO]')) ALTER TABLE [dbo].[OSESSAO] DROP CONSTRAINT [R_48]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_157]') AND parent_object_id = OBJECT_ID(N'[dbo].[OSERVICOEVT]')) ALTER TABLE [dbo].[OSERVICOEVT] DROP CONSTRAINT [R_157]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_124]') AND parent_object_id = OBJECT_ID(N'[dbo].[OAREA_TRATAMENTO]')) ALTER TABLE [dbo].[OAREA_TRATAMENTO] DROP CONSTRAINT [R_124]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_125]') AND parent_object_id = OBJECT_ID(N'[dbo].[OAREA_TRATAMENTO]')) ALTER TABLE [dbo].[OAREA_TRATAMENTO] DROP CONSTRAINT [R_125]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OAREA]') AND name = N'PK_AREA') ALTER TABLE [dbo].[OAREA] DROP CONSTRAINT [PK_AREA]
GO
/***** OTPSERVICO ***/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_170]') AND parent_object_id = OBJECT_ID(N'[dbo].[OSESSAO]')) ALTER TABLE [dbo].[OSESSAO] DROP CONSTRAINT [R_170]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_174]') AND parent_object_id = OBJECT_ID(N'[dbo].[OSERVICOEVT]')) ALTER TABLE [dbo].[OSERVICOEVT] DROP CONSTRAINT [R_174]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OTPSERVICO]') AND name = N'PK_OTPSERVICO') ALTER TABLE [dbo].[OTPSERVICO] DROP CONSTRAINT [PK_OTPSERVICO]
GO
/***** OTPTRATAMENTO ***/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_176]') AND parent_object_id = OBJECT_ID(N'[dbo].[OTRATAMENTOCLI]')) ALTER TABLE [dbo].[OTRATAMENTOCLI] DROP CONSTRAINT [R_176]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_171]') AND parent_object_id = OBJECT_ID(N'[dbo].[OSESSAO]')) ALTER TABLE [dbo].[OSESSAO] DROP CONSTRAINT [R_171]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_175]') AND parent_object_id = OBJECT_ID(N'[dbo].[OSERVICOEVT]')) ALTER TABLE [dbo].[OSERVICOEVT] DROP CONSTRAINT [R_175]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OTPTRATAMENTO]') AND name = N'XPKdboTRATAMENTO') ALTER TABLE [dbo].[OTPTRATAMENTO] DROP CONSTRAINT [XPKdboTRATAMENTO]
GO
/***** OAREA_TRATAMENTO ***/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OAREA_TRATAMENTO]') AND name = N'PK_AREATRATAMENTO') ALTER TABLE [dbo].[OAREA_TRATAMENTO] DROP CONSTRAINT [PK_AREATRATAMENTO]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_124]') AND parent_object_id = OBJECT_ID(N'[dbo].[OAREA_TRATAMENTO]')) ALTER TABLE [dbo].[OAREA_TRATAMENTO] DROP CONSTRAINT [R_124]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_125]') AND parent_object_id = OBJECT_ID(N'[dbo].[OAREA_TRATAMENTO]')) ALTER TABLE [dbo].[OAREA_TRATAMENTO] DROP CONSTRAINT [R_125]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_135]') AND parent_object_id = OBJECT_ID(N'[dbo].[OAREA_TRATAMENTO]')) ALTER TABLE [dbo].[OAREA_TRATAMENTO] DROP CONSTRAINT [R_135]
GO
/***** ODIRECAO ***/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_47]') AND parent_object_id = OBJECT_ID(N'[dbo].[OSESSAO]')) ALTER TABLE [dbo].[OSESSAO] DROP CONSTRAINT [R_47]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ODIRECAO]') AND name = N'PK_DIRECAO') ALTER TABLE [dbo].[ODIRECAO] DROP CONSTRAINT [PK_DIRECAO]
GO
/***** OREACAOADV ***/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_178]') AND parent_object_id = OBJECT_ID(N'[dbo].[OSESSAO_REACAOADV]')) ALTER TABLE [dbo].[OSESSAO_REACAOADV] DROP CONSTRAINT [R_178]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OREACAOADV]') AND name = N'PK_OREACAOADV') ALTER TABLE [dbo].[OREACAOADV] DROP CONSTRAINT [PK_OREACAOADV]
GO
/****************************************/

EXECUTE sp_rename N'dbo.OTPMAQ', N'OTPMAQ1', 'OBJECT'  
GO 
EXECUTE sp_rename N'dbo.OSALA_MAQUINA', N'OSALA_MAQUINA1', 'OBJECT'  
GO 
EXECUTE sp_rename N'dbo.OMAQUINA', N'OMAQUINA1', 'OBJECT'  
GO 
EXECUTE sp_rename N'dbo.OTPMANUT', N'OTPMANUT1', 'OBJECT'  
GO 
EXECUTE sp_rename N'dbo.OMAQMANUT', N'OMAQMANUT1', 'OBJECT'  
GO 
EXECUTE sp_rename N'dbo.OTPMANIPULO', N'OTPMANIPULO1', 'OBJECT'  
GO 
EXECUTE sp_rename N'dbo.OMANIPULO', N'OMANIPULO1', 'OBJECT'  
GO 
EXECUTE sp_rename N'dbo.OLAMPADA', N'OLAMPADA1', 'OBJECT'  
GO 
EXECUTE sp_rename N'dbo.OMAQDISPAROS', N'OMAQDISPAROS1', 'OBJECT'  
GO 
EXECUTE sp_rename N'dbo.OAREA', N'OAREA1', 'OBJECT'  
GO 
EXECUTE sp_rename N'dbo.OTPSERVICO', N'OTPSERVICO1', 'OBJECT'  
GO 
EXECUTE sp_rename N'dbo.OTPTRATAMENTO', N'OTPTRATAMENTO1', 'OBJECT'  
GO 
EXECUTE sp_rename N'dbo.OAREA_TRATAMENTO', N'OAREA_TRATAMENTO1', 'OBJECT'  
GO 
EXECUTE sp_rename N'dbo.ODIRECAO', N'ODIRECAO1', 'OBJECT'  
GO 
EXECUTE sp_rename N'dbo.OREACAOADV', N'OREACAOADV1', 'OBJECT'  
GO 
/****************************************/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING OFF
GO 
/****************************************/
 /***** OTPMAQ ***/
CREATE TABLE [dbo].[OTPMAQ]
   (IDLOJA int NOT NULL,
    IDTPMAQ int NOT NULL,
	DSCMAQ varchar(20) NULL,
	TPNUM int NOT NULL,    
    TPMANIPULO int NOT NULL,
    NUMTRATAMENTO varchar(150) NOT NULL,
	ALTERSTAMP int NULL,
	TIMESTAMP datetime NULL,
 CONSTRAINT PK_IDTPMAQ PRIMARY KEY CLUSTERED (IDLOJA ASC,IDTPMAQ ASC) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]) ON [PRIMARY]
GO

exec sp_bindefault DF_1, 'OTPMAQ.ALTERSTAMP'
GO
exec sp_bindefault DF_Now, 'OTPMAQ.TIMESTAMP'
GO
exec sp_bindefault DF_0, 'OTPMAQ.TPNUM'
GO
exec sp_bindefault DF_1, 'OTPMAQ.TPMANIPULO'
go
/***** OSALA_MAQUINA ***/
CREATE TABLE [dbo].[OSALA_MAQUINA](
	[IDLOJA] [int] NOT NULL,
	[IDSALA] [int] NOT NULL,
	[IDMAQUINA] [int] NOT NULL,	
	[DTINICIO] [datetime] NULL,
	[DTFIM] [datetime] NULL,	
	[ALTERSTAMP] [int] NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
 CONSTRAINT [PK_OSALA_MAQUINA] PRIMARY KEY NONCLUSTERED 
([IDLOJA] ASC, [IDSALA] ASC, [IDMAQUINA] ASC)
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OPENDENCIACLI]    Script Date: 07/05/2010 23:23:23 ******/
exec sp_bindefault DF_1, 'OSALA_MAQUINA.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OSALA_MAQUINA.TIMESTAMP'
go
/***** OMAQUINA ***/
CREATE TABLE [dbo].[OMAQUINA](
	[IDLOJA] [int] NOT NULL,	
	[IDMAQUINA] [int] NOT NULL,	
	[CODMAQUINA] [varchar](20) NULL,
	[IDTPMAQ] [int] NULL,
	[NREGISTRO] [varchar](20) NULL,
	[NANVISA] [varchar](20) NULL,
	[DTOPERACAO] [datetime] NULL,
	[DTFECHAMENTO] [datetime] NULL,
	[DISPAROS] [int] NULL,	
	[SITMAQUINA] [int] NULL,
	[ALTERSTAMP] [int] NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
 CONSTRAINT [PK_OMAQUINA] PRIMARY KEY NONCLUSTERED ([IDLOJA] ASC,[IDMAQUINA] ASC) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]) ON [PRIMARY]
GO
exec sp_bindefault DF_1, 'OMAQUINA.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OMAQUINA.TIMESTAMP'
go
exec sp_bindefault DF_1, 'OMAQUINA.SITMAQUINA'
go
/***** OTPMANUT ***/
CREATE TABLE [dbo].[OTPMANUT]
(	IDLOJA  int NOT NULL,
	IDTPMANUT  int NOT NULL,
	DSCMANUT  varchar(20)  NULL,
	OBJMANUT  int  NOT NULL,
	ALTERSTAMP  int  NULL,
	TIMESTAMP  datetime  NULL
)
go
ALTER TABLE OTPMANUT ADD CONSTRAINT  PK_IDTPMANUT PRIMARY KEY CLUSTERED (IDLOJA ASC, IDTPMANUT  ASC)
go
exec sp_bindefault DF_1, 'OTPMANUT.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OTPMANUT.TIMESTAMP'
go
exec sp_bindefault DF_0, 'OTPMANUT.OBJMANUT'
go
/***** OMAQMANUT ***/
CREATE TABLE [dbo].[OMAQMANUT]
(	IDLOJA int NOT NULL,
	IDMANUT int NOT NULL,
	IDTPMANUT  int  NULL,
	IDMAQUINA  int  NULL,
	IDMANIPULO  int  NULL,
	DTMANUT  datetime  NULL,
	DSCMANUT  varchar(100)  NULL,
	ALTERSTAMP  integer  NULL,
	TIMESTAMP  datetime  NULL
)
go
ALTER TABLE OMAQMANUT ADD CONSTRAINT  PK_IDMANUT PRIMARY KEY CLUSTERED (IDLOJA ASC, IDMANUT  ASC)
go
exec sp_bindefault DF_1, 'OMAQMANUT.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OMAQMANUT.TIMESTAMP'
go
/***** OTPMANIPULO ***/
CREATE TABLE [dbo].[OTPMANIPULO]
(	IDLOJA int  NOT NULL,
	IDTPMANIPULO  int NOT NULL,
	DSCMANIPULO  varchar(10)  NULL, 
	ALTERSTAMP  integer  NULL,
	TIMESTAMP  datetime  NULL
)
go
ALTER TABLE OTPMANIPULO	ADD CONSTRAINT  PK_IDTPMANIPULO PRIMARY KEY CLUSTERED (IDLOJA ASC, IDTPMANIPULO  ASC)
go
exec sp_bindefault DF_1, 'OTPMANIPULO.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OTPMANIPULO.TIMESTAMP'
go
/***** OMANIPULO ***/
CREATE TABLE [dbo].[OMANIPULO]
(	IDLOJA int NOT NULL,
	IDMANIPULO  int NOT NULL,	
	CODMANIPULO  varchar(20)  NULL,
	IDTPMANIPULO  int  NULL,
	ATIVO int  NULL,	
	ALTERSTAMP  integer  NULL,
	TIMESTAMP  datetime  NULL
)
go
ALTER TABLE OMANIPULO ADD CONSTRAINT  PK_IDMANIPULO PRIMARY KEY CLUSTERED (IDLOJA ASC, IDMANIPULO  ASC)
go
exec sp_bindefault DF_1, 'OMANIPULO.ATIVO'
go
exec sp_bindefault DF_1, 'OMANIPULO.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OMANIPULO.TIMESTAMP'
go
/***** OLAMPADA ***/
CREATE TABLE [dbo].[OLAMPADA]
(	IDLOJA int NOT NULL,
	IDLAMP  int  NOT NULL,
	IDMANIPULO  int  NOT NULL,
	ALTERSTAMP  integer  NULL,
	TIMESTAMP  datetime  NULL
)
go
ALTER TABLE OLAMPADA ADD CONSTRAINT PK_IDLAMPADA PRIMARY KEY   NONCLUSTERED (IDLOJA ASC, IDMANIPULO  ASC,IDLAMP  ASC)
go
exec sp_bindefault DF_1, 'OLAMPADA.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OLAMPADA.TIMESTAMP'
go
/***** OMAQDISPAROS ***/
CREATE TABLE [dbo].[OMAQDISPAROS]
(	IDLOJA  int  NOT NULL ,
	IDMAQUINA  int  NOT NULL ,
	IDDISPARO  int  NOT NULL ,		
	IDTPMANIPULO int Null,
    IDMANIPULO int NULL,
	IDLAMP int NULL,
	NUMDISPARO  int  NOT NULL ,	
	QTDDISPARO  int  NOT NULL ,	
	DTDISPARO  datetime NOT NULL ,	
	IDATENDIMENTO  int  NULL ,
	IDSESSAO  int  NULL ,	
	IDTPTRATAMENTO int NULL,
	IDAREA  int  NULL ,
	FLGDELETE  int  NULL ,
	IDLOJAD  int  NULL ,
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NULL 
)
ALTER TABLE OMAQDISPAROS ADD CONSTRAINT  PK_OMAQDISPAROS PRIMARY KEY   NONCLUSTERED (IDLOJA ASC, IDMAQUINA  ASC,IDDISPARO  ASC)
go
exec sp_bindefault DF_0, 'OMAQDISPAROS.FLGDELETE'
go
exec sp_bindefault DF_1, 'OMAQDISPAROS.IDTPMANIPULO'
go
exec sp_bindefault DF_1, 'OMAQDISPAROS.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OMAQDISPAROS.TIMESTAMP'
go
/***** OAREA ***/
CREATE TABLE [dbo].[OAREA](
	[IDLOJA] [int] NOT NULL,
	[IDAREA] [int] NOT NULL,
	[DSCAREA] [varchar](20) NULL,
	[ALTERSTAMP] [int] NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
 CONSTRAINT [PK_AREA] PRIMARY KEY NONCLUSTERED ([IDLOJA] ASC, [IDAREA] ASC) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]) ON [PRIMARY]
GO
exec sp_bindefault DF_1, 'OAREA.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OAREA.TIMESTAMP'
go
/***** OTPSERVICO ***/
CREATE TABLE [dbo].[OTPSERVICO](
	[IDLOJA] [int] NOT NULL,
	[IDTPSERVICO] [int] NOT NULL,
	[DSCSERVICO] [varchar](30) NULL,
	[ALTERSTAMP] [int] NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
 CONSTRAINT [PK_OTPSERVICO] PRIMARY KEY NONCLUSTERED 
([IDLOJA] ASC, 	[IDTPSERVICO] ASC) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY] ) ON [PRIMARY]
GO
exec sp_bindefault DF_1, 'OTPSERVICO.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OTPSERVICO.TIMESTAMP'
go
/***** OTPTRATAMENTO ***/
CREATE TABLE [dbo].[OTPTRATAMENTO](
	[IDLOJA] [int] NOT NULL,
	[IDTPTRATAMENTO] [int] NOT NULL,
	[DSCTRATAMENTO] [varchar](30) NULL,
	[FREQUENCIA] [int] NULL,
	[FLGDISPARO] [int] NULL,
	[ALTERSTAMP] [int] NULL,
	[TIMESTAMP] [datetime] NULL,
 CONSTRAINT [PK_TRATAMENTO] PRIMARY KEY NONCLUSTERED 
 ([IDLOJA] ASC, [IDTPTRATAMENTO] ASC)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]) ON [PRIMARY]
GO
exec sp_bindefault DF_0, 'OTPTRATAMENTO.FLGDISPARO'
go
exec sp_bindefault DF_1, 'OTPTRATAMENTO.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OTPTRATAMENTO.TIMESTAMP'
go
/***** OAREA_TRATAMENTO ***/
CREATE TABLE [dbo].[OAREA_TRATAMENTO]
(	IDLOJA int not null,
    IDAREA  int  NOT NULL,
	IDTPTRATAMENTO  int  NOT NULL,
	IDTPMANIPULO  int  NOT NULL, 
	TEMPOMIN  integer  NULL,
	TEMPOMED  integer  NULL,
	TEMPOMAX  varchar(50)  NULL,
	INDICEH  decimal(3,2)  NULL,
	ALTERSTAMP  integer  NULL,
	TIMESTAMP  datetime  NULL
)
go
ALTER TABLE OAREA_TRATAMENTO ADD CONSTRAINT  PK_AREATRATAMENTO PRIMARY KEY   NONCLUSTERED (IDLOJA ASC, IDAREA  ASC,IDTPTRATAMENTO  ASC,IDTPMANIPULO  ASC)
go
exec sp_bindefault DF_1, 'OAREA_TRATAMENTO.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OAREA_TRATAMENTO.TIMESTAMP'
go
/***** ODIRECAO ***/
CREATE TABLE [dbo].[ODIRECAO](
	[IDLOJA] [int] NOT NULL,
	[IDDIRECAO] [int] NOT NULL,
	[DSCDIRECAO] [varchar](20) NULL,
	[NORDEM] [int] NOT NULL,
	[ALTERSTAMP] [int] NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
 CONSTRAINT [PK_DIRECAO] PRIMARY KEY NONCLUSTERED 
([IDLOJA] ASC,[IDDIRECAO] ASC) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]) ON [PRIMARY]
GO
exec sp_bindefault DF_1, 'ODIRECAO.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'ODIRECAO.TIMESTAMP'
go
/***** OREACAOADV ***/
CREATE TABLE [dbo].[OREACAOADV](
	[IDLOJA] [int] NOT NULL,
	[IDREACAOADV] [int] NOT NULL,
	[DSCREACAOADV] [varchar](25) NULL,
	[ALTERSTAMP] [int] NULL,
	[TIMESTAMP] [datetime] NULL,
 CONSTRAINT [PK_OREACAOADV] PRIMARY KEY NONCLUSTERED 
([IDLOJA] ASC,	[IDREACAOADV] ASC) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]) ON [PRIMARY]
GO
exec sp_bindefault DF_1, 'OREACAOADV.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OREACAOADV.TIMESTAMP'
go
/****************************************/
SET ANSI_PADDING OFF
GO
/****************************************/
INSERT INTO dbo.OTPMAQ (IDLOJA,IDTPMAQ,DSCMAQ,TPNUM,TPMANIPULO,NUMTRATAMENTO,ALTERSTAMP,TIMESTAMP) 
SELECT  L.IDLOJA,T.IDTPMAQ,T.DSCMAQ,T.TPNUM,T.TPMANIPULO,T.NUMTRATAMENTO,T.ALTERSTAMP,T.TIMESTAMP
FROM OTPMAQ1 T, OLOJA L
GO 
INSERT INTO dbo.OSALA_MAQUINA(IDLOJA,IDSALA,IDMAQUINA,DTINICIO,DTFIM,ALTERSTAMP,TIMESTAMP) SELECT 
(SELECT MIN(IDLOJA) FROM OLOJA),IDSALA,IDMAQUINA,DTINICIO,DTFIM,ALTERSTAMP,TIMESTAMP
FROM OSALA_MAQUINA1
GO 
UPDATE OSALA SET IDLOJA=(SELECT MIN(IDLOJA) FROM OLOJA)
GO
INSERT INTO dbo.OMAQUINA (IDLOJA,IDMAQUINA,CODMAQUINA,IDTPMAQ,NREGISTRO,NANVISA,DTOPERACAO,DTFECHAMENTO,DISPAROS,SITMAQUINA,ALTERSTAMP,TIMESTAMP) SELECT 
IDLOJA,IDMAQUINA,CODMAQUINA,IDTPMAQ,NREGISTRO,NANVISA,DTOPERACAO,DTFECHAMENTO,DISPAROS,SITMAQUINA,ALTERSTAMP,TIMESTAMP
FROM OMAQUINA1
GO 
INSERT INTO dbo.OTPMANUT(IDLOJA,IDTPMANUT,DSCMANUT,OBJMANUT,ALTERSTAMP,TIMESTAMP) SELECT 
(SELECT MIN(IDLOJA) FROM OLOJA),IDTPMANUT,DSCMANUT,OBJMANUT,ALTERSTAMP,TIMESTAMP
FROM OTPMANUT1
GO 
INSERT INTO dbo.OMAQMANUT(IDLOJA,IDMANUT,IDTPMANUT,IDMAQUINA,IDMANIPULO,DTMANUT,DSCMANUT,ALTERSTAMP,TIMESTAMP) SELECT 
(SELECT MIN(IDLOJA) FROM OLOJA),IDMANUT,IDTPMANUT,IDMAQUINA,IDMANIPULO,DTMANUT,DSCMANUT,ALTERSTAMP,TIMESTAMP
FROM OMAQMANUT1
GO 
IF NOT EXISTS(SELECT IDTPMANIPULO FROM OTPMANIPULO where IDTPMANIPULO=1) INSERT INTO OTPMANIPULO(IDLOJA,IDTPMANIPULO,DSCMANIPULO) VALUES (1,1,'Pequeno')
go
IF NOT EXISTS(SELECT IDTPMANIPULO FROM OTPMANIPULO where IDTPMANIPULO=2) INSERT INTO OTPMANIPULO(IDLOJA,IDTPMANIPULO,DSCMANIPULO) VALUES (1,2,'Grande')
go
INSERT INTO dbo.OMANIPULO(IDLOJA,IDMANIPULO,CODMANIPULO,IDTPMANIPULO,ATIVO,ALTERSTAMP,TIMESTAMP) SELECT 
(SELECT MIN(IDLOJA) FROM OLOJA),IDMANIPULO,CODMANIPULO,IDTPMANIPULO,ATIVO,ALTERSTAMP,TIMESTAMP
FROM OMANIPULO1
GO 
INSERT INTO dbo.OLAMPADA(IDLOJA,IDLAMP,IDMANIPULO,ALTERSTAMP,TIMESTAMP) SELECT 
(SELECT MIN(IDLOJA) FROM OLOJA),IDLAMP,IDMANIPULO,ALTERSTAMP,TIMESTAMP
FROM OLAMPADA1
GO 
INSERT INTO dbo.OMAQDISPAROS(IDLOJA,IDLOJAD,IDMAQUINA,IDDISPARO,IDTPMANIPULO,IDMANIPULO,IDLAMP,NUMDISPARO,QTDDISPARO,DTDISPARO,IDATENDIMENTO,IDSESSAO,IDTPTRATAMENTO,IDAREA,FLGDELETE,ALTERSTAMP,TIMESTAMP) SELECT 
(SELECT MIN(IDLOJA) FROM OLOJA),(SELECT MIN(IDLOJA) FROM OLOJA), IDMAQUINA,IDDISPARO,IDTPMANIPULO,IDMANIPULO,IDLAMP,NUMDISPARO,QTDDISPARO,DTDISPARO,IDATENDIMENTO,IDSESSAO,IDTPTRATAMENTO,IDAREA,FLGDELETE,ALTERSTAMP,TIMESTAMP
FROM OMAQDISPAROS1
GO
INSERT INTO dbo.OAREA(IDLOJA,IDAREA,DSCAREA,ALTERSTAMP,TIMESTAMP) SELECT 
(SELECT MIN(IDLOJA) FROM OLOJA),IDAREA,DSCAREA,ALTERSTAMP,TIMESTAMP
FROM OAREA1
GO
INSERT INTO dbo.OTPSERVICO(IDLOJA,IDTPSERVICO,DSCSERVICO,ALTERSTAMP,TIMESTAMP) SELECT 
(SELECT MIN(IDLOJA) FROM OLOJA),IDTPSERVICO,DSCSERVICO,ALTERSTAMP,TIMESTAMP
FROM OTPSERVICO1
GO
INSERT INTO dbo.OTPTRATAMENTO(IDLOJA,IDTPTRATAMENTO,DSCTRATAMENTO,FREQUENCIA,FLGDISPARO,ALTERSTAMP,TIMESTAMP) SELECT 
(SELECT MIN(IDLOJA) FROM OLOJA),IDTPTRATAMENTO,DSCTRATAMENTO,FREQUENCIA,1,ALTERSTAMP,TIMESTAMP
FROM OTPTRATAMENTO1
GO
INSERT INTO dbo.OAREA_TRATAMENTO(IDLOJA,IDAREA,IDTPTRATAMENTO,IDTPMANIPULO,TEMPOMIN,TEMPOMED,TEMPOMAX,INDICEH,ALTERSTAMP,TIMESTAMP) SELECT 
(SELECT MIN(IDLOJA) FROM OLOJA),IDAREA,IDTPTRATAMENTO,IDTPMANIPULO,TEMPOMIN,TEMPOMED,TEMPOMAX,INDICEH,ALTERSTAMP,TIMESTAMP
FROM OAREA_TRATAMENTO1
GO
INSERT INTO dbo.ODIRECAO(IDLOJA,IDDIRECAO,DSCDIRECAO,NORDEM,ALTERSTAMP,TIMESTAMP) SELECT 
(SELECT MIN(IDLOJA) FROM OLOJA),IDDIRECAO,DSCDIRECAO,NORDEM,ALTERSTAMP,TIMESTAMP
FROM ODIRECAO1
GO
INSERT INTO dbo.OREACAOADV(IDLOJA,IDREACAOADV,DSCREACAOADV,ALTERSTAMP,TIMESTAMP) SELECT 
(SELECT MIN(IDLOJA) FROM OLOJA),IDREACAOADV,DSCREACAOADV,ALTERSTAMP,TIMESTAMP
FROM OREACAOADV1
GO
/****************************************/
ALTER TABLE [dbo].[OSALA_MAQUINA]  WITH CHECK ADD  CONSTRAINT [FK_SALA_MAQUINA_SALA] FOREIGN KEY([IDLOJA], [IDSALA]) REFERENCES [dbo].[OSALA] ([IDLOJA], [IDSALA]) ON UPDATE CASCADE
GO
ALTER TABLE OMAQUINA  WITH CHECK ADD CONSTRAINT R_127 FOREIGN KEY(IDLOJA,IDTPMAQ) REFERENCES OTPMAQ(IDLOJA,IDTPMAQ) ON DELETE NO ACTION ON UPDATE NO ACTION
go
ALTER TABLE OMANIPULO WITH CHECK ADD CONSTRAINT R_126 FOREIGN KEY(IDLOJA,IDTPMANIPULO) REFERENCES OTPMANIPULO(IDLOJA,IDTPMANIPULO)
GO
ALTER TABLE [dbo].[OSALA_MAQUINA]  WITH CHECK ADD  CONSTRAINT [R_15] FOREIGN KEY([IDLOJA],[IDMAQUINA]) REFERENCES [dbo].[OMAQUINA] ([IDLOJA],[IDMAQUINA])
GO
ALTER TABLE [dbo].[OSALA_MAQUINA] CHECK CONSTRAINT [R_15]
GO
ALTER TABLE OMAQDISPAROS WITH CHECK ADD  CONSTRAINT R_225 FOREIGN KEY(IDLOJA, IDMAQUINA) REFERENCES OMAQUINA(IDLOJA, IDMAQUINA) ON DELETE NO ACTION ON UPDATE NO ACTION
GO
ALTER TABLE [dbo].[OMAQMANUT] WITH CHECK ADD CONSTRAINT [R_132] FOREIGN KEY([IDLOJA], [IDTPMANUT]) REFERENCES [dbo].[OTPMANUT] ([IDLOJA],[IDTPMANUT])
GO
ALTER TABLE [dbo].[OMAQMANUT] CHECK CONSTRAINT [R_132]
GO
ALTER TABLE [dbo].[OMAQMANUT]  WITH CHECK ADD  CONSTRAINT [R_133] FOREIGN KEY([IDLOJA], [IDMAQUINA]) REFERENCES [dbo].[OMAQUINA] ([IDLOJA], [IDMAQUINA])
GO
ALTER TABLE [dbo].[OMAQMANUT] CHECK CONSTRAINT [R_133]
GO
ALTER TABLE [dbo].[OMAQMANUT]  WITH CHECK ADD  CONSTRAINT [R_134] FOREIGN KEY([IDLOJA],[IDMANIPULO]) REFERENCES [dbo].[OMANIPULO] ([IDLOJA],[IDMANIPULO])
GO
ALTER TABLE [dbo].[OMAQMANUT] CHECK CONSTRAINT [R_134]
GO
ALTER TABLE OAREA_TRATAMENTO ADD CONSTRAINT  R_124 FOREIGN KEY (IDLOJA, IDAREA) REFERENCES OAREA(IDLOJA, IDAREA)
go
ALTER TABLE OAREA_TRATAMENTO ADD CONSTRAINT  R_125 FOREIGN KEY (IDLOJA, IDTPTRATAMENTO) REFERENCES OTPTRATAMENTO(IDLOJA, IDTPTRATAMENTO)
go
ALTER TABLE OAREA_TRATAMENTO ADD CONSTRAINT  R_135 FOREIGN KEY (IDLOJA, IDTPMANIPULO) REFERENCES OTPMANIPULO(IDLOJA, IDTPMANIPULO)
go
ALTER TABLE OMAQDISPAROS ADD CONSTRAINT  R_OTPMANIPULO_DISPARO FOREIGN KEY (IDLOJA,IDTPMANIPULO) REFERENCES OTPMANIPULO(IDLOJA, IDTPMANIPULO) ON DELETE NO ACTION ON UPDATE NO ACTION
go
ALTER TABLE OATENDIMENTO ADD CONSTRAINT  R_137 FOREIGN KEY (IDLOJA, IDMANIPULO) REFERENCES OMANIPULO(IDLOJA, IDMANIPULO)
go
ALTER TABLE [dbo].[OLAMPADA]  WITH CHECK ADD  CONSTRAINT [R_129] FOREIGN KEY([IDLOJA], [IDMANIPULO]) REFERENCES [dbo].[OMANIPULO] ([IDLOJA],[IDMANIPULO])
GO
ALTER TABLE [dbo].[OLAMPADA] CHECK CONSTRAINT [R_129]
GO
ALTER TABLE [dbo].[OMAQDISPAROS] ADD CONSTRAINT  R_130 FOREIGN KEY (IDLOJA, IDMANIPULO,IDLAMP) REFERENCES OLAMPADA(IDLOJA, IDMANIPULO,IDLAMP) ON DELETE NO ACTION ON UPDATE NO ACTION
go
ALTER TABLE OMAQDISPAROS ADD CONSTRAINT  R_136 FOREIGN KEY (IDLOJA, IDTPTRATAMENTO) REFERENCES OTPTRATAMENTO(IDLOJA, IDTPTRATAMENTO)
go
ALTER TABLE OMAQDISPAROS WITH NOCHECK ADD  CONSTRAINT R_226 FOREIGN KEY (IDLOJA,IDATENDIMENTO,IDSESSAO) REFERENCES OSESSAO(IDLOJA,IDATENDIMENTO,IDSESSAO)
go
ALTER TABLE [dbo].[OMAQDISPAROS] NOCHECK CONSTRAINT [R_226]
GO
ALTER TABLE OMAQDISPAROS WITH NOCHECK ADD  CONSTRAINT R_230 FOREIGN KEY (IDLOJA,IDAREA) REFERENCES OAREA(IDLOJA, IDAREA)
go
ALTER TABLE [dbo].[OMAQDISPAROS] NOCHECK CONSTRAINT [R_230]
GO
ALTER TABLE [dbo].[OTRATAMENTOCLI]  WITH CHECK ADD  CONSTRAINT [R_172] FOREIGN KEY([IDLOJA],[IDAREA]) REFERENCES [dbo].[OAREA] ([IDLOJA],[IDAREA]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[OTRATAMENTOCLI] CHECK CONSTRAINT [R_172]
GO
ALTER TABLE [dbo].[OSESSAO]  WITH CHECK ADD  CONSTRAINT [R_48] FOREIGN KEY([IDLOJA],[IDAREA]) REFERENCES [dbo].[OAREA] ([IDLOJA],[IDAREA]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[OSESSAO] CHECK CONSTRAINT [R_48]
GO
ALTER TABLE [dbo].[OSERVICOEVT]  WITH CHECK ADD  CONSTRAINT [R_157] FOREIGN KEY([IDLOJA],[IDAREA]) REFERENCES [dbo].[OAREA] ([IDLOJA],[IDAREA]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[OSERVICOEVT] CHECK CONSTRAINT [R_157]
GO
ALTER TABLE [dbo].[OSESSAO]  WITH CHECK ADD  CONSTRAINT [R_170] FOREIGN KEY([IDLOJA], [IDTPSERVICO]) REFERENCES [dbo].[OTPSERVICO] ([IDLOJA], [IDTPSERVICO])
GO
ALTER TABLE [dbo].[OSESSAO] CHECK CONSTRAINT [R_170]
GO
ALTER TABLE [dbo].[OTRATAMENTOCLI]  WITH CHECK ADD  CONSTRAINT [R_176] FOREIGN KEY([IDLOJA],[IDTPTRATAMENTO]) REFERENCES [dbo].[OTPTRATAMENTO] ([IDLOJA],[IDTPTRATAMENTO])
GO
ALTER TABLE [dbo].[OTRATAMENTOCLI] CHECK CONSTRAINT [R_176]
GO
ALTER TABLE [dbo].[OSESSAO]  WITH CHECK ADD  CONSTRAINT [R_171] FOREIGN KEY([IDLOJA], [IDTPTRATAMENTO]) REFERENCES [dbo].[OTPTRATAMENTO] ([IDLOJA], [IDTPTRATAMENTO])
GO
ALTER TABLE [dbo].[OSESSAO] CHECK CONSTRAINT [R_171]
GO
ALTER TABLE [dbo].[OSERVICOEVT]  WITH CHECK ADD  CONSTRAINT [R_175] FOREIGN KEY([IDLOJA],[IDTPTRATAMENTO]) REFERENCES [dbo].[OTPTRATAMENTO] ([IDLOJA],[IDTPTRATAMENTO])
GO
ALTER TABLE [dbo].[OSERVICOEVT] CHECK CONSTRAINT [R_175]
GO
ALTER TABLE [dbo].[OSESSAO]  WITH CHECK ADD  CONSTRAINT [R_47] FOREIGN KEY([IDLOJA], [IDDIRECAO]) REFERENCES [dbo].[ODIRECAO] ([IDLOJA], [IDDIRECAO])
GO
ALTER TABLE [dbo].[OSESSAO] CHECK CONSTRAINT [R_47]
GO
ALTER TABLE [dbo].[OSESSAO_REACAOADV]  WITH CHECK ADD  CONSTRAINT [R_178] FOREIGN KEY([IDLOJA],[IDREACAOADV]) REFERENCES [dbo].[OREACAOADV] ([IDLOJA],[IDREACAOADV])
GO
ALTER TABLE [dbo].[OSESSAO_REACAOADV] CHECK CONSTRAINT [R_178]
GO

/****************************************/
DROP TABLE OTPMAQ1
GO
DROP TABLE OSALA_MAQUINA1
GO
DROP TABLE OMAQUINA1
GO
DROP TABLE OTPMANUT1
GO
DROP TABLE OMAQMANUT1
GO
DROP TABLE OTPMANIPULO1
GO
DROP TABLE OMANIPULO1
GO
DROP TABLE OLAMPADA1
GO
DROP TABLE OMAQDISPAROS1
GO
DROP TABLE OAREA1
GO
DROP TABLE OTPSERVICO1
GO
DROP TABLE OTPTRATAMENTO1
GO
DROP TABLE OAREA_TRATAMENTO1
GO
DROP TABLE ODIRECAO1
GO
DROP TABLE OREACAOADV1
GO
 