--USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='47', ARQATU='Rev47.sql';
/****************************************************************************
****************************************************************************/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_182]') AND parent_object_id = OBJECT_ID(N'[dbo].[SPRODUTO]'))	ALTER TABLE [dbo].[SPRODUTO] DROP CONSTRAINT [R_182]
GO
ALTER TABLE SPRODUTO ADD CONSTRAINT  R_203 FOREIGN KEY (IDLOJA) REFERENCES OLOJA(IDLOJA)
go
ALTER TABLE [dbo].[CVENDA] NOCHECK CONSTRAINT [FK_CVENDA_RFUNC]
GO
ALTER TABLE [dbo].[CBANDC]  WITH CHECK ADD  CONSTRAINT [R_182] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[CBANDC] CHECK CONSTRAINT [R_182]
GO
ALTER TABLE [dbo].[OTPSERVICO]  WITH CHECK ADD  CONSTRAINT [R_183] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[OTPSERVICO] CHECK CONSTRAINT [R_183]
GO
ALTER TABLE [dbo].[OTPTRATAMENTO]  WITH CHECK ADD  CONSTRAINT [R_184] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[OTPTRATAMENTO] CHECK CONSTRAINT [R_184]
GO
ALTER TABLE [dbo].[OAREA]  WITH CHECK ADD  CONSTRAINT [R_185] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[OAREA] CHECK CONSTRAINT [R_185]
GO
ALTER TABLE [dbo].[ODIRECAO]  WITH CHECK ADD  CONSTRAINT [R_186] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[ODIRECAO] CHECK CONSTRAINT [R_186]
GO
ALTER TABLE [dbo].[OEVENTOREC]  WITH CHECK ADD  CONSTRAINT [R_187] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[OEVENTOREC] CHECK CONSTRAINT [R_187]
GO
ALTER TABLE [dbo].[OREACAOADV]  WITH CHECK ADD  CONSTRAINT [R_188] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[OREACAOADV] CHECK CONSTRAINT [R_188]
GO
ALTER TABLE [dbo].[CFORMAPGTO]  WITH CHECK ADD  CONSTRAINT [R_189] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[CFORMAPGTO] CHECK CONSTRAINT [R_189]
GO
ALTER TABLE [dbo].[CCONDPGTO]  WITH CHECK ADD  CONSTRAINT [R_190] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[CCONDPGTO] CHECK CONSTRAINT [R_190]
GO
ALTER TABLE [dbo].[OTRATAMENTO_PROD]  WITH CHECK ADD  CONSTRAINT [R_191] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[OTRATAMENTO_PROD] CHECK CONSTRAINT [R_191]
GO
ALTER TABLE [dbo].[SESTOQUE]  WITH CHECK ADD  CONSTRAINT [R_192] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[SESTOQUE] CHECK CONSTRAINT [R_192]
GO
ALTER TABLE [dbo].[OTPCONHEC]  WITH CHECK ADD  CONSTRAINT [R_193] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[OTPCONHEC] CHECK CONSTRAINT [R_193]
GO
ALTER TABLE [dbo].[FGRUPODESP]  WITH CHECK ADD  CONSTRAINT [R_194] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[FGRUPODESP] CHECK CONSTRAINT [R_194]
GO
ALTER TABLE [dbo].[OTPMAQ]  WITH CHECK ADD  CONSTRAINT [R_195] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[OTPMAQ] CHECK CONSTRAINT [R_195]
GO
ALTER TABLE [dbo].[OTPMANUT]  WITH CHECK ADD  CONSTRAINT [R_196] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[OTPMANUT] CHECK CONSTRAINT [R_196]
GO
ALTER TABLE [dbo].[OTPMANIPULO]  WITH CHECK ADD  CONSTRAINT [R_197] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[OTPMANIPULO] CHECK CONSTRAINT [R_197]
GO
ALTER TABLE [dbo].[OCATTAREFA]  WITH CHECK ADD  CONSTRAINT [R_198] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[OCATTAREFA] CHECK CONSTRAINT [R_198]
GO
ALTER TABLE [dbo].[OTIPOTAREFA]  WITH CHECK ADD  CONSTRAINT [R_199] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[OTIPOTAREFA] CHECK CONSTRAINT [R_199]
GO
ALTER TABLE [dbo].[PMETA]  WITH CHECK ADD  CONSTRAINT [R_200] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[PMETA] CHECK CONSTRAINT [R_200]
GO
ALTER TABLE [dbo].[PPN]  WITH CHECK ADD  CONSTRAINT [R_201] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[PPN] CHECK CONSTRAINT [R_201]
GO
ALTER TABLE [dbo].[PPNITEM]  WITH CHECK ADD  CONSTRAINT [R_149] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[PPNITEM] CHECK CONSTRAINT [R_149]
GO
ALTER TABLE [dbo].[GFERIADO]  WITH CHECK ADD  CONSTRAINT [R_202] FOREIGN KEY([IDLOJA]) REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[GFERIADO] CHECK CONSTRAINT [R_202]
GO
