
/****************************************************************************
****************************************************************************/
--USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='42', ARQATU='Rev42.sql';
/****************************************************************************
****************************************************************************/
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='PARAM' AND C.NAME='IDLOJA') ALTER TABLE PARAM ADD IDLOJA INT NOT NULL DEFAULT 1
GO
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='DADOSPARAM' AND C.NAME='IDLOJA') ALTER TABLE DADOSPARAM ADD IDLOJA INT NOT NULL DEFAULT 1
GO

UPDATE PARAM SET IDLOJA=(SELECT Min(IDLOJA) from OLOJA)
GO
UPDATE DADOSPARAM SET IDLOJA=(SELECT Min(IDLOJA) from OLOJA)
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_DADOSPARAM]') AND parent_object_id = OBJECT_ID(N'[dbo].[DADOSPARAM]')) ALTER TABLE [dbo].[DADOSPARAM] DROP CONSTRAINT [FK_DADOSPARAM]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[PARAM]') AND name = N'PK_PARAM') ALTER TABLE [dbo].[PARAM] DROP CONSTRAINT [PK_PARAM]
GO

ALTER TABLE [dbo].[PARAM] ADD  CONSTRAINT [PK_PARAM] PRIMARY KEY CLUSTERED ([CODSIS] ASC,[IDLOJA] ASC, [CODPARAM] ASC)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DADOSPARAM]  WITH CHECK ADD  CONSTRAINT [FK_DADOSPARAM] FOREIGN KEY([CODSIS],[IDLOJA],[CODPARAM]) REFERENCES [dbo].[PARAM] ([CODSIS], [IDLOJA], [CODPARAM]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[DADOSPARAM] CHECK CONSTRAINT [FK_DADOSPARAM]
GO

EXECUTE sp_rename N'dbo.OSALA', N'OSALA1', 'OBJECT'  
GO 
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_SALA_MAQUINA_SALA]') AND parent_object_id = OBJECT_ID(N'[dbo].[OSALA_MAQUINA]')) ALTER TABLE [dbo].[OSALA_MAQUINA] DROP CONSTRAINT [FK_SALA_MAQUINA_SALA]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_AGENDA_SALA]') AND parent_object_id = OBJECT_ID(N'[dbo].[OAGENDA]')) ALTER TABLE [dbo].[OAGENDA] DROP CONSTRAINT [FK_AGENDA_SALA]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OSALA1]') AND name = N'PK_SALA') ALTER TABLE [dbo].[OSALA1] DROP CONSTRAINT [PK_SALA]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_3]') AND parent_object_id = OBJECT_ID(N'[dbo].[OSALA1]')) ALTER TABLE [dbo].[OSALA1] DROP CONSTRAINT [R_3]
GO

SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[OSALA](
	[IDLOJA] [int] NOT NULL,
	[IDSALA] [int] NOT NULL,	
	[CODSALA] [varchar](5) NULL,
	[DIMENSAO] [varchar](20) NULL,
	[DTOPERACAO] [datetime] NULL,
	[ATIVO] [int] NULL,
	[ALTERSTAMP] [int] NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
 CONSTRAINT [PK_SALA] PRIMARY KEY NONCLUSTERED 
(	[IDLOJA] ASC,[IDSALA] ASC)
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
exec sp_bindefault DF_1, 'OSALA.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OSALA.TIMESTAMP'
go
exec sp_bindefault DF_Now, 'OSALA.DTOPERACAO'
go
SET ANSI_PADDING OFF
GO
INSERT INTO dbo.OSALA (IDSALA,IDLOJA,CODSALA,DIMENSAO,DTOPERACAO,ATIVO) SELECT IDSALA,IDLOJA,CODSALA,DIMENSAO,DTOPERACAO,ATIVO FROM OSALA1
GO 

ALTER TABLE [dbo].[OSALA]  WITH CHECK ADD  CONSTRAINT [R_3] FOREIGN KEY([IDLOJA])
REFERENCES [dbo].[OLOJA] ([IDLOJA])
GO
ALTER TABLE [dbo].[OSALA] CHECK CONSTRAINT [R_3]
GO
ALTER TABLE [dbo].[OSALA_MAQUINA]  WITH CHECK ADD  CONSTRAINT [FK_SALA_MAQUINA_SALA] FOREIGN KEY([IDLOJA], [IDSALA]) REFERENCES [dbo].[OSALA] ([IDLOJA], [IDSALA]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[OSALA_MAQUINA] CHECK CONSTRAINT [FK_SALA_MAQUINA_SALA]
GO

DROP TABLE OSALA1
GO
/*******************************************************/
/*******************************************************/
EXECUTE sp_rename N'dbo.OAGENDA', N'OAGENDA1', 'OBJECT'  
GO 
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_OEVENTOREC_OAGENDA]') AND parent_object_id = OBJECT_ID(N'[dbo].[OEVENTOREC]')) ALTER TABLE [dbo].[OEVENTOREC] DROP CONSTRAINT [FK_OEVENTOREC_OAGENDA]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_OEVENTOAGENDA_OAGENDA]') AND parent_object_id = OBJECT_ID(N'[dbo].[OEVENTOAGENDA]')) ALTER TABLE [dbo].[OEVENTOAGENDA] DROP CONSTRAINT [FK_OEVENTOAGENDA_OAGENDA]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[OAGENDA1]') AND name = N'PK_OAGENDA') ALTER TABLE [dbo].[OAGENDA1] DROP CONSTRAINT [PK_OAGENDA]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_AGENDA_SALA]') AND parent_object_id = OBJECT_ID(N'[dbo].[OAGENDA1]')) ALTER TABLE [dbo].[OAGENDA1] DROP CONSTRAINT [FK_AGENDA_SALA]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_OAGENDA_OLOJA]') AND parent_object_id = OBJECT_ID(N'[dbo].[OAGENDA1]')) ALTER TABLE [dbo].[OAGENDA1] DROP CONSTRAINT [FK_OAGENDA_OLOJA]
GO

SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[OAGENDA](
	[IDLOJA] [int] NOT NULL,
	[IDAGENDA] [int] NOT NULL,
	[IDSALA] [int] NULL,
	[CODAGENDA] [varchar](10) NULL,	
	[ALTERSTAMP] [int] NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
 CONSTRAINT [PK_OAGENDA] PRIMARY KEY CLUSTERED 
(	[IDLOJA]ASC,[IDAGENDA] ASC)
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
exec sp_bindefault DF_1, 'OAGENDA.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OAGENDA.TIMESTAMP'
go
SET ANSI_PADDING OFF
GO
INSERT INTO dbo.OAGENDA (IDLOJA,IDAGENDA,IDSALA,CODAGENDA) SELECT IDLOJA,IDAGENDA,IDSALA,CODAGENDA FROM OAGENDA1
GO 
ALTER TABLE [dbo].[OAGENDA]  WITH CHECK ADD CONSTRAINT [FK_AGENDA_SALA] FOREIGN KEY([IDLOJA], [IDSALA]) REFERENCES [dbo].[OSALA] ([IDLOJA], [IDSALA]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[OAGENDA] CHECK CONSTRAINT [FK_AGENDA_SALA]
GO
ALTER TABLE [dbo].[OEVENTOREC]  WITH CHECK ADD CONSTRAINT [FK_OEVENTOREC_OAGENDA] FOREIGN KEY([IDLOJA], [IDAGENDA]) REFERENCES [dbo].[OAGENDA] ([IDLOJA], [IDAGENDA]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[OEVENTOREC] CHECK CONSTRAINT [FK_OEVENTOREC_OAGENDA]
GO
ALTER TABLE [dbo].[OEVENTOAGENDA]  WITH CHECK ADD  CONSTRAINT [FK_OEVENTOAGENDA_OAGENDA] FOREIGN KEY([IDLOJA],[IDAGENDA]) REFERENCES [dbo].[OAGENDA] ([IDLOJA], [IDAGENDA]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[OEVENTOAGENDA] CHECK CONSTRAINT [FK_OEVENTOAGENDA_OAGENDA]
GO
DROP TABLE OAGENDA1
GO
