--USE G3R;
--SELECT * FROM VERSAOBD
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='48', ARQATU='Rev48.sql';
/****************************************************************************
****************************************************************************/
ALTER TABLE FLAN ALTER COLUMN IDDESP INT NULL
GO
ALTER TABLE FLAN ALTER COLUMN IDSUBDESP INT NULL
GO
--********************************************
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CPROMO]') AND parent_object_id = OBJECT_ID(N'[dbo].[CVENDA]')) ALTER TABLE [dbo].[CVENDA] DROP CONSTRAINT [FK_CPROMO]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[CPROMOCAO]') AND name = N'PK_CPROMOCAO') ALTER TABLE [dbo].[CPROMOCAO] DROP CONSTRAINT [PK_CPROMOCAO]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[CPROMOCAO1]') AND name = N'PK_CPROMOCAO') ALTER TABLE [dbo].[CPROMOCAO1] DROP CONSTRAINT [PK_CPROMOCAO]
GO
EXECUTE sp_rename N'dbo.CPROMOCAO', N'CPROMOCAO1', 'OBJECT'  
GO 
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[CPROMOCAO1]') AND name = N'PK_CPROMOCAO') ALTER TABLE [dbo].[CPROMOCAO1] DROP CONSTRAINT [PK_CPROMOCAO]
GO

CREATE TABLE [dbo].[CPROMOCAO]
(	[IDLOJA]    int NOT NULL,	
	[IDPROMO]    int NOT NULL,	
	[DSCPROMO]	 varchar(30) NULL,
	[ATIVO]		 int NULL,
	[VLDESC]	 decimal(9,2) NULL ,
	[DTVENC]  datetime  NULL ,
	[DTEMISSAO]  datetime  NULL ,
	[NPARCELA]  int  NULL ,	
	[PRAZO]  int  NULL,
	[IDPROD]  int  NULL,
	[QTDPROD]  decimal(9,2) NULL,
	[ALTERSTAMP] int NULL,
	[TIMESTAMP]  datetime NULL,		
 CONSTRAINT [PK_CPROMOCAO] PRIMARY KEY CLUSTERED 
([IDLOJA] ASC, [IDPROMO] ASC)
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]) ON [PRIMARY]
GO

exec sp_bindefault DF_1, 'CPROMOCAO.ATIVO'
go
exec sp_bindefault DF_1, 'CPROMOCAO.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'CPROMOCAO.TIMESTAMP'
go
SET ANSI_PADDING OFF
GO
DROP TABLE CPROMOCAO1
GO
--********************************************
/********************************************/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_138]') AND parent_object_id = OBJECT_ID(N'[dbo].[CCUPOM]')) ALTER TABLE [dbo].[CCUPOM] DROP CONSTRAINT [R_138]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_139]') AND parent_object_id = OBJECT_ID(N'[dbo].[CCUPOM_VENDA]')) ALTER TABLE [dbo].[CCUPOM_VENDA] DROP CONSTRAINT [R_139]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[CCUPOM]') AND name = N'PK_CCUPOM') ALTER TABLE [dbo].[CCUPOM] DROP CONSTRAINT [PK_CCUPOM]
GO
EXECUTE sp_rename N'dbo.CCUPOM', N'CCUPOM1', 'OBJECT'  
GO 
CREATE TABLE [dbo].[CCUPOM]
(	IDLOJA  int NOT NULL,
	IDPROMO  int NOT NULL,	
	IDCUPOM  int NOT NULL,    
	CODCUPOM  varchar(20)  NULL ,
	DTEMISSAO  datetime  NULL ,
	DTVENC  datetime  NULL ,
	VLDESC decimal(9,2) NULL ,
	ATIVO  int  NULL ,
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NULL 
)
go
ALTER TABLE CCUPOM ADD CONSTRAINT  PK_CCUPOM PRIMARY KEY   NONCLUSTERED (IDLOJA ASC, IDPROMO ASC, IDCUPOM  ASC)
go
exec sp_bindefault DF_1, 'CCUPOM.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'CCUPOM.TIMESTAMP'
go
SET ANSI_PADDING OFF
GO
ALTER TABLE CCUPOM	ADD CONSTRAINT  R_138 FOREIGN KEY (IDLOJA, IDPROMO) REFERENCES CPROMOCAO(IDLOJA, IDPROMO) ON DELETE NO ACTION ON UPDATE CASCADE
go
DROP TABLE CCUPOM1
GO
--********************************************
/********************************************/
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_139]') AND parent_object_id = OBJECT_ID(N'[dbo].[CCUPOM_VENDA]')) ALTER TABLE [dbo].[CCUPOM_VENDA] DROP CONSTRAINT [R_139]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_140]') AND parent_object_id = OBJECT_ID(N'[dbo].[CCUPOM_VENDA]')) ALTER TABLE [dbo].[CCUPOM_VENDA] DROP CONSTRAINT [R_140]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[CCUPOM_VENDA]') AND name = N'PK_CCUPOMVENDA') ALTER TABLE [dbo].[CCUPOM_VENDA] DROP CONSTRAINT [PK_CCUPOMVENDA]
GO

EXECUTE sp_rename N'dbo.CCUPOM_VENDA', N'CCUPOM_VENDA1', 'OBJECT'  
GO 

CREATE TABLE [dbo].[CCUPOM_VENDA]
(	IDLOJA  int  NOT NULL ,
	IDPROMO  int  NOT NULL ,
	IDCUPOM  int  NOT NULL ,
	IDVENDA  int  NOT NULL ,
	QTD  int  NULL ,
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NULL 
)
go
ALTER TABLE CCUPOM_VENDA ADD CONSTRAINT  PK_CCUPOMVENDA PRIMARY KEY   NONCLUSTERED (IDLOJA  ASC,IDVENDA  ASC,IDCUPOM  ASC)
go
exec sp_bindefault DF_1, 'CCUPOM_VENDA.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'CCUPOM_VENDA.TIMESTAMP'
go
SET ANSI_PADDING OFF
GO
ALTER TABLE CCUPOM_VENDA ADD CONSTRAINT  R_139 FOREIGN KEY (IDLOJA, IDPROMO, IDCUPOM) REFERENCES CCUPOM(IDLOJA, IDPROMO, IDCUPOM) ON DELETE NO ACTION ON UPDATE CASCADE
go
ALTER TABLE CCUPOM_VENDA ADD CONSTRAINT  R_140 FOREIGN KEY (IDLOJA,IDVENDA) REFERENCES CVENDA(IDLOJA,IDVENDA) ON DELETE NO ACTION ON UPDATE CASCADE
go
DROP TABLE CCUPOM_VENDA1
GO

IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='PARAM' AND C.NAME='ALTERSTAMP') ALTER TABLE [PARAM] ADD ALTERSTAMP INT NULL
GO
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='PARAM' AND C.NAME='TIMESTAMP') ALTER TABLE [PARAM] ADD TIMESTAMP DATETIME NULL
GO
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='PARAM' AND C.NAME='IDLOJA') ALTER TABLE [PARAM] ADD IDPARAM INT NULL
GO

exec sp_bindefault DF_1, 'PARAM.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'PARAM.TIMESTAMP'
go

UPDATE [PARAM] SET ALTERSTAMP=1 WHERE ALTERSTAMP IS Null
GO
UPDATE [PARAM] SET TIMESTAMP=GetDate() WHERE TIMESTAMP IS Null
GO
ALTER TABLE [PARAM] ALTER COLUMN [ALTERSTAMP] INT NOT NULL
GO
ALTER TABLE [PARAM] ALTER COLUMN [TIMESTAMP] DATETIME NOT NULL
GO
DELETE FROM PARAM WHERE IDLOJA=0
GO
