--USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='49', ARQATU='Rev49.sql';
/****************************************************************************
****************************************************************************/

IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[DELETEDROWS]') AND name = N'XPKdboDELETEDROWS') ALTER TABLE [dbo].[DELETEDROWS] DROP CONSTRAINT [XPKdboDELETEDROWS]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[DELETEDROWS]') AND name = N'PK_DELETEDROWS') ALTER TABLE [dbo].[DELETEDROWS] DROP CONSTRAINT [PK_DELETEDROWS]
GO
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[DELETEDROWS1]') AND name = N'PK_DELETEDROWS') ALTER TABLE [dbo].[DELETEDROWS1] DROP CONSTRAINT [PK_DELETEDROWS]
GO

EXECUTE sp_rename N'dbo.DELETEDROWS', N'DELETEDROWS1', 'OBJECT'  
GO 
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[DELETEDROWS](
	[IDDELETED] [int] IDENTITY(1,1) NOT NULL,
	[QUERY] [varchar](max) NULL,
	[SITQUERY] [int] NULL,
	[TAG] [varchar](max) NULL,
	[ALTERSTAMP] [int] NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
 CONSTRAINT [PK_DELETEDROWS] PRIMARY KEY NONCLUSTERED 
([IDDELETED] ASC)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
exec sp_bindefault DF_1, 'DELETEDROWS.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'DELETEDROWS.TIMESTAMP'
go

INSERT INTO dbo.DELETEDROWS(QUERY,SITQUERY) 
SELECT QUERY,SITQUERY
FROM DELETEDROWS1
GO
DROP TABLE DELETEDROWS1
GO
