--USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='58', ARQATU='Rev58.sql';
/****************************************************************************
****************************************************************************/

IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='FFATURA' AND C.NAME='IDVENDAORIGEM')  ALTER TABLE FFATURA ADD IDVENDAORIGEM int NULL
go
IF EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='FFATURA' AND C.NAME='IDVENDAORIGEM')  UPDATE FFATURA SET IDVENDAORIGEM=(SELECT TOP 1 AV.IDVENDA FROM OATENDIMENTO_VENDA AV WHERE AV.IDLOJA=FFATURA.IDLOJA  AND AV.IDATENDIMENTO=FFATURA.IDATENDIMENTO )
go
CREATE TABLE RBANCOHH
(	IDLOJA  int  NOT NULL ,
	IDFUNCIONARIO  int  NOT NULL ,
	DTPONTO  datetime  NOT NULL ,
	HHINI  datetime  NULL ,
	HHFIM  datetime  NULL ,
	HHESPERADO  decimal(5,2)  NULL ,
	HHTRAB  decimal(5,2)  NULL ,
	SALDODIA  decimal(9,2)  NULL ,
	IDMOVHH  int  NOT NULL ,
	HHABONADO  decimal(5,2)  NULL ,
	IDABONO  int  NULL ,
	FLGDIA  int  NULL ,
	HHREFEICAO  int  NULL ,
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NULL 
)
go

ALTER TABLE RBANCOHH ADD CONSTRAINT  PK_RBANCOHH PRIMARY KEY   NONCLUSTERED (IDLOJA  ASC,IDFUNCIONARIO  ASC,IDMOVHH  ASC)
go
exec sp_bindefault DF_1, 'RBANCOHH.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'RBANCOHH.TIMESTAMP'
go
ALTER TABLE RBANCOHH ADD CONSTRAINT  R_220 FOREIGN KEY (IDLOJA,IDFUNCIONARIO) REFERENCES RFUNCIONARIO(IDLOJA,IDFUNCIONARIO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go
