--USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='51', ARQATU='Rev51.sql';
/****************************************************************************
****************************************************************************/
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='OTPTRATAMENTO' AND C.NAME='FLGDISPARO') ALTER TABLE OTPTRATAMENTO ADD FLGDISPARO INT
go
UPDATE OTPTRATAMENTO SET FLGDISPARO=1 WHERE FLGDISPARO IS NULL
GO
exec sp_bindefault DF_0, 'OTPTRATAMENTO.FLGDISPARO'
GO
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='FCCORRENTE' AND C.NAME='IDCOLIGADA') ALTER TABLE [FCCORRENTE] ADD IDCOLIGADA INT NULL
GO
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='RFUNCIONARIO' AND C.NAME='IDCOLIGADA') ALTER TABLE [RFUNCIONARIO] ADD IDCOLIGADA INT NULL
GO
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='OCONTATO' AND C.NAME='IDCOLIGADA') ALTER TABLE [OCONTATO] ADD IDCOLIGADA INT NULL
GO
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='OCLIENTE' AND C.NAME='IDCOLIGADA') ALTER TABLE [OCLIENTE] ADD IDCOLIGADA INT NULL
GO
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='PMETAITEM' AND C.NAME='VLPREV') ALTER TABLE PMETAITEM ADD VLPREV decimal(9,2) NULL 
GO
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='RFUNCIONARIO' AND C.NAME='IDLOJA0') ALTER TABLE [RFUNCIONARIO] DROP COLUMN IDLOJA0
GO
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='OCONTATO' AND C.NAME='IDLOJA0') ALTER TABLE [OCONTATO] DROP COLUMN IDLOJA0
GO
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='OCLIENTE' AND C.NAME='IDLOJA0') ALTER TABLE [OCLIENTE] DROP COLUMN IDLOJA0
GO
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='RFUNCIONARIO' AND C.NAME='CODCOL') ALTER TABLE RFUNCIONARIO ADD CODCOL INT NULL 
GO
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='OCONTATO' AND C.NAME='CODCOL') ALTER TABLE OCONTATO ADD CODCOL INT NULL 
GO
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='OCLIENTE' AND C.NAME='CODCOL') ALTER TABLE OCLIENTE ADD CODCOL INT NULL 
GO
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='FCCORRENTE' AND C.NAME='CODCOL') ALTER TABLE FCCORRENTE ADD CODCOL INT NULL 
GO
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='OLOJA' AND C.NAME='ATIVO') ALTER TABLE OLOJA ADD ATIVO INT NULL 
GO
UPDATE OLOJA SET ATIVO =1
GO
UPDATE RFUNCIONARIO SET CODCOL =0
GO
UPDATE OCONTATO SET CODCOL =0
GO
UPDATE OCLIENTE SET CODCOL =0
GO
UPDATE FCCORRENTE SET CODCOL =0
GO
exec sp_bindefault DF_1, 'OLOJA.ATIVO'
GO
exec sp_bindefault DF_0, 'RFUNCIONARIO.CODCOL'
GO
exec sp_bindefault DF_0, 'OCONTATO.CODCOL'
GO
exec sp_bindefault DF_0, 'OCLIENTE.CODCOL'
GO
exec sp_bindefault DF_0, 'FCCORRENTE.CODCOL'
GO


