--USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='54', ARQATU='Rev54.sql';
/****************************************************************************
****************************************************************************/

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_FLAN_FDESPESA]') AND parent_object_id = OBJECT_ID(N'[dbo].[FLAN]'))
ALTER TABLE [dbo].[FLAN] DROP CONSTRAINT [FK_FLAN_FDESPESA]
GO

ALTER TABLE [dbo].[FLAN]  WITH NOCHECK ADD  CONSTRAINT [FK_FLAN_FDESPESA] FOREIGN KEY([IDLOJA], [IDDESP]) REFERENCES [dbo].[FDESPESA] ([IDLOJA], [IDDESP])ON UPDATE CASCADE
GO

IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='CVENDA' AND C.NAME='IDFATURA') ALTER TABLE [dbo].[CVENDA] ADD [IDFATURA] [int] NULL DEFAULT 0
GO
UPDATE CVENDA SET IDFATURA=0 WHERE IDFATURA IS NULL
GO
UPDATE CVENDA SET IDFATURA=1 WHERE IDLOJA=3 and (VLPGTO - VLTROCO) - (VLVENDA - VLDESC)<0
GO
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='OTPSERVICO' AND C.NAME='ATIVO') ALTER TABLE [dbo].[OTPSERVICO] ADD [ATIVO] [int] NULL DEFAULT 1
GO
UPDATE OTPSERVICO SET ATIVO=1 WHERE ATIVO IS NULL 
GO
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='OTPTRATAMENTO' AND C.NAME='ATIVO') ALTER TABLE [dbo].[OTPTRATAMENTO] ADD [ATIVO] [int] NULL DEFAULT 1
GO
UPDATE OTPTRATAMENTO SET ATIVO=1 WHERE ATIVO IS NULL 
GO
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='OAREA' AND C.NAME='ATIVO') ALTER TABLE [dbo].[OAREA] ADD [ATIVO] [int] NULL DEFAULT 1
GO
UPDATE OAREA SET ATIVO=1 WHERE ATIVO IS NULL 
GO
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='OTPTRATAMENTO' AND C.NAME='COR') ALTER TABLE [dbo].[OTPTRATAMENTO] ADD [COR] [varchar](30) NULL
GO
