--USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='50', ARQATU='Rev50.sql';
/****************************************************************************
****************************************************************************/
CREATE TABLE GSINC
(	IDLOJA  int  NOT NULL ,
	CODMAQ  varchar(50)  NOT NULL ,
	TABELA varchar(50) NOT NULL,
	DTSINC  datetime  NULL ,
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NULL
)
go

ALTER TABLE GSINC ADD CONSTRAINT  PK_GSINC PRIMARY KEY   NONCLUSTERED (IDLOJA  ASC,CODMAQ  ASC, TABELA ASC)
go
exec sp_bindefault DF_1, 'GSINC.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'GSINC.TIMESTAMP'
go
ALTER TABLE GSINC ADD CONSTRAINT  R_204 FOREIGN KEY (IDLOJA) REFERENCES OLOJA(IDLOJA) ON UPDATE CASCADE
go

/****************************************************************************
****************************************************************************/
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[DADOSPARAM]') AND name = N'PK_DADOSPARAM') ALTER TABLE [dbo].[DADOSPARAM] DROP CONSTRAINT [PK_DADOSPARAM]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_DADOSPARAM]') AND parent_object_id = OBJECT_ID(N'[dbo].[DADOSPARAM]')) ALTER TABLE [dbo].[DADOSPARAM] DROP CONSTRAINT [FK_DADOSPARAM]
GO

EXECUTE sp_rename N'dbo.DADOSPARAM', N'DADOSPARAM1', 'OBJECT'  
GO 

SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[DADOSPARAM](
	[CODSIS] [varchar](10) NOT NULL,
	[IDLOJA] [int] NOT NULL,
	[CODPARAM] [varchar](30) NOT NULL,
	[CODDADO] [varchar](50) NOT NULL,		
	[DSCDADO] [varchar](80) NULL,
	[TIPODADO] [varchar](3) NULL,
	[ALTERSTAMP] [int] NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,	
 CONSTRAINT [PK_DADOSPARAM] PRIMARY KEY CLUSTERED 
([CODSIS] ASC,[IDLOJA] ASC,[CODPARAM] ASC,[CODDADO] ASC)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
exec sp_bindefault DF_1, 'DADOSPARAM.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'DADOSPARAM.TIMESTAMP'
go
INSERT INTO dbo.DADOSPARAM (CODSIS,IDLOJA,CODPARAM,CODDADO,TIPODADO) SELECT CODSIS,IDLOJA,CODPARAM,CODDADO,TIPODADO FROM DADOSPARAM1
GO 
ALTER TABLE [dbo].[DADOSPARAM]  WITH CHECK ADD  CONSTRAINT [FK_DADOSPARAM] FOREIGN KEY([CODSIS], [IDLOJA], [CODPARAM]) REFERENCES [dbo].[PARAM] ([CODSIS], [IDLOJA], [CODPARAM]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[DADOSPARAM] CHECK CONSTRAINT [FK_DADOSPARAM]
GO

DROP TABLE DADOSPARAM1
GO
