--USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='56', ARQATU='Rev56.sql';
/****************************************************************************
****************************************************************************/

IF EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='CPROMOCAO' AND C.NAME='PRAZO')  ALTER TABLE CPROMOCAO DROP COLUMN PRAZO
go
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='CPROMOCAO' AND C.NAME='DTINIV')  ALTER TABLE CPROMOCAO ADD DTINIV datetime NULL
go
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='CPROMOCAO' AND C.NAME='DTFIMV') ALTER TABLE CPROMOCAO ADD DTFIMV datetime NULL
go
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='CPROMOCAO' AND C.NAME='VLTOTAL') ALTER TABLE CPROMOCAO ADD VLTOTAL decimal(9,2) NULL
go
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='CPROMOCAO' AND C.NAME='VALOR') ALTER TABLE CPROMOCAO ADD VALOR decimal(9,2) NULL
go
IF EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='CPROMOCAO' AND C.NAME='SERVIN')  ALTER TABLE CPROMOCAO ALTER COLUMN SERVIN varchar(max) Null
go
IF EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='CPROMOCAO' AND C.NAME='TRATIN')  ALTER TABLE CPROMOCAO ALTER COLUMN TRATIN varchar(max) Null
go
IF EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='CPROMOCAO' AND C.NAME='AREAIN')  ALTER TABLE CPROMOCAO ALTER COLUMN AREAIN varchar(max) Null
go
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='CITENSVENDA' AND C.NAME='IDPACOTE')  ALTER TABLE CITENSVENDA ADD IDPACOTE int NULL
go

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_205]') AND parent_object_id = OBJECT_ID(N'[dbo].[CPACOTE]')) ALTER TABLE [dbo].[CPACOTE] DROP CONSTRAINT [R_205]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_206]') AND parent_object_id = OBJECT_ID(N'[dbo].[CPACOTE]')) ALTER TABLE [dbo].[CPACOTE] DROP CONSTRAINT [R_206]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_213]') AND parent_object_id = OBJECT_ID(N'[dbo].[CPACOTE]')) ALTER TABLE [dbo].[CPACOTE] DROP CONSTRAINT [R_213]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CPACOTE]') AND type in (N'U')) DROP TABLE [dbo].[CPACOTE]
GO
CREATE TABLE CPACOTE
(	IDLOJA  int  NOT NULL ,
	IDVENDA  int  NOT NULL,
	IDPACOTE  int  NOT NULL ,
	DSCPACOTE varchar(30)  NULL ,
	IDCLIENTE  int  NULL ,
	IDPROMO  int  NULL ,
	DTEMISSAO  datetime  NULL ,
	VALOR  decimal(9,2)  NULL ,
	VLDESC  decimal(9,2)  NULL ,	
	VLTOTAL  decimal(9,2)  NULL ,	
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NULL)
go

ALTER TABLE CPACOTE	ADD CONSTRAINT  PK_CPACOTE PRIMARY KEY   NONCLUSTERED (IDLOJA  ASC,IDVENDA  ASC,IDPACOTE  ASC)
go
exec sp_bindefault DF_1, 'CPACOTE.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'CPACOTE.TIMESTAMP'
go
ALTER TABLE CPACOTE	ADD CONSTRAINT  R_205 FOREIGN KEY (IDLOJA,IDCLIENTE) REFERENCES OCLIENTE(IDLOJA,IDCLIENTE)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
go
ALTER TABLE CPACOTE	ADD CONSTRAINT  R_214 FOREIGN KEY (IDLOJA,IDPROMO) REFERENCES CPROMOCAO(IDLOJA,IDPROMO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE CPACOTE	ADD CONSTRAINT  R_213 FOREIGN KEY (IDLOJA,IDVENDA) REFERENCES CVENDA(IDLOJA,IDVENDA)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
go
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_211]') AND parent_object_id = OBJECT_ID(N'[dbo].[CPROMO_PROD]')) ALTER TABLE [dbo].[CPROMO_PROD] DROP CONSTRAINT [R_211]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CPROMO_PROD]') AND type in (N'U')) DROP TABLE [dbo].[CPROMO_PROD]
GO
CREATE TABLE CPROMO_PROD
(	IDLOJA  int  NOT NULL ,
	IDPROMO  int  NOT NULL ,
	IDPROD  int  NOT NULL ,
	QTDPROD  decimal(9,2)  NULL ,
	NMPROD  varchar(20)  NULL ,
	UNIDCONTROLE  varchar(5)  NULL ,
	VLUNIT  decimal(9,2)  NULL ,
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NULL 
)
go

ALTER TABLE CPROMO_PROD
	ADD CONSTRAINT  PK_CPROMOPROD PRIMARY KEY   NONCLUSTERED (IDLOJA  ASC,IDPROMO  ASC,IDPROD  ASC)
go
exec sp_bindefault DF_1, 'CPROMO_PROD.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'CPROMO_PROD.TIMESTAMP'
go
ALTER TABLE CPROMO_PROD
	ADD CONSTRAINT  R_211 FOREIGN KEY (IDLOJA,IDPROMO) REFERENCES CPROMOCAO(IDLOJA,IDPROMO)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
go
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[R_212]') AND parent_object_id = OBJECT_ID(N'[dbo].[CPROMOCAO]')) ALTER TABLE [dbo].[CPROMOCAO] DROP CONSTRAINT [R_212]
GO
ALTER TABLE CPROMOCAO	ADD CONSTRAINT  R_212 FOREIGN KEY (IDLOJA) REFERENCES OLOJA(IDLOJA)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
go
