--USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='59', ARQATU='Rev59.sql';
/****************************************************************************
****************************************************************************/

IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[CPROMO_PROD]') AND name = N'PK_CPROMOPROD') ALTER TABLE [dbo].[CPROMO_PROD] DROP CONSTRAINT [PK_CPROMOPROD]
GO
ALTER TABLE CPROMO_PROD ALTER COLUMN IDPROD DECIMAL(10,0) NOT NULL
GO
ALTER TABLE [dbo].[CPROMO_PROD] ADD  CONSTRAINT [PK_CPROMOPROD] PRIMARY KEY NONCLUSTERED ([IDLOJA] ASC,	[IDPROMO] ASC,	[IDPROD] ASC)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
ALTER TABLE CPROMO_PROD	ADD CONSTRAINT  R_222 FOREIGN KEY (IDLOJA,IDPROD) REFERENCES SPRODUTO(IDLOJA,IDPROD)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

