--USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='57', ARQATU='Rev57.sql';
/****************************************************************************
****************************************************************************/

IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='CVENDA' AND C.NAME='CODVENDA')  ALTER TABLE CVENDA ADD CODVENDA int NULL
go
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='CITENSVENDA' AND C.NAME='VLDESC')  ALTER TABLE CITENSVENDA ADD VLDESC decimal(9,2) NULL
go
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='CITENSVENDA' AND C.NAME='DSCDESC')  ALTER TABLE CITENSVENDA ADD DSCDESC varchar(30) NULL
go
UPDATE CITENSVENDA SET IDPACOTE=0 WHERE IDPACOTE IS NULL
GO
UPDATE CITENSVENDA SET VLDESC = 0 WHERE VLDESC IS NULL
GO
UPDATE CITENSVENDA SET DSCDESC='' WHERE DSCDESC IS NULL
GO