--USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='68', ARQATU='Rev68.sql';
/****************************************************************************
****************************************************************************/
IF EXISTS (SELECT * FROM OTIPOTAREFA Where IDTPTAREFA=1 And DSCTPTAREFA='Confirmar Agenda')
 begin
	UPDATE OTIPOTAREFA SET DSCTPTAREFA='Enviar Boas Vindas', DIFHORA=24, ALTERSTAMP=1, TIMESTAMP=GETDATE() where IDTPTAREFA=1
	UPDATE OTIPOTAREFA SET DSCTPTAREFA='Confirmar Agenda', DIFHORA=-24, ALTERSTAMP=1, TIMESTAMP=GETDATE()  where IDTPTAREFA=2
	UPDATE OTIPOTAREFA SET DSCTPTAREFA='Enviar e-Mail de Orientação', DIFHORA=-120, ALTERSTAMP=1, TIMESTAMP=GETDATE()  where IDTPTAREFA=3
	UPDATE OTIPOTAREFA SET DSCTPTAREFA='Verificar Avaliação' , DIFHORA=24, ALTERSTAMP=1, TIMESTAMP=GETDATE()  where IDTPTAREFA=4
	UPDATE OTIPOTAREFA SET DSCTPTAREFA='Verificar Cancelamento/Falta de Sessão' , DIFHORA=24, ALTERSTAMP=1, TIMESTAMP=GETDATE()  where IDTPTAREFA=5
	UPDATE OTIPOTAREFA SET DSCTPTAREFA='Verificar Sessão não Marcada' , DIFHORA=600, ALTERSTAMP=1, TIMESTAMP=GETDATE()  where IDTPTAREFA=6			
	IF NOT EXISTS(SELECT * FROM OTAREFAEVT Where IDTPTAREFA=6 ) 
	  begin
	     UPDATE OTAREFAEVT SET IDTPTAREFA=IDTPTAREFA+1
	  end   
 end
go
IF NOT EXISTS(SELECT * FROM OTIPOTAREFA Where IDTPTAREFA=6 ) INSERT INTO OTIPOTAREFA (IDLOJA, IDTPTAREFA, DSCTPTAREFA, ATIVO,DIFHORA) Select distinct IDLOJA, 6, 'Verificar Sessão não Marcada',1, 600  from OTAREFAevt;

