--USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='62', ARQATU='Rev62.sql';
/****************************************************************************
****************************************************************************/

CREATE TABLE OTPTRATATR
(	IDLOJA  int  NOT NULL ,
	IDTPTRATAMENTO  int  NOT NULL ,
	IDATR  int  NOT NULL ,
	DSCATR  varchar(20)  NULL ,
	TPATR  char(1)  NULL ,
	VLLISTA  text  NULL ,
	VLPADRAO  varchar(20)  NULL ,
	ATIVO  int  NULL, 
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NULL 
)
go

ALTER TABLE OTPTRATATR	ADD CONSTRAINT  PK_OTPTRATATR PRIMARY KEY NONCLUSTERED (IDLOJA  ASC,IDTPTRATAMENTO  ASC,IDATR  ASC)
go

exec sp_bindefault DF_1, 'OTPTRATATR.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OTPTRATATR.TIMESTAMP'
go
exec sp_bindefault DF_1, 'OTPTRATATR.ATIVO'
go
exec sp_bindefault DF_N, 'OTPTRATATR.TPATR'
go
ALTER TABLE OTPTRATATR
	ADD CONSTRAINT  R_224 FOREIGN KEY (IDLOJA,IDTPTRATAMENTO) REFERENCES OTPTRATAMENTO(IDLOJA,IDTPTRATAMENTO)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
go

CREATE TABLE OSESSAO_ATR
(	IDLOJA  int  NOT NULL ,
	IDTPTRATAMENTO  int  NOT NULL ,
	IDATR  int  NOT NULL ,
	IDATENDIMENTO  int  NOT NULL ,
	IDSESSAO  int  NOT NULL ,
	VALOR  varchar(20)  NULL ,
	ALTERSTAMP  integer  NULL ,
	TIMESTAMP  datetime  NULL 
)
go
ALTER TABLE OSESSAO_ATR
	ADD CONSTRAINT  PK_OSESSAO_ATR PRIMARY KEY   NONCLUSTERED (IDLOJA  ASC,IDATENDIMENTO  ASC,IDSESSAO  ASC,IDTPTRATAMENTO  ASC,IDATR  ASC)
go
exec sp_bindefault DF_1, 'OSESSAO_ATR.ALTERSTAMP'
go
exec sp_bindefault DF_Now, 'OSESSAO_ATR.TIMESTAMP'
go
ALTER TABLE OSESSAO_ATR
	ADD CONSTRAINT  R_236 FOREIGN KEY (IDLOJA,IDTPTRATAMENTO,IDATR) REFERENCES OTPTRATATR(IDLOJA,IDTPTRATAMENTO,IDATR)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
go
ALTER TABLE OSESSAO_ATR
	ADD CONSTRAINT  R_237 FOREIGN KEY (IDLOJA,IDATENDIMENTO,IDSESSAO) REFERENCES OSESSAO(IDLOJA,IDATENDIMENTO,IDSESSAO)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
go
Insert Into OTPTRATATR (IDLOJA, IDTPTRATAMENTO, IDATR, DSCATR, TPATR, VLLISTA, VLPADRAO, ATIVO)
SELECT L.IDLOJA, T.IDTPTRATAMENTO, 1 [IDATR], 'Direção' [DSCATR], 'N' [TPATR], 'Select IDDIRECAO, DSCDIRECAO From ODIRECAO' [VLLISTA], '1' [VLPADRAO], 1 [ATIVO]
FROM OLOJA L 
JOIN OTPTRATAMENTO T ON L.IDLOJA=T.IDLOJA
WHERE IDTPTRATAMENTO <5
go
Insert Into OTPTRATATR (IDLOJA, IDTPTRATAMENTO, IDATR, DSCATR, TPATR, VLLISTA, VLPADRAO, ATIVO)
SELECT L.IDLOJA, T.IDTPTRATAMENTO, 2 [IDATR], 'Fototipo' [DSCATR], 'N' [TPATR], 'Select FOTOTIPO, FOTOTIPO, PELE From OFOTOTIPO' [VLLISTA], '' [VLPADRAO], 1 [ATIVO]
FROM OLOJA L 
JOIN OTPTRATAMENTO T ON L.IDLOJA=T.IDLOJA
WHERE IDTPTRATAMENTO <5
GO
Insert Into OTPTRATATR (IDLOJA, IDTPTRATAMENTO, IDATR, DSCATR, TPATR, VLLISTA, VLPADRAO, ATIVO)
SELECT L.IDLOJA, T.IDTPTRATAMENTO, 3 [IDATR], 'Potência' [DSCATR], 'N' [TPATR], '' [VLLISTA], '' [VLPADRAO], 1 [ATIVO]
FROM OLOJA L 
JOIN OTPTRATAMENTO T ON L.IDLOJA=T.IDLOJA
WHERE IDTPTRATAMENTO <5
GO
Insert Into OTPTRATATR (IDLOJA, IDTPTRATAMENTO, IDATR, DSCATR, TPATR, VLLISTA, VLPADRAO, ATIVO)
SELECT L.IDLOJA, T.IDTPTRATAMENTO, 4 [IDATR], 'Disparo' [DSCATR], 'N' [TPATR], '' [VLLISTA], '' [VLPADRAO], 1 [ATIVO]
FROM OLOJA L 
JOIN OTPTRATAMENTO T ON L.IDLOJA=T.IDLOJA
WHERE IDTPTRATAMENTO <5
GO
Insert Into OTPTRATATR (IDLOJA, IDTPTRATAMENTO, IDATR, DSCATR, TPATR, VLLISTA, VLPADRAO, ATIVO)
SELECT L.IDLOJA, T.IDTPTRATAMENTO, 5 [IDATR], 'Tempo' [DSCATR], 'N' [TPATR], '' [VLLISTA], '' [VLPADRAO], 1 [ATIVO]
FROM OLOJA L 
JOIN OTPTRATAMENTO T ON L.IDLOJA=T.IDLOJA
WHERE IDTPTRATAMENTO <5
GO



