--USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='61', ARQATU='Rev61.sql';
/****************************************************************************
****************************************************************************/


IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='RBATIDA' AND C.NAME='IDMOVHH')  ALTER TABLE RBATIDA ADD IDMOVHH int NULL
go
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='RBATIDA' AND C.NAME='FLGMANUAL')  ALTER TABLE RBATIDA ADD FLGMANUAL int NULL
go
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='RBATIDA' AND C.NAME='OFOTO')  ALTER TABLE RBATIDA ADD OFOTO	binary NULL
go
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='RBANCOHH' AND C.NAME='ACUMULADO')  ALTER TABLE RBANCOHH ADD ACUMULADO decimal(9,2) NULL
go
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='RBANCOHH' AND C.NAME='FLGFALTA')  ALTER TABLE RBANCOHH ADD FLGFALTA int NULL
go
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='RBANCOHH' AND C.NAME='OBS')  ALTER TABLE RBANCOHH ADD OBS varchar(100) NULL
go
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='RBANCOHH' AND C.NAME='FLGZERASALDO')  ALTER TABLE RBANCOHH ADD FLGZERASALDO int NULL
go
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='RBANCOHH' AND C.NAME='ACUMULADO')  ALTER TABLE RBANCOHH ADD ACUMULADO decimal(9,2)
go
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='RFUNCIONARIO' AND C.NAME='DIAFOLGA')  ALTER TABLE RFUNCIONARIO ADD DIAFOLGA int NULL
go
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='OTPTRATAMENTO' AND C.NAME='FLGAREA')  ALTER TABLE OTPTRATAMENTO ADD FLGAREA int NULL
go
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='OTPTRATAMENTO' AND C.NAME='FLGAVALIACAO')  ALTER TABLE OTPTRATAMENTO ADD FLGAVALIACAO int NULL
go
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='OTPTRATAMENTO' AND C.NAME='FLGSESSAO')  ALTER TABLE OTPTRATAMENTO ADD FLGSESSAO int NULL
go
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='OEVENTOAGENDA' AND C.NAME='IDSALA')  ALTER TABLE OEVENTOAGENDA ADD IDSALA int NULL
go
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='OEVENTOAGENDA' AND C.NAME='FLGAVALIACAO')  ALTER TABLE OEVENTOAGENDA ADD FLGAVALIACAO int NULL
go
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='RFUNCIONARIO' AND C.NAME='FLGVENDA')  ALTER TABLE RFUNCIONARIO ADD FLGVENDA int NULL
go
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='CVENDA' AND C.NAME='OBS')  ALTER TABLE CVENDA ADD OBS ntext NULL
go

exec sp_bindefault DF_0, 'OEVENTOAGENDA.FLGAVALIACAO'
go
exec sp_bindefault DF_0, 'OTPTRATAMENTO.FLGAREA'
go
exec sp_bindefault DF_0, 'OTPTRATAMENTO.FLGAVALIACAO'
go
exec sp_bindefault DF_1, 'OTPTRATAMENTO.FLGSESSAO'
go
exec sp_bindefault DF_0, 'RBANCOHH.FLGFALTA'
go
exec sp_bindefault DF_0, 'RBANCOHH.FLGZERASALDO'
go
exec sp_bindefault DF_0, 'RBATIDA.FLGMANUAL'
go
exec sp_bindefault DF_0, 'RFUNCIONARIO.DIAFOLGA'
go
exec sp_bindefault DF_0, 'RFUNCIONARIO.FLGCERTIFICADO'
go
exec sp_bindefault DF_0, 'RFUNCIONARIO.FLGVENDA'
go

Update RFUNCIONARIO SET FLGVENDA=1 where FLGVENDA is Null
Go

ALTER TABLE RBATIDA
	ADD CONSTRAINT  R_159 FOREIGN KEY (IDLOJA,IDFUNCIONARIO) REFERENCES RFUNCIONARIO(IDLOJA,IDFUNCIONARIO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go
Update RBATIDA Set FLGMANUAL=0 Where FLGMANUAL is Null
go
Update RFUNCIONARIO Set DIAFOLGA=0 Where DIAFOLGA is Null
go
Update RBANCOHH Set FLGFALTA=0 Where FLGFALTA is Null
go
Update RBANCOHH Set FLGZERASALDO=0 Where FLGZERASALDO is Null
go
Update OTPTRATAMENTO Set FLGAREA=0 Where FLGAREA is Null
go
Update OTPTRATAMENTO Set FLGAREA=1 Where IDTPTRATAMENTO<=4
go
Update OTPTRATAMENTO Set FLGAVALIACAO=0 Where FLGAVALIACAO is Null
go
Update OTPTRATAMENTO Set FLGSESSAO=1 Where FLGSESSAO=1 is Null
go
Update OTPTRATAMENTO Set FLGAVALIACAO=1 Where IDTPTRATAMENTO<=4
go

ALTER TABLE OSALA ALTER COLUMN CODSALA VARCHAR(10)
GO
