--USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='60', ARQATU='Rev60.sql';
/****************************************************************************
****************************************************************************/

IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='EMPRESA' AND C.NAME='ATIVO')  ALTER TABLE EMPRESA ADD ATIVO int NULL
go
exec sp_bindefault DF_1, 'EMPRESA.ATIVO'
go
Update EMPRESA Set ATIVO=1 Where ATIVO is Null
go
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='CPGTOSVENDA' AND C.NAME='VLTXSERV')  ALTER TABLE CPGTOSVENDA ADD VLTXSERV decimal(9,2) NULL
go
exec sp_bindefault DF_0, 'CPGTOSVENDA.VLTXSERV'
go
Update CPGTOSVENDA Set VLTXSERV=0 Where VLTXSERV is Null
go
if Exists(SELECT TOP 1 CFORMAPGTO.TXSERV FROM CFORMAPGTO WHERE CFORMAPGTO.IDFORMAPGTO=2 AND Not CFORMAPGTO.TXSERV Is Null)
Update CPGTOSVENDA 
Set CPGTOSVENDA.VLTXSERV=CPGTOSVENDA.VLPGTO*(
			SELECT TOP 1 CFORMAPGTO.TXSERV 
			FROM CFORMAPGTO 
			WHERE CFORMAPGTO.IDFORMAPGTO=2 
			AND Not CFORMAPGTO.TXSERV Is Null) 
Where CPGTOSVENDA.IDFORMAPGTO=2
go
if  Exists(SELECT TOP 1 CFORMAPGTO.TXSERV FROM CFORMAPGTO WHERE CFORMAPGTO.IDFORMAPGTO=3 AND Not CFORMAPGTO.TXSERV Is Null)
Update CPGTOSVENDA Set CPGTOSVENDA.VLTXSERV=CPGTOSVENDA.VLPGTO*(
			SELECT TOP 1 CFORMAPGTO.TXSERV 
			FROM CFORMAPGTO 
			WHERE CFORMAPGTO.IDFORMAPGTO=3 
			AND Not CFORMAPGTO.TXSERV Is Null) 
Where CPGTOSVENDA.IDFORMAPGTO=3
go


select IsNull(SELECT TOP 1 CFORMAPGTO.TXSERV 
			FROM CFORMAPGTO 
			WHERE CFORMAPGTO.IDFORMAPGTO=2 
			AND Not CFORMAPGTO.TXSERV Is Null
			AND  CFORMAPGTO.TXSERV >20
			,0)