--USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='71', ARQATU='Rev71.sql';
/****************************************************************************
****************************************************************************/
IF NOT EXISTS (SELECT * FROM OAREA Where IDAREA=0 And IDLOJA=(Select Top 1 IDLOJA From OLOJA Order By IDLOJA)) Insert into OAREA (IDLOJA, IDAREA, ATIVO, DSCAREA) Select Top 1 IDLOJA, 0, 0,'--' From OLOJA Order By IDLOJA;
IF NOT EXISTS (SELECT * FROM OTPTRATAMENTO Where IDTPTRATAMENTO=0 And IDLOJA=(Select Top 1 IDLOJA From OLOJA Order By IDLOJA)) Insert into OTPTRATAMENTO (IDLOJA, IDTPTRATAMENTO, FREQUENCIA, ATIVO, FLGAREA, FLGAVALIACAO, PESOCOMISSAO, FLGSESSAO, DSCTRATAMENTO) Select Top 1 IDLOJA, 0,  0, 0, 0, 0, 0, 0,'Avaliação' From OLOJA Order By IDLOJA;
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='OCLIENTE' AND C.NAME='IDFUNC')  ALTER TABLE OCLIENTE ADD IDFUNC int NULL;

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_EVENTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[OTAREFAEVT]'))
ALTER TABLE [dbo].[OTAREFAEVT] DROP CONSTRAINT [FK_EVENTO];

ALTER TABLE [dbo].[OTAREFAEVT]  WITH NOCHECK ADD  CONSTRAINT [FK_EVENTO] FOREIGN KEY([IDLOJA], [IDEVENTO])
REFERENCES [dbo].[OEVENTOAGENDA] ([IDLOJA], [IDEVENTO]);

ALTER TABLE [dbo].[OTAREFAEVT] NOCHECK CONSTRAINT [FK_EVENTO];

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CITENSVENDA_CVENDA]') AND parent_object_id = OBJECT_ID(N'[dbo].[CITENSVENDA]'))
ALTER TABLE [dbo].[CITENSVENDA] DROP CONSTRAINT [FK_CITENSVENDA_CVENDA];

ALTER TABLE [dbo].[CITENSVENDA]  WITH CHECK ADD  CONSTRAINT [FK_CITENSVENDA_CVENDA] FOREIGN KEY([IDLOJA], [IDVENDA])
REFERENCES [dbo].[CVENDA] ([IDLOJA], [IDVENDA])
ON UPDATE CASCADE;

ALTER TABLE [dbo].[CITENSVENDA] CHECK CONSTRAINT [FK_CITENSVENDA_CVENDA];

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_CPGTOSVENDA_CVENDA]') AND parent_object_id = OBJECT_ID(N'[dbo].[CPGTOSVENDA]'))
ALTER TABLE [dbo].[CPGTOSVENDA] DROP CONSTRAINT [FK_CPGTOSVENDA_CVENDA];

ALTER TABLE [dbo].[CPGTOSVENDA]  WITH CHECK ADD  CONSTRAINT [FK_CPGTOSVENDA_CVENDA] FOREIGN KEY([IDLOJA], [IDVENDA])
REFERENCES [dbo].[CVENDA] ([IDLOJA], [IDVENDA])
ON UPDATE CASCADE;

ALTER TABLE [dbo].[CPGTOSVENDA] CHECK CONSTRAINT [FK_CPGTOSVENDA_CVENDA];
