--USE G3R;

if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='76', ARQATU='Rev76.sql';

IF EXISTS (SELECT * FROM PARAM WHERE CODSIS='P3R' AND CODPARAM='MailUID')  
	UPDATE PARAM SET VLPARAM='sistemap3r@classeaconsultoria.com.br'
	, DSCPARAM= 'Conta de Envio do Sistema'
	WHERE CODSIS='P3R' AND CODPARAM='MailUID'  
go
IF EXISTS (SELECT * FROM PARAM WHERE CODSIS='P3R' AND CODPARAM='MailPWD')  
	UPDATE PARAM SET VLPARAM='044A475559574504040905'
	, DSCPARAM= 'Senha da Conta de Envio'
	WHERE CODSIS='P3R' AND CODPARAM='MailPWD'  
go
IF EXISTS (SELECT * FROM PARAM WHERE CODSIS='P3R' AND CODPARAM='POP3Host')  
	UPDATE PARAM SET VLPARAM='mail.classeaconsultoria.com.br'
	, DSCPARAM= 'Servidor POP'
	WHERE CODSIS='P3R' AND CODPARAM='POP3Host'  
go
IF EXISTS (SELECT * FROM PARAM WHERE CODSIS='P3R' AND CODPARAM='SMTPHost')  
	UPDATE PARAM SET VLPARAM='mail.classeaconsultoria.com.br'
	, DSCPARAM= 'Servidor SMTP'
	WHERE CODSIS='P3R' AND CODPARAM='SMTPHost'  
go
IF EXISTS (SELECT * FROM PARAM WHERE CODSIS='P3R' AND CODPARAM='SMTPPort')  
	UPDATE PARAM SET VLPARAM='587'
	, DSCPARAM= 'Porta SMTP'
	WHERE CODSIS='P3R' AND CODPARAM='SMTPPort'  
go
IF EXISTS (SELECT * FROM PARAM WHERE CODSIS='P3R' AND CODPARAM='SSL')  
	UPDATE PARAM SET VLPARAM='0'
	, DSCPARAM= 'Criptografia SSL'
	WHERE CODSIS='P3R' AND CODPARAM='SSL'  
go
IF EXISTS (SELECT * FROM PARAM WHERE CODSIS='P3R' AND CODPARAM='UseAuthentication')  
	UPDATE PARAM SET VLPARAM='1'
	, DSCPARAM= 'Servidor Requer Autenticação'
	WHERE CODSIS='P3R' AND CODPARAM='UseAuthentication'  
go
IF EXISTS (SELECT * FROM PARAM WHERE CODSIS='P3R' AND CODPARAM='UsePopAuthentication')  
	UPDATE PARAM SET VLPARAM='1'
	, DSCPARAM= 'Autenticação POP'
	WHERE CODSIS='P3R' AND CODPARAM='UsePopAuthentication'  
go


--select * from PARAM where idloja=3 codparam in ('MailPWD')
--select * from oloja
