--USE G3R;
if NOt Exists(Select * From VERSAOBD Where IDBD=1) INSERT INTO VERSAOBD(IDBD, DSCBD, VSBD, ATUBD, DTATU, ARQATU) VALUES (1, 'Banco Dpil', '1.0', '0', GetDate(), '');
UPDATE VERSAOBD SET VSBD='1.0', DTATU=GetDate(), ATUBD='72', ARQATU='Rev72.sql';
/****************************************************************************
****************************************************************************/
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='CVENDA' AND C.NAME='VLACRESC')  ALTER TABLE CVENDA ADD VLACRESC decimal(9,2) NULL
go
IF NOT EXISTS (SELECT * FROM sys.COLUMNS C JOIN  sys.OBJECTS O ON C.OBJECT_ID=O.OBJECT_ID WHERE O.NAME='CVENDA' AND C.NAME='VLITENS')  ALTER TABLE CVENDA ADD VLITENS decimal(9,2) NULL
go
Update CVENDA Set VLACRESC=0 where VLACRESC is null
go
Update CVENDA Set VLITENS=0 where VLITENS is null
go
Update CVENDA
Set VLITENS=(Select Sum(I.QTDVENDA*I.VLUNIT) From CITENSVENDA I Where CVENDA.IDLOJA=I.IDLOJA And CVENDA.IDVENDA=I.IDVENDA)
Where VLITENS<>(Select Sum(I.QTDVENDA*I.VLUNIT) From CITENSVENDA I Where CVENDA.IDLOJA=I.IDLOJA And CVENDA.IDVENDA=I.IDVENDA)
go
Update CVENDA
Set VLVENDA=(Select Sum(I.QTDVENDA*I.VLUNIT) From CITENSVENDA I Where CVENDA.IDLOJA=I.IDLOJA And CVENDA.IDVENDA=I.IDVENDA)-CVENDA.VLDESC+VLACRESC
Where VLITENS-VLDESC+VLACRESC<>VLVENDA
go
UPDATE CPGTOSVENDA
Set VLPGTO=VLPGTO-(Select V.VLTROCO From CVENDA V Where CPGTOSVENDA.IDLOJA=V.IDLOJA And CPGTOSVENDA.IDVENDA=V.IDVENDA)
Where IDFORMAPGTO=1
and 0<>(Select VLTROCO From CVENDA V Where CPGTOSVENDA.IDLOJA=V.IDLOJA And CPGTOSVENDA.IDVENDA=V.IDVENDA)
and (Select sum(P3.VLPGTO) From CPGTOSVENDA P3 Where CPGTOSVENDA.IDLOJA=P3.IDLOJA And CPGTOSVENDA.IDVENDA=P3.IDVENDA)<>(Select V.VLVENDA From CVENDA V Where CPGTOSVENDA.IDLOJA=V.IDLOJA And CPGTOSVENDA.IDVENDA=V.IDVENDA)
go
UPDATE CVENDA
Set VLPGTO=(Select sum(P.VLPGTO) From CPGTOSVENDA P Where CVENDA.IDLOJA=P.IDLOJA And CVENDA.IDVENDA=P.IDVENDA)
Where vlvenda<>vlpgto-vltroco and idfatura=0
and 0=(Select count(F.IDFATURA) From FFATURA F Where CVENDA.IDLOJA=F.IDLOJA And CVENDA.IDVENDA=F.IDVENDA)
go

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OTPTRATAAGENDA](
	[IDLOJA] [int] NOT NULL,
	[IDTPTRATAMENTO] [int] NOT NULL,
	[IDREGRA] [int] NOT NULL,
	[TPREGRA] [int] NULL,
	[FREQUENCIA] [varchar](1) NOT NULL,
	[DIA] [datetime] NULL,
	[DIAS] [varchar](7) NULL,
	[ALTERSTAMP] [int] NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
 CONSTRAINT [PK_OTPTRATAAGENDA] PRIMARY KEY CLUSTERED 
([IDLOJA] ASC,[IDTPTRATAMENTO] ASC,	[IDREGRA] ASC)
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]) ON [PRIMARY]
GO


/*
rollback
begin transaction
select * from cvenda where idloja=3 and idvenda=2760
select * from citensvenda where idloja=3 and idvenda=2760
select * from CPGTOSVENDA where idloja=3 and idvenda=2760

select * from CVENDA Where  VLITENS-VLDESC+VLACRESC<>VLVENDA

select * from CPGTOSVENDA
Where IDFORMAPGTO=1
and 0<>(Select VLTROCO From CVENDA V Where CPGTOSVENDA.IDLOJA=V.IDLOJA And CPGTOSVENDA.IDVENDA=V.IDVENDA)
and (Select sum(P3.VLPGTO) From CPGTOSVENDA P3 Where CPGTOSVENDA.IDLOJA=P3.IDLOJA And CPGTOSVENDA.IDVENDA=P3.IDVENDA)<>(Select V.VLVENDA From CVENDA V Where CPGTOSVENDA.IDLOJA=V.IDLOJA And CPGTOSVENDA.IDVENDA=V.IDVENDA)
and idloja=3

select * from cvenda where vlvenda<>vlpgto-vltroco and idfatura=0 and idloja=3
and 0=(Select count(F.IDFATURA) From FFATURA F Where CVENDA.IDLOJA=F.IDLOJA And CVENDA.IDVENDA=F.IDVENDA)

SELECT * FROM FFATURA




*/
