DECLARE @IDCLIENTE AS INTEGER
SET @IDCLIENTE=884

Select A.IDCLIENTE, C.NOME, COUNT(S.IDSESSAO) [FEITO]
, (Select SUM(I.QTDVENDA) From CVENDA V JOIN CITENSVENDA I On V.IDLOJA=I.IDLOJA And V.IDVENDA=I.IDVENDA Where V.IDLOJA = 3 And V.IDCLIENTE=A.IDCLIENTE AND I.IDPROD=1) [PAGO]
, (Select SUM(I.QTDVENDA) From CVENDA V JOIN CITENSVENDA I On V.IDLOJA=I.IDLOJA And V.IDVENDA=I.IDVENDA Where V.IDLOJA = 3 And V.IDCLIENTE=A.IDCLIENTE AND I.IDPROD=1)-COUNT(S.IDSESSAO) [SALDO]
From OCLIENTE C 
JOIN OATENDIMENTO A ON A.IDLOJA=C.IDLOJA AND C.IDCLIENTE=A.IDCLIENTE
JOIN OSESSAO S On A.IDLOJA=S.IDLOJA And A.IDATENDIMENTO=S.IDATENDIMENTO
Where A.IDLOJA = 3
And A.IDCLIENTE in (69,185) --=@IDCLIENTE
aND S.IDTPSERVICO<>1
GROUP BY A.IDCLIENTE, C.NOME
HAVING COUNT(S.IDSESSAO)<>(Select SUM(I.QTDVENDA) From CVENDA V JOIN CITENSVENDA I On V.IDLOJA=I.IDLOJA And V.IDVENDA=I.IDVENDA Where V.IDLOJA = 3 And V.IDCLIENTE=A.IDCLIENTE AND I.IDPROD=1)
ORDER BY [SALDO]