declare @Mes int;
declare @Ano int;
Select @Mes=8;
Select @Ano=2011;

Select Distinct E.IDCLIENTE [Id.], C.NOME [Cliente], C.TEL1, C.TEL2, Convert(char, E.STARTDATETIME, 103) [Data]
, 'Teste Realizado sem Sessão' [Obs]
--, SE.DSCSERVICO [Servico], TR.DSCTRATAMENTO [Tratamento]
--, A.DSCAREA [Area]
, Convert(char, E2.STARTDATETIME, 103) [Prox. Sessão]
From OEVENTOAGENDA  E
JOIN OSERVICOEVT S On E.IDLOJA=S.IDLOJA AND E.IDEVENTO=S.IDEVENTO
JOIN OCLIENTE C On E.IDLOJA=C.IDLOJA AND E.IDCLIENTE=C.IDCLIENTE
JOIN OTPSERVICO SE On S.IDTPSERVICO=SE.IDTPSERVICO 
JOIN OTPTRATAMENTO TR On S.IDTPTRATAMENTO=TR.IDTPTRATAMENTO
JOIN OAREA A On S.IDAREA=A.IDAREA
LEFT JOIN OEVENTOAGENDA  E2 On E.IDLOJA=E2.IDLOJA AND E.IDCLIENTE=E2.IDCLIENTE AND E.STARTDATETIME<E2.STARTDATETIME
Where C.ATIVO=1
AND SE.IDTPSERVICO=1
AND E.FLGCANCELADO=0
AND Month(E.STARTDATETIME) = @Mes
AND Year(E.STARTDATETIME) = @Ano
AND E.STARTDATETIME < GETDATE()
AND E2.STARTDATETIME IS NULL
--=====================================================
--=====================================================
Union all
--=====================================================
--=====================================================
Select Distinct  E.IDCLIENTE [Id.], C.NOME [Cliente], C.TEL1, C.TEL2, Convert(char, E.STARTDATETIME, 103) [Data Teste]
, SE.DSCSERVICO+' Cancelad'+case S.IDTPSERVICO when 1 then 'o' else 'a' end [Obs]
--, SE.DSCSERVICO [Servico], TR.DSCTRATAMENTO [Tratamento]
--, A.DSCAREA [Area]
, Convert(char, E2.STARTDATETIME, 103) [Prox. Sessão]
From OEVENTOAGENDA  E
JOIN OSERVICOEVT S On E.IDLOJA=S.IDLOJA AND E.IDEVENTO=S.IDEVENTO
JOIN OCLIENTE C On E.IDLOJA=C.IDLOJA AND E.IDCLIENTE=C.IDCLIENTE
JOIN OTPSERVICO SE On S.IDTPSERVICO=SE.IDTPSERVICO 
JOIN OTPTRATAMENTO TR On S.IDTPTRATAMENTO=TR.IDTPTRATAMENTO
JOIN OAREA A On S.IDAREA=A.IDAREA
LEFT JOIN OEVENTOAGENDA  E2 On E.IDLOJA=E2.IDLOJA AND E.IDCLIENTE=E2.IDCLIENTE AND E.STARTDATETIME<E2.STARTDATETIME
--JOIN OSERVICOEVT S On E2.IDLOJA=S2.IDLOJA AND E2.IDEVENTO=S2.IDEVENTO AND S2.IDTPSERVICO=1
Where C.ATIVO=1
AND E.FLGCANCELADO=1
AND Month(E.STARTDATETIME) = @Mes
AND Year(E.STARTDATETIME) = @Ano
AND E.STARTDATETIME < GETDATE()
--AND E2.STARTDATETIME IS NULL
--=====================================================
--=====================================================
union all
--=====================================================
--=====================================================
Select DISTINCT A.IDCLIENTE [Id.], C.NOME [Cliente], C.Tel1, C.Tel2, Convert(char, A.DTATEND, 103) [Data]
, 'Atendimento Sem Remarcação' [Obs]
, Convert(char, E.STARTDATETIME, 103) [Prox. Sessão]
From OATENDIMENTO A JOIN OCLIENTE C ON A.IDCLIENTE=C.IDCLIENTE
LEFT JOIN OEVENTOAGENDA  E On E.IDLOJA=A.IDLOJA AND E.IDCLIENTE=A.IDCLIENTE AND E.STARTDATETIME>A.DTATEND
WHERE C.ATIVO=1 AND C.ISENTO=0
AND  E.STARTDATETIME  is null
AND Year(A.DTATEND) = @Ano
AND Month(A.DTATEND) >= @Mes-3
order by 2, 1 -- convert(char, E.STARTDATETIME, 103)