SELECT E.IDCLIENTE, E.SUBJECT, E.STARTDATETIME
, DATEDIFF(MINUTE, A.HHINI, A.HHFIM) [TEMPO_ATENDIMENTO]
, DATEDIFF(MINUTE, E.STARTDATETIME, E.ENDDATETIME) [TEMPO_AGENDADO]
, (SELECT count(*) FROM OSESSAO S1 WHERE S1.IDATENDIMENTO=A.IDATENDIMENTO) [QTD_ATENDIMENTO]
, (SELECT count(*) FROM OSERVICOEVT SE1 WHERE SE1.IDEVENTO=E.IDEVENTO) [QTD_AGENDADO]
--, MAX(A.DTATEND) [DATA], (SELECT MAX(A.DTATEND) FROM OATENDIMENTO A WHERE A.IDCLIENTE=E.IDCLIENTE) [DATAMAX]
FROM OEVENTOAGENDA E JOIN OATENDIMENTO A ON A.IDCLIENTE=E.IDCLIENTE 
JOIN OSERVICOEVT SE ON E.IDEVENTO=SE.IDEVENTO
JOIN OSESSAO S ON A.IDATENDIMENTO=S.IDATENDIMENTO AND S.IDTPSERVICO>1
WHERE E.STARTDATETIME>GETDATE()
AND E.IDCLIENTE>0
AND E.FLGCANCELADO=0
AND DAY(E.TIMESTAMP)=DAY(GETDATE()-1)
AND MONTH(E.TIMESTAMP)=MONTH(GETDATE()-1)
AND YEAR(E.TIMESTAMP)=YEAR(GETDATE()-1)
GROUP BY E.IDCLIENTE, E.SUBJECT, E.STARTDATETIME, E.ENDDATETIME, A.HHINI, A.HHFIM, E.IDEVENTO, A.IDATENDIMENTO
HAVING MAX(A.DTATEND)=(SELECT MAX(A.DTATEND) FROM OATENDIMENTO A WHERE A.IDCLIENTE=E.IDCLIENTE) 
AND DATEDIFF(MINUTE, E.STARTDATETIME, E.ENDDATETIME)-DATEDIFF(MINUTE, A.HHINI, A.HHFIM)>5
ORDER BY E.STARTDATETIME, E.IDCLIENTE