Select E.IDCLIENTE, E.StartDateTime, C.NOME, TS.DSCSERVICO, TT.DSCTRATAMENTO, A.DSCAREA
From OEVENTOAGENDA E 
Join OCLIENTE C On E.IDCLIENTE=C.IDCLIENTE
Join OSERVICOEVT S On E.IDEVENTO=S.IDEVENTO
Join OTPSERVICO TS On S.IDTPSERVICO=TS.IDTPSERVICO
Join OTPTRATAMENTO TT On S.IDTPTRATAMENTO=TT.IDTPTRATAMENTO
Join OAREA A On S.IDAREA=A.IDAREA
Where 
--E.STARTDATETIME>='2011-11-07 00:00'
--And E.STARTDATETIME<='2011-11-07 23:59'
 S.IDTPSERVICO <> 1
And S.IDTPTRATAMENTO = 2
Order By C.NOME, E.StartDateTime