Declare @Ano as int; Declare @Mes as int;; Declare @IDLOJA as int;
--****************************************************************
Set @IDLOJA=3
Set @Ano=2013
Set @Mes=1

IF @IDLOJA=2 USE G3R_FREGUESIA;
IF @IDLOJA=3 USE G3R_COPACABANA1;

Select L.NOME [Loja], Year(a.dtatend) [Ano],Month(a.dtatend) [Mes], F.NOME, COUNT(distinct cast(S.IDSESSAO as varchar(10))+cast(s.IDATENDIMENTO as varchar(10))) [Prod]
,  sum(V.VLDESC)/55 [Cortesia]
,  COUNT(distinct cast(S.IDSESSAO as varchar(10))+cast(s.IDATENDIMENTO as varchar(10)))-sum(V.VLDESC)/55 [Total]
From OATENDIMENTO A
Join OSESSAO S On S.IDLOJA=A.IDLOJA AND S.IDATENDIMENTO=A.IDATENDIMENTO
Join RFUNCIONARIO F On F.IDLOJA=A.IDLOJA AND F.IDFUNCIONARIO=A.IDFUNCIONARIO
Join OCLIENTE C On C.IDLOJA=A.IDLOJA AND C.IDCLIENTE=A.IDCLIENTE 
Join OATENDIMENTO_VENDA VA On VA.IDLOJA=A.IDLOJA AND VA.IDATENDIMENTO=A.IDATENDIMENTO
Join CVENDA V On V.IDLOJA=VA.IDLOJA AND V.IDVENDA=VA.IDVENDA
Join OLOJA L On L.IDLOJA=A.IDLOJA
--Join OTPTRATAMENTO T On S.IDLOJA=T.IDLOJA AND S.IDTPTRATAMENTO=T.IDTPTRATAMENTO
Where  C.ISENTO=0
AND A.IDLOJA=@IDLOJA
And year(a.dtatend)= @Ano
And month(a.dtatend) = @Mes
and S.IDTPSERVICO IN (2,3)
--And F.IDFUNCIONARIO=9
GROUP BY L.NOME, Year(a.dtatend), Month(A.DTATEND), F.NOME
UNION 
Select L.NOME [Loja], Year(S.DTMOV) [Ano], Month(S.DTMOV) [Mes], P.NMPROD [NOME]
, Sum(S.QTDITEM)*-1 [Prod], 0 [Cortesia], Sum(S.QTDITEM)*-1 [Total]
From SMOVEST S 
Join OLOJA L On L.IDLOJA=S.IDLOJA
Join SPRODUTO P On P.IDLOJA=S.IDLOJA And P.IDPROD=S.IDPROD
where S.IDPROD=2 
And S.IDLOJA=@IDLOJA
And Year(DTMOV)=@ANO 
And Month(DTMOV)=@Mes
And TPDOC='CV'
Group By L.NOME, Year(S.DTMOV), Month(S.DTMOV), P.NMPROD 
ORDER BY F.NOME, Mês


Select F.NOME [Funcionário] 
, COUNT(distinct cast(S.IDSESSAO as varchar(10))+cast(s.IDATENDIMENTO as varchar(10))) [Produção]
From OATENDIMENTO A
Join OSESSAO S On A.IDLOJA=S.IDLOJA And A.IDATENDIMENTO=S.IDATENDIMENTO
Join RFUNCIONARIO F On F.IDLOJA=A.IDLOJA AND F.IDFUNCIONARIO=A.IDFUNCIONARIO
Join OCLIENTE C On F.IDLOJA=C.IDLOJA AND C.IDCLIENTE=A.IDCLIENTE 

Join OTPSERVICO SE On SE.IDLOJA=S.IDLOJA AND SE.IDTPSERVICO=S.IDTPSERVICO
Join OLOJA L On A.IDLOJA=L.IDLOJA
WHERE A.IDLOJA=@IDLOJA
AND YEAR(A.DTATEND)=@Ano
AND MONTH(A.DTATEND)=@Mes
AND SE.IDTPSERVICO>1
AND C.ISENTO=0
GROUP BY  F.NOME
ORDER BY 1 


/*
Select Year(V.DTVENDA) [Ano], Month(V.DTVENDA) [Mês], Sum(I.QTDVENDA) [Cremes]
From CVENDA V 
Join  CITENSVENDA I On V.IDLOJA=I.IDLOJA And V.IDVENDA=I.IDVENDA
Where year(V.DTVENDA)= @Ano
--And Month(V.DTVENDA)=5
AND V.IDLOJA=@IDLOJA
And I.IDPROD=2
Group by Year(V.DTVENDA), Month(V.DTVENDA)
Order by 1,2
*/