declare @Mes as int; declare @Ano as int; 
set @Ano=2012; set @Mes=9;

Select  F.NOME+'' as [id]
, F.IDLOJA
, F.IDFUNCIONARIO
, F.NOME [Funcionário]
, SE.DSCSERVICO [Serviço]
, L.NOME [Loja]
, COUNT(distinct cast(S.IDSESSAO as varchar(10))+cast(s.IDATENDIMENTO as varchar(10))) [Producao]
From OATENDIMENTO A
Join OSESSAO S On A.IDLOJA=S.IDLOJA And A.IDATENDIMENTO=S.IDATENDIMENTO
Join RFUNCIONARIO F On F.IDLOJA=A.IDLOJA AND F.IDFUNCIONARIO=A.IDFUNCIONARIO
Join OCLIENTE C On F.IDLOJA=C.IDLOJA AND C.IDCLIENTE=A.IDCLIENTE 
Join OTPSERVICO SE On SE.IDLOJA=S.IDLOJA AND SE.IDTPSERVICO=S.IDTPSERVICO
Join OLOJA L On A.IDLOJA=L.IDLOJA
WHERE YEAR(A.DTATEND)=@Ano
AND MONTH(A.DTATEND)=@Mes
AND C.ISENTO=0
--AND L.IDLOJA=2
AND S.IDTPSERVICO IN (2,3)
GROUP BY  F.IDLOJA,  F.IDFUNCIONARIO, L.NOME, F.NOME, YEAR(DTATEND), MONTH(A.DTATEND) , SE.DSCSERVICO
Union all
--declare @Mes as int; declare @Ano as int; set @Ano=2012; set @Mes=9;
Select F.NOME+'Z'  [id], '99999' [IDLOJA], '', F.NOME [Funcionário] , '' [Serviço], 'Total :' [Loja]
, COUNT(distinct cast(S.IDSESSAO as varchar(10))+cast(s.IDATENDIMENTO as varchar(10))) [Produção]
From OATENDIMENTO A
Join OSESSAO S On A.IDLOJA=S.IDLOJA And A.IDATENDIMENTO=S.IDATENDIMENTO
Join RFUNCIONARIO F On F.IDLOJA=A.IDLOJA AND F.IDFUNCIONARIO=A.IDFUNCIONARIO
Join OCLIENTE C On F.IDLOJA=C.IDLOJA AND C.IDCLIENTE=A.IDCLIENTE 
Join OTPSERVICO SE On SE.IDLOJA=S.IDLOJA AND SE.IDTPSERVICO=S.IDTPSERVICO
Join OLOJA L On A.IDLOJA=L.IDLOJA
WHERE YEAR(A.DTATEND)=@Ano
AND MONTH(A.DTATEND)=@Mes
AND C.ISENTO=0
AND S.IDTPSERVICO IN (2,3)
GROUP BY  F.NOME, YEAR(DTATEND), MONTH(A.DTATEND) 
ORDER BY ID




--SELECT * FROM RFUNCIONARIO ORDER BY NOME
--SELECT * FROM RBATIDA WHERE ((IDLOJA=2 AND IDFUNCIONARIO=5) OR (IDLOJA=3 AND IDFUNCIONARIO=9)) ORDER BY DTBATIDA DESC

--SELECT SUM(VLDESC)/55 FROM CVENDA V
--WHERE YEAR(V.DTVENDA)=@Ano
--AND MONTH(V.DTVENDA)=@Mes
--AND VLDESC>=55