--SELECT O.NAME FROM SYSOBJECTS O JOIN SYSCOLUMNS C ON O.ID=C.ID WHERE C.NAME = 'IDRECIBO'
--O.TYPE = 'U'4
--SELECT * FROM SYSOBJECTS
--SELECT * FROM SYSCOLUMNS
--SELECT * from FRECIBO WHERE IDLOTE=0 ORDER BY IDRECIBO
--SELECT * from FRECIBO ORDER BY IDRECIBO
--UPDATE FRECIBO SET IDRECIBO = IDRECIBO-1 WHERE IDRECIBO>404
--UPDATE FNOTAFISCAL SET IDRECIBO = IDRECIBO-1 WHERE IDRECIBO>404


select * from fnotafiscal order by numnota