USE G3R;
Select C.IDTPCONHEC [ID], T.NMCONHEC [Conhecimento]
, Count(Distinct C.IDCLIENTE) [Qtd.]
, Sum(V.VLPGTO) [Valor]
From OCLIENTE C 
JOIN OTPCONHEC T On C.IDTPCONHEC=T.IDTPCONHEC
Left JOIN CVENDA V On C.IDCLIENTE=V.IDCLIENTE
Group By C.IDTPCONHEC, T.NMCONHEC
Order By [Qtd.] Desc, [Valor]

--Select T.NMCONHEC, COUNT(*) [QTD]
--From OCLIENTE C 
--JOIN OTPCONHEC T ON C.IDTPCONHEC=T.IDTPCONHEC
--WHERE C.IDCLIENTE IN (SELECT DISTINCT E.IDCLIENTE FROM OEVENTOAGENDA E 
--						WHERE MONTH(E.STARTDATETIME)>=8)
--GROUP BY T.NMCONHEC
--ORDER BY [QTD] DESC



