set dateformat 'dmy';
declare @DTINI varchar(16)
declare @DTFIM varchar(16)
set @DTINI='26/02/2011 00:00'
set @DTFIM='25/03/2011 23:59'

Select I.IDPROD, P.NMPROD, SUM(I.QTDVENDA) [Qtd.]
, SUM(I.QTDVENDA*I.VLUNIT) [Valor]
From FLAN L
Join CITENSVENDA I On L.IDLOJA=I.IDLOJA And L.IDVENDA=I.IDVENDA
Join SPRODUTO P On P.IDPROD=I.IDPROD And P.EVENDA=1 
Where L.IDLOJA=1
And L.DTVENCIMENTO>=@DTINI
And L.DTVENCIMENTO<=@DTFIM
and L.TPDOC='CV'
--And L.IDCONTA=2
Group By I.IDPROD, P.NMPROD

