set dateformat 'dmy';

declare @DTINI varchar(16)
declare @DTFIM varchar(16)
set @DTINI='26/07/2011 00:00'
set @DTFIM='25/08/2011 23:59'

Select Month(@DTFIM) [Período], S.NMPROD, SUM(I.QTDVENDA) [Qtd.Feita]
, SUM(I.QTDVENDA*I.VLUNIT) [Valor], (SUM(I.QTDVENDA*I.VLUNIT)-SUM(V.VLDESC))/55  [Qtd.Pagas]
From CVENDA V
Join CITENSVENDA I On V.IDLOJA=I.IDLOJA And V.IDVENDA=I.IDVENDA
Join SPRODUTO S On S.IDPROD=I.IDPROD And S.EVENDA=1 
Join OCLIENTE C On V.IDCLIENTE=C.IDCLIENTE And C.ISENTO=0
-- And S.ESERVICO=0 
Where V.DTVENDA>=@DTINI 
And V.DTVENDA<=@DTFIM
--and V.IDCLIENTE Not in (1,2,113,116,117,605)
--and V.IDCLIENTE Not in (57, 58, 63)
Group by S.NMPROD

Select Month(@DTFIM) [Período], S.NMPROD, SUM(I.QTDVENDA) [Qtd.]
, F.FORMAPGTO, SUM(I.QTDVENDA*I.VLUNIT) [Valor]
From CVENDA V
Join CITENSVENDA I On V.IDLOJA=I.IDLOJA And V.IDVENDA=I.IDVENDA
Join CPGTOSVENDA P On V.IDLOJA=P.IDLOJA And V.IDVENDA=P.IDVENDA
Join CFORMAPGTO F On F.IDFORMAPGTO=P.IDFORMAPGTO
Join SPRODUTO S On S.IDPROD=I.IDPROD And S.EVENDA=1 
-- And S.ESERVICO=0 
Where V.DTVENDA>=@DTINI 
And V.DTVENDA<=@DTFIM
and V.IDCLIENTE Not in (1,2,113,116,117,605)
Group by S.NMPROD, P.IDFORMAPGTO, F.FORMAPGTO
Order By S.NMPROD

