--USE G3R_COPACABANA1;


set dateformat 'dmy';

declare @DTINI varchar(16)
declare @DTFIM varchar(16)
set @DTINI='01/09/2012 00:00'
set @DTFIM='30/09/2012 23:59'

Select E.DSCSERVICO, COUNT(*) [Qtd.]
, case E.DSCSERVICO when 'Sessão' then COUNT(*)*55 else 0 end [Valor]
From OSESSAO S 
Join OATENDIMENTO A On S.IDLOJA=A.IDLOJA And S.IDATENDIMENTO=A.IDATENDIMENTO
Join OTPSERVICO E On S.IDLOJA=E.IDLOJA AND  S.IDTPSERVICO=E.IDTPSERVICO
Join OCLIENTE C On C.IDLOJA=A.IDLOJA AND C.IDCLIENTE=A.IDCLIENTE
Where A.DTATEND>=@DTINI
And A.DTATEND<=@DTFIM
and C.ISENTO=0
AND S.IDLOJA =2
--GROUP BY Month(A.DTATEND), E.DSCSERVICO
GROUP BY E.DSCSERVICO
union
Select S.NMPROD, Sum(I.QTDVENDA) [Qtd.]
, Sum(I.QTDVENDA)*I.VLUNIT [Valor]
From CVENDA V
Join CITENSVENDA I On V.IDLOJA=I.IDLOJA And V.IDVENDA=I.IDVENDA
Join SPRODUTO S On S.IDPROD=I.IDPROD And S.EVENDA=1 and S.ESERVICO=0
Where V.DTVENDA>=@DTINI
And V.DTVENDA<=@DTFIM
and V.IDCLIENTE Not in (1,2,113,116,117,605)
--Group by month(A.DTATEND), S.NMPROD
GROUP BY S.NMPROD, I.VLUNIT


/*
Select month(P.DTPGTO) [Mês],F.FORMAPGTO [Forma], SUM(P.VLPGTO) [Valor]
From CPGTOSVENDA P 
JOIN CFORMAPGTO F On P.IDFORMAPGTO=F.IDFORMAPGTO
Where month(P.DTPGTO)>=month(Getdate())
GROUP BY month(P.DTPGTO), F.FORMAPGTO
Compute Sum(SUM(P.VLPGTO))
*/