/*select A.IDCLIENTE, C.NOME, Convert(Char, A.DTATEND,103) [Data]
, datediff(mi, hhini, hhfim) [TEMPO TOTAL]
, S.IDTPSERVICO, S.IDTPTRATAMENTO, R.DSCAREA 
From OATENDIMENTO A Join OCLIENTE C On A.IDCLIENTE=C.IDCLIENTE
JOIN OSESSAO S On S.IDLOJA=A.IDLOJA And S.IDATENDIMENTO=A.IDATENDIMENTO
JOIN OAREA R On R.IDAREA=S.IDAREA
Order By IDTPSERVICO
*/
Select DISTINCT A.IDCLIENTE, C.NOME, Convert(Char, A.DTATEND,103) [Data]
, Count(S.IDAREA) [Qtd.Area], datediff(mi, hhini, hhfim) [TEMPO TOTAL], A.DTATEND

From OATENDIMENTO A Join OCLIENTE C On A.IDCLIENTE=C.IDCLIENTE
JOIN OSESSAO S On S.IDLOJA=A.IDLOJA And S.IDATENDIMENTO=A.IDATENDIMENTO
WHERE S.IDTPSERVICO<>1
AND C.ATIVO=1
GROUP BY A.IDCLIENTE, C.NOME, A.DTATEND, HHINI, HHFIM
--HAVING A.DTATEND=(Select Max(A2.DTATEND) From OATENDIMENTO A2 Where A2.IDCLIENTE=A.IDCLIENTE)
ORDER BY A.IDCLIENTE, A.DTATEND

SELECT DISTINCT A.IDCLIENTE, A.STARTDATETIME, datediff(mi, A.STARTDATETIME, A.ENDDATETIME)
, S.IDTPSERVICO
 FROM OEVENTOAGENDA A JOIN OSERVICOEVT S ON A.IDLOJA=S.IDLOJA AND A.IDEVENTO=S.IDEVENTO
WHERE A.STARTDATETIME=(SELECT MAX(A2.STARTDATETIME) FROM OEVENTOAGENDA A2 WHERE A2.IDCLIENTE=A.IDCLIENTE)
--AND A.IDCLIENTE=12 
AND S.IDTPSERVICO<>1
ORDER BY A.IDCLIENTE 

