USE [G3R]

GO
/************************************************
************************************************/
UPDATE CVENDA SET DTVENDA=(SELECT MIN(A.DTATEND )
			FROM OATENDIMENTO A 
				JOIN OATENDIMENTO_VENDA V ON A.IDATENDIMENTO=V.IDATENDIMENTO
			WHERE V.IDVENDA=CVENDA.IDVENDA)
GO			
/************************************************
************************************************/
UPDATE CPGTOSVENDA 
SET CPGTOSVENDA.DTPGTO=(SELECT V.DTVENDA 
			FROM CVENDA V 				
			WHERE V.IDVENDA=CPGTOSVENDA.IDVENDA)
GO	
/************************************************
************************************************/
UPDATE FLAN SET DTVENCIMENTO=(Select DTPGTO 
								From CPGTOSVENDA P 
								WHERE P.IDLOJA=FLAN.IDLOJA
								AND P.IDVENDA=FLAN.IDVENDA
								AND P.IDPGTO=FLAN.IDPGTO)
WHERE FLAN.IDLAN IN (Select F.IDLAN
					From CPGTOSVENDA PG JOIN FLAN F ON
								PG.IDLOJA=F.IDLOJA
								AND PG.IDVENDA=F.IDVENDA
								AND PG.IDPGTO=F.IDPGTO
								AND PG.IDFORMAPGTO IN (1,4))
And FLAN.IDCONTA=1
GO	

UPDATE FLAN SET DTBAIXA = DTVENCIMENTO WHERE IDCONTA = 1
GO

UPDATE FLAN SET DTVENCIMENTO=(Select DTPGTO+1
								From CPGTOSVENDA P 
								WHERE P.IDLOJA=FLAN.IDLOJA
								AND P.IDVENDA=FLAN.IDVENDA
								AND P.IDPGTO=FLAN.IDPGTO)
WHERE FLAN.IDLAN IN (Select F.IDLAN
					From CPGTOSVENDA PG JOIN FLAN F ON
								PG.IDLOJA=F.IDLOJA
								AND PG.IDVENDA=F.IDVENDA
								AND PG.IDPGTO=F.IDPGTO
								AND PG.IDFORMAPGTO IN (2))	
And FLAN.IDCONTA=2
GO

UPDATE FLAN SET DTVENCIMENTO=(Select DTPGTO+30 
								From CPGTOSVENDA P 
								WHERE P.IDLOJA=FLAN.IDLOJA
								AND P.IDVENDA=FLAN.IDVENDA
								AND P.IDPGTO=FLAN.IDPGTO)
WHERE FLAN.IDLAN IN (Select F.IDLAN
					From CPGTOSVENDA PG JOIN FLAN F ON
								PG.IDLOJA=F.IDLOJA
								AND PG.IDVENDA=F.IDVENDA
								AND PG.IDPGTO=F.IDPGTO
								AND PG.IDFORMAPGTO IN (3))									
And FLAN.IDCONTA=2
GO
