UPDATE OSESSAO SET OSESSAO.IDVENDA =(SELECT AV.IDVENDA FROM OATENDIMENTO_VENDA AV WHERE OSESSAO.IDLOJA=AV.IDLOJA AND OSESSAO.IDATENDIMENTO=AV.IDATENDIMENTO)
WHERE OSESSAO.IDLOJA = 3
AND OSESSAO.IDATENDIMENTO IN 
(SELECT AV2.IDATENDIMENTO FROM OATENDIMENTO_VENDA AV2 WHERE AV2.IDLOJA =3 GROUP BY AV2.IDATENDIMENTO HAVING COUNT(AV2.IDVENDA)=1)
AND (OSESSAO.IDVENDA =0 OR OSESSAO.IDVENDA IS NULL)

