INSERT USUARIO(IDUSU,IDGRUPO,SENHAUSU,NMUSU,IDCOLIGADA,DTCADASTRO,DTEXPIRAUSU,DTEXPIRASENHA,TPUSU,SITUSU,USUCADASTRO,FEXPIRASENHA,MATRUSU,ICORREIO,ECORREIO,ASSINATURA,TIMEOUT,IDSETOR,IDEMPR,LOCALTRAB,NIVELOS,NMAD,IDPESSOA,DTVALIDAUSU,TROCARSENHA) 
 VALUES('DSR','MASTER','0709040607','Diogenes Santos',1,Getdate(), NULL, NULL,'','A', 'DIO', 0, '', '', '', NULL,	0, 0, NULL,	NULL, 0, '', 0,	NULL, 0)
