/****** Object:  Database [G3R]    Script Date: 07/05/2010 22:21:04 ******
  DECLARE @retvalue int;
  EXECUTE @retvalue = master.dbo.xp_instance_regread 'HKEY_LOCAL_MACHINE'
           , 'SOFTWARE\Microsoft\MSSQLServer\Setup'
           , 'SQLDataRoot', @param = @data_dir OUTPUT
*************************************************************************/

USE [master];
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'G3R') DROP DATABASE [G3R];


DECLARE @SQLString NVARCHAR(500);
DECLARE @data_dir nvarchar(256);
SET @data_dir = (SELECT SUBSTRING(physical_name, 1, CHARINDEX(N'master.mdf', LOWER(physical_name)) - 1)
                  FROM master.sys.master_files
                  WHERE database_id = 1 AND file_id = 1);

SET @SQLString = 'CREATE DATABASE [G3R] ON  PRIMARY 
			( NAME = G3R_Data
			, FILENAME = '''+@data_dir +'\G3R.mdf'' 
			, SIZE = 3072KB 
			, MAXSIZE = UNLIMITED
			, FILEGROWTH = 10%)
			LOG ON 
			( NAME = G3R_Log
			, FILENAME = '''+@data_dir +'\G3R.ldf''
			, SIZE = 1024KB
			, MAXSIZE = UNLIMITED
			, FILEGROWTH = 10%)'

--PRINT @SQLString
EXECUTE SP_executesql @SQLString	
GO

--ALTER DATABASE G3R SET COMPATIBILITY_LEVEL = 90;
--GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
  begin
  EXEC [G3R].[dbo].[sp_fulltext_database] @action = 'disable';
end


ALTER DATABASE [G3R] SET ANSI_NULL_DEFAULT ON;
ALTER DATABASE [G3R] SET ANSI_NULLS OFF;
ALTER DATABASE [G3R] SET ANSI_PADDING OFF;
ALTER DATABASE [G3R] SET ANSI_WARNINGS OFF; 
ALTER DATABASE [G3R] SET ARITHABORT OFF;
ALTER DATABASE [G3R] SET AUTO_CLOSE OFF;
ALTER DATABASE [G3R] SET AUTO_CREATE_STATISTICS ON;
ALTER DATABASE [G3R] SET AUTO_SHRINK ON;
ALTER DATABASE [G3R] SET AUTO_UPDATE_STATISTICS ON;
ALTER DATABASE [G3R] SET CURSOR_CLOSE_ON_COMMIT OFF; 
ALTER DATABASE [G3R] SET CURSOR_DEFAULT  GLOBAL;
ALTER DATABASE [G3R] SET CONCAT_NULL_YIELDS_NULL OFF;
ALTER DATABASE [G3R] SET NUMERIC_ROUNDABORT OFF;
ALTER DATABASE [G3R] SET QUOTED_IDENTIFIER OFF;
ALTER DATABASE [G3R] SET RECURSIVE_TRIGGERS OFF; 
ALTER DATABASE [G3R] SET  DISABLE_BROKER;
ALTER DATABASE [G3R] SET AUTO_UPDATE_STATISTICS_ASYNC ON;
ALTER DATABASE [G3R] SET DATE_CORRELATION_OPTIMIZATION OFF;
ALTER DATABASE [G3R] SET TRUSTWORTHY OFF;
ALTER DATABASE [G3R] SET ALLOW_SNAPSHOT_ISOLATION OFF;
ALTER DATABASE [G3R] SET PARAMETERIZATION SIMPLE;
ALTER DATABASE [G3R] SET READ_COMMITTED_SNAPSHOT OFF;
--ALTER DATABASE [G3R] SET HONOR_BROKER_PRIORITY OFF;
--GO
ALTER DATABASE [G3R] SET  READ_WRITE;
ALTER DATABASE [G3R] SET RECOVERY SIMPLE;
ALTER DATABASE [G3R] SET  MULTI_USER;
ALTER DATABASE [G3R] SET PAGE_VERIFY CHECKSUM;
ALTER DATABASE [G3R] SET DB_CHAINING OFF;
USE [G3R]
GO